server {
    listen 80;
    server_name _;
    resolver 127.0.0.11 valid=10s ipv6=off;
    set $api_upstream http://api:3000;

    root /usr/share/nginx/html;
    index index.html;

    location = /service {
        return 301 /service/;
    }

    location /service/service-assets/ {
        rewrite ^/service/(.*)$ /$1 break;
        try_files $uri =404;
        add_header Cache-Control "public, max-age=86400";
    }

    location /service-api/ {
        proxy_pass $api_upstream/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /service/ {
        rewrite ^/service/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
