USE `aibs`;

INSERT INTO `service_items` (
  `id`,
  `title`,
  `category`,
  `description`,
  `handler_count`,
  `target_roles`,
  `target_grades`,
  `target_colleges`,
  `target_campuses`,
  `entry_url`,
  `department`,
  `contact_person`,
  `contact_phone`,
  `service_time`,
  `basis`,
  `materials`,
  `process_steps`,
  `notice`,
  `keywords`,
  `faq`,
  `status`,
  `source_url`,
  `last_verified_at`
) VALUES (
  'electricity-transfer-dorm-guide',
  '电费转账填写指南',
  '校园缴费',
  '根据学生住宿信息提示电费转账页面中区域、用途、楼宇、楼层、房间应如何选择，减少充错房间。',
  NULL,
  JSON_ARRAY('本科生', '研究生'),
  NULL,
  NULL,
  NULL,
  'https://myvpn.ahau.edu.cn:10443/http/webvpn47107d807fd53f8c72c1effc7563ea4f/ZSANAPP/WEB/PowerGridTransferAuth.aspx',
  '财务处 / 一卡通微门户',
  '陈老师',
  '0551-65786419',
  '任何时间',
  '-',
  JSON_ARRAY('本人住宿信息', '校园卡'),
  JSON_ARRAY(
    '进入电费转账页面',
    '根据系统提示选择区域、用途、楼宇、楼层、房间',
    '确认宿舍信息无误后输入转账金额',
    '支付完成后，持卡前往自助多媒体写卡，完成校园卡余额更新操作'
  ),
  'AI 办事会优先根据 xszsxx 学生住宿信息生成填写指南。请核对楼宇、楼层、房间后再付款，避免充错房间。',
  JSON_ARRAY('电费', '电费转账', '电费充值', '充电费', '宿舍电费', '照明费', '空调费', '空调电费', '一卡通'),
  JSON_ARRAY(),
  'ENABLED',
  'https://myvpn.ahau.edu.cn:10443/http/webvpn47107d807fd53f8c72c1effc7563ea4f/ZSANAPP/WEB/PowerGridTransferAuth.aspx',
  '2026-06-17 00:00:00.000'
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `target_roles` = VALUES(`target_roles`),
  `entry_url` = VALUES(`entry_url`),
  `department` = VALUES(`department`),
  `contact_person` = VALUES(`contact_person`),
  `contact_phone` = VALUES(`contact_phone`),
  `service_time` = VALUES(`service_time`),
  `materials` = VALUES(`materials`),
  `process_steps` = VALUES(`process_steps`),
  `notice` = VALUES(`notice`),
  `keywords` = VALUES(`keywords`),
  `status` = VALUES(`status`),
  `source_url` = VALUES(`source_url`),
  `last_verified_at` = VALUES(`last_verified_at`),
  `updated_at` = CURRENT_TIMESTAMP(3);
