USE `aibs`;

INSERT INTO `service_items` (
  `id`,
  `title`,
  `category`,
  `description`,
  `handler_count`,
  `target_roles`,
  `entry_url`,
  `department`,
  `contact_person`,
  `contact_phone`,
  `service_time`,
  `basis`,
  `materials`,
  `process_steps`,
  `notice`,
  `keywords`,
  `status`,
  `source_url`,
  `last_verified_at`
) VALUES
(
  'principal-secretary-mailbox',
  '书记校长信箱',
  '校务服务',
  '书记校长信箱平台是在校师生与学校沟通交流的重要渠道，是学校联系师生、服务师生、凝聚师生的重要平台，您的来信学校将按规定处理，并尽快向您答复。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://xzxx.ahau.edu.cn/hmbwebapp/pmb/pmbhome/home.html?random=0.26669100176579286',
  '党政办公室',
  '岳老师',
  '0551-65786020',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('实名来信人员信息', '简明扼要、事实清楚、诉求明确的来信内容'),
  JSON_ARRAY(
    '阅读写信须知',
    '实名填写来信人员信息',
    '按照一信一事原则描述意见、建议、咨询或诉求',
    '学校按规定处理并尽快答复',
    '流程结束后对处理结果作出客观评价'
  ),
  '来信应遵守宪法、法律、法规和社会公德，用语文明友善，不得捏造、歪曲事实。已经或依法应当通过诉讼、仲裁、行政复议等法定途径解决的事项，以及与学校职责无关的个人问题，不予受理。',
  JSON_ARRAY('书记校长信箱', '书记信箱', '校长信箱', '意见建议', '投诉', '咨询', '反馈', '学校沟通'),
  'ENABLED',
  'https://xzxx.ahau.edu.cn/hmbwebapp/pmb/pmbhome/home.html?random=0.26669100176579286',
  '2026-06-14 00:00:00.000'
),
(
  'cloud-drive-service',
  '云盘服务',
  '信息化服务',
  '为师生提供大容量文件存储服务。每个用户云盘容量默认 1000GB。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://pan.ahau.edu.cn/cloudservice/home.html',
  '数据管理处（信息化办公室）',
  '许老师',
  '0551-65786196',
  '任何时间',
  '-',
  JSON_ARRAY('已激活的数智安农账号'),
  JSON_ARRAY(
    '师生在数智安农账号激活后，即具有云盘使用权限',
    '进入“数智安农 / 安心办 / 云盘服务”',
    '申请或进入云盘使用',
    '使用前可先查看图文或视频教程'
  ),
  '使用前请参阅图文或视频教程。',
  JSON_ARRAY('云盘', '网盘', '文件存储', '大容量', '数智安农', '信息化', '数据管理处'),
  'ENABLED',
  'https://pan.ahau.edu.cn/cloudservice/home.html',
  '2026-06-14 00:00:00.000'
),
(
  'sports-venue-reservation',
  '体育场馆预约',
  '校园生活',
  '为进一步提升学校体育场馆的使用效能，面向在校学生在非教学时间段提供场地预约服务，包含校本部第三运动场羽毛球馆、九华山路校区乒羽运动馆等场地。',
  NULL,
  JSON_ARRAY('场馆预约系统管理员', '本科生', '研究生', '场馆预约-研究生院'),
  'https://my.ahau.edu.cn/default/work/process/processManager/managePageIndex.jsp?businessCode=ahau_cgyyxt',
  '体育部',
  '体育场馆管理人员',
  '校本部李老师：0551-65786023；九华山路校区高老师：18361228019',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('数智安农账号', '预约时间段'),
  JSON_ARRAY(
    '在校学生通过数智安农“体育场馆预约”提交预约',
    '每生每天可以预定不超过一小时',
    '每天中午 12 时开放预约本日 12 时以后及次日空闲场地',
    '如显示预约时间为空白，表示场地已全部预约满，请于次日中午 12:00 后预约',
    '如不能按预约时间来馆锻炼，须于预约时间 2 小时前取消'
  ),
  '九华山路校区体育场馆资源有限，仅限九华山路校区学生预约使用。未按要求取消预约，后续可能被限制预约。',
  JSON_ARRAY('体育场馆', '场馆预约', '羽毛球', '乒乓球', '运动场', '体育部', '九华山路校区'),
  'ENABLED',
  'https://my.ahau.edu.cn/default/work/process/processManager/managePageIndex.jsp?businessCode=ahau_cgyyxt',
  '2026-06-14 00:00:00.000'
),
(
  'meeting-room-reservation',
  '会议室在线预约',
  '校园服务',
  '为在校师生提供会议室预约服务，服务范围包含安徽农业大学本部各教学办公楼宇、各单位部门已登记管理员信息并开放服务的会议室，以及九华山路校区综合楼、1 号楼。',
  7354,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://my.ahau.edu.cn/default/work/process/processManager/managePageIndex.jsp?businessCode=ahau_hyszxyygl',
  '国有资产管理处、采购与招标中心',
  '各会议室管理员老师',
  '-',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('数智安农账号', '预约会议室信息', '使用时间段'),
  JSON_ARRAY('进入会议室在线预约系统', '选择开放预约的会议室', '填写使用时间和预约信息', '提交后等待管理员处理'),
  '具体会议室开放范围和管理员要求，以系统内显示为准。',
  JSON_ARRAY('会议室', '会议室预约', '在线预约', '国资处', '采购与招标中心', '九华山路校区'),
  'ENABLED',
  'https://my.ahau.edu.cn/default/work/process/processManager/managePageIndex.jsp?businessCode=ahau_hyszxyygl',
  '2026-06-14 00:00:00.000'
),
(
  'student-archive-destination-query',
  '学生档案去向查询',
  '档案服务',
  '提供学生档案去向在线查询服务。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://archxs.ahau.edu.cn/#/queryStudentByNet',
  '图书馆、档案馆',
  '张老师',
  '0551-65786525',
  '任何时间',
  '-',
  JSON_ARRAY('学生身份信息'),
  JSON_ARRAY('进入学生档案去向查询页面', '按页面要求填写身份信息', '提交查询并查看档案去向结果'),
  '档案去向信息以档案馆系统查询结果为准。',
  JSON_ARRAY('学生档案', '档案去向', '档案查询', '毕业档案', '档案馆', '图书馆档案馆'),
  'ENABLED',
  'https://archxs.ahau.edu.cn/#/queryStudentByNet',
  '2026-06-14 00:00:00.000'
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `handler_count` = VALUES(`handler_count`),
  `target_roles` = VALUES(`target_roles`),
  `entry_url` = VALUES(`entry_url`),
  `department` = VALUES(`department`),
  `contact_person` = VALUES(`contact_person`),
  `contact_phone` = VALUES(`contact_phone`),
  `service_time` = VALUES(`service_time`),
  `basis` = VALUES(`basis`),
  `materials` = VALUES(`materials`),
  `process_steps` = VALUES(`process_steps`),
  `notice` = VALUES(`notice`),
  `keywords` = VALUES(`keywords`),
  `status` = VALUES(`status`),
  `source_url` = VALUES(`source_url`),
  `last_verified_at` = VALUES(`last_verified_at`);
