USE `aibs`;

INSERT INTO `service_items` (
  `id`,
  `title`,
  `category`,
  `description`,
  `handler_count`,
  `target_roles`,
  `entry_url`,
  `department`,
  `contact_person`,
  `contact_phone`,
  `service_time`,
  `basis`,
  `materials`,
  `process_steps`,
  `notice`,
  `keywords`,
  `faq`,
  `status`,
  `source_url`,
  `last_verified_at`
) VALUES
(
  'undergraduate-admission-score-line-query',
  '高招分数线查询',
  '招生服务',
  '面向社会考生，提供历年安徽农业大学录取分数线查询。',
  NULL,
  JSON_ARRAY('全部人员'),
  'https://app.ahau.edu.cn/recruit/public/zsxsxxCountSearchMobile.jsp',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '曹老师',
  '0551-65786603',
  '任何时间',
  '-',
  JSON_ARRAY('考生查询相关信息'),
  JSON_ARRAY('进入高招分数线查询页面', '按页面提示选择年份、地区或科类等条件', '查看历年录取分数线'),
  '查询结果以学校招生系统发布信息为准。',
  JSON_ARRAY('高招分数线', '录取分数线', '历年分数线', '招生分数线', '高考录取', '招生查询', '曹老师'),
  JSON_ARRAY(),
  'ENABLED',
  'https://app.ahau.edu.cn/recruit/public/zsxsxxCountSearchMobile.jsp',
  '2026-06-15 00:00:00.000'
),
(
  'fixed-vehicle-payment',
  '固定车缴费',
  '保卫服务',
  '面向教职工提供固定车辆相关缴费入口。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://xssq.ahau.edu.cn/security/h5/#/pkgFixedVehicle/payCar/payCar',
  '保卫处',
  '-',
  '-',
  '-',
  '-',
  JSON_ARRAY('固定车辆相关信息'),
  JSON_ARRAY('进入固定车缴费页面', '按页面提示登录并确认车辆信息', '完成固定车辆缴费'),
  '具体缴费金额、车辆权限和办理结果以保卫处系统显示为准。',
  JSON_ARRAY('固定车缴费', '车辆缴费', '固定车辆', '车牌缴费', '保卫处', '车辆入校'),
  JSON_ARRAY(),
  'ENABLED',
  'https://xssq.ahau.edu.cn/security/h5/#/pkgFixedVehicle/payCar/payCar',
  '2026-06-15 00:00:00.000'
),
(
  'teacher-theory-course-adjustment',
  '教师调停课（理论课）办理',
  '教务服务',
  '各位老师根据教学安排需要进行理论课调停的，需要进行调停课申请。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://bkjw.ahau.edu.cn/manager/for-teacher/schedule-change-apply',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '张老师',
  '0551-65786861',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('理论课调停课申请表（纸质）'),
  JSON_ARRAY('教师须提前 2 天下载并填写调停课申请表，一门课程一张表，一式两份', '教师将调停课申请表交给本教研室主任（或系主任）审核、签字', '教学副院长对教师提交的申请表进行审核', '符合要求的由教务科审查并处理，不同意或手续不完整的应及时告知教师并退回', '学院盖章后，一份报送教务处教学科，另一份由学院教学督导办公室留存', '教务科审核通过后接收申请表并告知学生课程调停办理结果', '教务科将调停课申请表移交给学校教学督导办公室'),
  '理论课调停课申请表下载：http://i.ahau.edu.cn/_upload/ueditor/file/20231101/1698802447942049159.doc。',
  JSON_ARRAY('调停课', '理论课调停课', '教师调课', '教师停课', '课程调整', '教务系统', '张老师', '调停课申请表'),
  JSON_ARRAY(
    JSON_OBJECT('question', '理论课调停课申请表在哪里下载', 'answer', '可下载理论课调停课申请表：http://i.ahau.edu.cn/_upload/ueditor/file/20231101/1698802447942049159.doc。')
  ),
  'ENABLED',
  'https://bkjw.ahau.edu.cn/manager/for-teacher/schedule-change-apply',
  '2026-06-15 00:00:00.000'
),
(
  'sms-platform-admin-application',
  '短信平台管理员申请',
  '信息化服务',
  '安徽农业大学短信管理员申请平台负责管理各业务单位和学院短信发送管理员申请流程。信息化办公室负责平台建设和管理工作，各单位指派一名负责同志分管本单位短信平台工作，并在短信管理员申请平台上完成相关流程申请。',
  32,
  JSON_ARRAY('教职工'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.dxptglysq.dxptglysq',
  '数据管理处（信息化办公室）',
  '康琳琳',
  '0551-65786196',
  '工作日正常办公时间',
  '《关于印发〈安徽农业大学短信平台使用管理办法〉的通知》',
  JSON_ARRAY('短信平台管理员申请信息'),
  JSON_ARRAY('各单位明确一名负责同志分管本单位短信平台工作', '各单位信息员作为本单位短信平台使用管理人员在线提交申请', '部门领导审核', '信息化办公室领导审核', '信息化办公室短信平台管理员授权', '流程结束'),
  '该事项目前被标记为暂不可用，先入库保留资料，暂不向用户推荐或返回。',
  JSON_ARRAY('短信平台管理员申请', '短信管理员', '短信平台', '短信发布权限', '康琳琳', '信息化办公室'),
  JSON_ARRAY(),
  'DISABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.dxptglysq.dxptglysq',
  '2026-06-15 00:00:00.000'
),
(
  'campus-activity-application',
  '校园活动申办',
  '保卫服务',
  '面向教职工、本科生、研究生提供校园活动申办服务。活动主办方填写《学生活动户外场地申请表》，由校团委审核通过并盖章；关注安农卫士微信公众号，点击底部菜单办事大厅、各类车辆门禁，手机号验证码登录后选择校园活动申办，填写信息并提交。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://xssq.ahau.edu.cn/security/h5/#/pages/login/login1',
  '保卫处',
  '薛老师',
  '0551-65786766',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('学生活动户外场地申请表（拍照上传）'),
  JSON_ARRAY('活动主办方填写《学生活动户外场地申请表》', '由校团委审核通过并盖章', '关注安农卫士微信公众号，点击底部菜单办事大厅、各类车辆门禁', '使用手机号验证码登录', '选择校园活动申办', '填写信息并根据描述上传对应图片材料', '提交后等待审核管理员审核', '可在我的校园活动申办记录中查看活动申办处理状态'),
  '学生活动户外场地申请表附件：https://i.ahau.edu.cn/_upload/ueditor/file/20250305/1741170476405061165.docx。',
  JSON_ARRAY('校园活动申办', '活动申办', '学生活动户外场地申请表', '安农卫士', '车辆门禁', '保卫处', '薛老师'),
  JSON_ARRAY(
    JSON_OBJECT('question', '校园活动申办需要什么材料', 'answer', '需要上传已审核盖章的《学生活动户外场地申请表》，附件地址：https://i.ahau.edu.cn/_upload/ueditor/file/20250305/1741170476405061165.docx。')
  ),
  'ENABLED',
  'https://xssq.ahau.edu.cn/security/h5/#/pages/login/login1',
  '2026-06-15 00:00:00.000'
),
(
  'public-course-selection',
  '公开课选课',
  '教务服务',
  '公开课选课入口。该事项当前面向对象标注为数据管理处测试。',
  NULL,
  JSON_ARRAY('数据管理处测试'),
  'https://bkjw.ahau.edu.cn/course-selection/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXB3aXNkb20iLCJleHAiOjE3ODE1NzYyNTUsInVzZXJuYW1lIjoiMjAwMzA5MyJ9.aY2fjsNsm7E6B5_ywhbVbo18WbRrSL9Lu9tL1T7T5KM#/noturn',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '张老师',
  '0551-65786861',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY(),
  JSON_ARRAY('进入公开课选课页面', '按页面提示进行选课操作'),
  '该事项目前面向对象为测试范围，先入库但保持 DISABLED，暂不向普通用户推荐或返回。',
  JSON_ARRAY('公开课选课', '选课', '公开课', '教务系统', '张老师'),
  JSON_ARRAY(),
  'DISABLED',
  'https://bkjw.ahau.edu.cn/course-selection/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXB3aXNkb20iLCJleHAiOjE3ODE1NzYyNTUsInVzZXJuYW1lIjoiMjAwMzA5MyJ9.aY2fjsNsm7E6B5_ywhbVbo18WbRrSL9Lu9tL1T7T5KM#/noturn',
  '2026-06-15 00:00:00.000'
),
(
  'special-network-account-application',
  '特殊网络账号申请',
  '信息化服务',
  '面向校园内务工的校外人员或二级学院公共机房等特殊场景提供特殊网络账号申请。外服单位原则上建议优先使用运营商宽带账号，确因工作需要使用互联网服务师生工作的，可由主管单位工作人员通过智慧安农办理特殊账号开户。',
  25,
  JSON_ARRAY('教职工'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.tswlzhsq.workflowFile',
  '数据管理处（信息化办公室）',
  '康琳琳',
  '0551-65786196',
  '工作日正常办公时间',
  '关于印发《安徽农业大学网络服务收费办法》的通知（校财字[2021] 13号）',
  JSON_ARRAY('特殊网络账号申请信息', '外服单位或公共机房相关说明'),
  JSON_ARRAY('用户提出申请', '信息化办公室工作人员预审', '所属单位领导审批同意', '信息化办公室领导审批同意', '信息化办公室工作人员开通特殊账号，反馈给申请人账号密码'),
  '该事项目前被标记为暂不可用，先入库保留资料，暂不向用户推荐或返回。特殊账号（外服单位）月租 30 元，不限时长、流量，每月首次登录成功即扣当月月租，账号同时在线终端数 1 台。机房专用账号免费使用，仅限公共机房网络区域使用，使用时段为 07:00-22:00。',
  JSON_ARRAY('特殊网络账号申请', '特殊网络账号', '外服单位账号', '机房专用账号', '校园网账号', '康琳琳'),
  JSON_ARRAY(),
  'DISABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.tswlzhsq.workflowFile',
  '2026-06-15 00:00:00.000'
),
(
  'enterprise-wechat-service',
  '企业微信服务',
  '信息化服务',
  '安徽农业大学企业微信上线试运行，作为数智安农的校园通讯平台使用。教职工加入后自动进入单位群，学生加入后自动进入班级群，与普通微信功能几乎相同，自带@安徽农业大学金标，工作台自带丰富的服务分类和快捷应用。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://xxb.ahau.edu.cn/info/1181/5971.htm',
  '数据管理处（信息化办公室）',
  '许老师',
  '0551-65786196',
  '任何时间',
  '关于安徽农业大学企业微信上线试运行的通知：http://xxb.ahau.edu.cn/info/1041/5881.htm',
  JSON_ARRAY('数智安农统一身份认证账号', '微信或手机浏览器'),
  JSON_ARRAY('师生使用微信或者手机浏览器扫码，通过统一身份认证加入安徽农业大学企业微信组织', '加入组织后，可选择下载企业微信客户端（电脑端、移动端）或者使用微信插件方式使用安徽农业大学企业微信', '移动端可通过应用市场、App Store 等搜索“企业微信”下载安装', '电脑端可从腾讯企业微信官方网站下载：https://work.weixin.qq.com/#indexDownload', '加入学校企业微信组织后，通过私人微信扫码关注“安徽农业大学”企业号，使用微信插件收发安徽农业大学企业微信消息并使用部分快捷功能'),
  '扫码注册、安装、使用教程详情请参阅《师生加入安徽农业大学企业微信》：https://xxb.ahau.edu.cn/info/1181/5971.htm。二维码可能存在时效性，长期办理请以教程页面最新二维码为准。',
  JSON_ARRAY('企业微信', '安徽农业大学企业微信', '企微', '单位群', '班级群', '微信插件', '身份认证', '许老师', '金标'),
  JSON_ARRAY(
    JSON_OBJECT('question', '企业微信怎么下载', 'answer', '移动端可在应用市场或 App Store 搜索“企业微信”；电脑端可访问腾讯企业微信官网下载：https://work.weixin.qq.com/#indexDownload。'),
    JSON_OBJECT('question', '企业微信怎么加入学校组织', 'answer', '使用微信或手机浏览器扫码，通过统一身份认证加入安徽农业大学企业微信组织，具体以学校教程 https://xxb.ahau.edu.cn/info/1181/5971.htm 为准。')
  ),
  'ENABLED',
  'https://xxb.ahau.edu.cn/info/1181/5971.htm',
  '2026-06-15 00:00:00.000'
),
(
  'union-branch-fund-approval',
  '分工会经费使用审批',
  '工会服务',
  '分工会经费申请使用审批已经按照财务制度要求，在财务系统-网络报销系统实现。申请人进入财务系统-网络报销系统，在相应模块提交经费使用信息，进行网络报销。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://wycw.ahau.edu.cn/zhcw/bizmall',
  '工会',
  '工会主席',
  '-',
  '-',
  '《安徽省基层工会经费收支管理实施办法》皖工发[2021]41号',
  JSON_ARRAY('经费支出汇总单', '相关财务票据或证明材料'),
  JSON_ARRAY('分工会（教职工协会）经办人申请', '填写《费用支出汇总单》并准备相关财务凭证', '分工会（教职工协会）主席（会长）审批', '业务真实免证明判断', '校工会主席审批', '金额超过 20000 元的，分管校领导审批', '财务处审批', '出纳支付'),
  '请进入财务系统-网络报销系统，在相应模块提交经费使用信息并办理网络报销。',
  JSON_ARRAY('分工会经费', '工会经费', '经费使用审批', '网络报销', '财务系统', '工会主席', '出纳支付'),
  JSON_ARRAY(),
  'ENABLED',
  'https://wycw.ahau.edu.cn/zhcw/bizmall',
  '2026-06-15 00:00:00.000'
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `handler_count` = VALUES(`handler_count`),
  `target_roles` = VALUES(`target_roles`),
  `entry_url` = VALUES(`entry_url`),
  `department` = VALUES(`department`),
  `contact_person` = VALUES(`contact_person`),
  `contact_phone` = VALUES(`contact_phone`),
  `service_time` = VALUES(`service_time`),
  `basis` = VALUES(`basis`),
  `materials` = VALUES(`materials`),
  `process_steps` = VALUES(`process_steps`),
  `notice` = VALUES(`notice`),
  `keywords` = VALUES(`keywords`),
  `faq` = VALUES(`faq`),
  `status` = VALUES(`status`),
  `source_url` = VALUES(`source_url`),
  `last_verified_at` = VALUES(`last_verified_at`);

INSERT INTO `service_item_assets` (
  `id`,
  `service_item_id`,
  `asset_type`,
  `title`,
  `url`,
  `alt_text`,
  `sort_order`
) VALUES
(
  'teacher-theory-course-adjustment-flow',
  'teacher-theory-course-adjustment',
  'image',
  '教师调停课办理流程',
  '/service-assets/teacher-theory-course-adjustment-flow.png',
  '教师调停课理论课办理流程图',
  1
),
(
  'sms-platform-admin-application-flow',
  'sms-platform-admin-application',
  'image',
  '短信平台管理员申请流程',
  '/service-assets/sms-platform-admin-application-flow.png',
  '短信平台管理员申请流程图',
  1
),
(
  'campus-activity-application-flow',
  'campus-activity-application',
  'image',
  '校园活动申办流程',
  '/service-assets/campus-activity-application-flow.png',
  '校园活动申办流程图',
  1
),
(
  'special-network-account-application-flow',
  'special-network-account-application',
  'image',
  '特殊网络账号申请流程',
  '/service-assets/special-network-account-application-flow.png',
  '特殊网络账号申请流程图',
  1
),
(
  'enterprise-wechat-gold-tag',
  'enterprise-wechat-service',
  'image',
  '企业微信学校金标示例',
  '/service-assets/enterprise-wechat-gold-tag.png',
  '安徽农业大学企业微信金标示例截图',
  1
),
(
  'enterprise-wechat-identity-qr',
  'enterprise-wechat-service',
  'image',
  '企业微信身份认证二维码',
  '/service-assets/enterprise-wechat-identity-qr.png',
  '安徽农业大学企业微信身份认证二维码截图',
  2
),
(
  'enterprise-wechat-plugin-qr-example',
  'enterprise-wechat-service',
  'image',
  '企业微信微信插件二维码示例',
  '/service-assets/enterprise-wechat-plugin-qr-example.png',
  '安徽农业大学企业微信插件二维码示例截图，二维码可能存在时效性',
  3
),
(
  'union-branch-fund-approval-flow',
  'union-branch-fund-approval',
  'image',
  '分工会经费使用审批流程',
  '/service-assets/union-branch-fund-approval-flow.png',
  '分工会经费使用审批流程图',
  1
)
ON DUPLICATE KEY UPDATE
  `service_item_id` = VALUES(`service_item_id`),
  `asset_type` = VALUES(`asset_type`),
  `title` = VALUES(`title`),
  `url` = VALUES(`url`),
  `alt_text` = VALUES(`alt_text`),
  `sort_order` = VALUES(`sort_order`);
