USE `aibs`;

INSERT INTO `service_items` (
  `id`,
  `title`,
  `category`,
  `description`,
  `handler_count`,
  `target_roles`,
  `entry_url`,
  `department`,
  `contact_person`,
  `contact_phone`,
  `service_time`,
  `basis`,
  `materials`,
  `process_steps`,
  `notice`,
  `keywords`,
  `faq`,
  `status`,
  `source_url`,
  `last_verified_at`
) VALUES
(
  'undergraduate-admission-result-query',
  '高招录取结果查询',
  '招生服务',
  '面向社会报考我校的考生，在省教育厅和省教育招生考试院的指导下，在年度招生录取查阅期间，提供高招录取查询服务。',
  NULL,
  JSON_ARRAY('全部人员'),
  'https://app.ahau.edu.cn/recruit/public/zscx.jsp',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '曹老师',
  '0551-65786603',
  '视具体情况而定',
  '-',
  JSON_ARRAY('考生相关查询信息'),
  JSON_ARRAY('进入高招录取结果查询页面', '按页面要求填写考生信息', '提交后查看录取查询结果'),
  '该服务仅在年度招生录取查询期间开放，具体查询时间以学校招生相关通知为准。',
  JSON_ARRAY('高招录取', '录取结果', '招生查询', '录取查询', '考生', '招生办'),
  JSON_ARRAY(),
  'ENABLED',
  'https://app.ahau.edu.cn/recruit/public/zscx.jsp',
  '2026-06-15 00:00:00.000'
),
(
  'fixed-ip-address-application',
  '固定IP地址申请',
  '信息化服务',
  '固定IP地址申请是指在校园内（非数据中心机房）因接入设备特性、管理等必须使用固定 IP 地址接入校园网的特定场景服务。适用于教学实训机房、多媒体教室、空调照明热水能源监管、楼宇安防、信息发布、消防联动设施、科研物联网平台等接入场景。',
  8,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.gdipdzsq.gdipdzsq',
  '数据管理处（信息化办公室）',
  '张武',
  '0551-65786196',
  '工作日正常办公时间',
  '《中华人民共和国网络安全法》；《网络安全等级保护2.0标准》；《互联网用户账号信息管理规定》',
  JSON_ARRAY('固定 IP 地址申请信息', '接入设备或场景说明', '申请单位网络安全责任承诺'),
  JSON_ARRAY('申请人在“智慧安农-固定IP地址申请”填写申请信息', '信息预审', '所在单位审批', '信息化办公室审批', '审批结束后分配固定 IP 地址', '信息化办工作人员线下协助完成 IP 地址配置及调测', '流程结束'),
  '设备设施接入校园网络不得占用原办公属性端口，需供应商或施工单位按校园网络接入要求重新布放信息点。申请单位须遵守网络安全法律法规和学校相关规定，并承担网络安全责任。',
  JSON_ARRAY('固定IP', '固定IP地址', 'IP地址申请', '校园网IP', '网络接入', '多媒体教室', '信息发布', '物联网', '张武'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.gdipdzsq.gdipdzsq',
  '2026-06-15 00:00:00.000'
),
(
  'digital-agriculture-password-service',
  '数智安农密码服务',
  '信息化服务',
  '“数智安农”融合门户作为学校教学、管理、科研、生活等应用系统和“安心办”平台的统一入口，账号密码是用户登录的重要凭证。数智安农支持用户自助重置或修改密码。密码服务提供用户账号密码重置、密码申诉（含忘记、复学、延期毕业、校园邮箱）等相关特殊情况的人工服务。',
  NULL,
  JSON_ARRAY('研究生', '教职工', '本科生'),
  'https://wk.ahau.edu.cn/default/work/ahau_mmsssq/mmsssq/nmIndex.jsp',
  '数据管理处（信息化办公室）',
  '康老师、王老师、许老师、陈老师',
  '0551-65786196',
  '工作日正常办公时间',
  '关于加强全校统一身份认证用户密码规则的通知：https://www.ahau.edu.cn/info/2351/125261.htm',
  JSON_ARRAY('工号或学号', '证件号', '当前使用手机号', '密码申诉所需说明材料'),
  JSON_ARRAY('大一、研一新生或新进教职工首次登录“数智安农”必须激活账号', '输入正确的工号/学号、证件号，并绑定当前使用手机号', '用户忘记密码时可采用自助找回或密码申诉（人工重置）两种方式重置密码', '休学复学、延期毕业等账号异常学生可使用密码申诉功能', '本科生院或研究生院老师先审核学籍情况，再由数据管理处工作人员受理密码重置并短信反馈', '已毕业、已办理学籍异动的学生账号仍允许登录数智安农，但授权应用和信息查阅范围有限'),
  '详细操作可参阅图文教程“重置数智安农密码（校园网密码）”和视频教程“数智安农密码问题处理”。数据管理处办公电话 65786196，网络运维服务热线 65785674。',
  JSON_ARRAY('数智安农密码', '密码服务', '忘记密码', '密码申诉', '账号激活', '校园网密码', '统一身份认证', '复学', '延期毕业', '校园邮箱密码'),
  JSON_ARRAY(
    JSON_OBJECT('question', '忘记数智安农密码怎么办', 'answer', '可使用自助找回或密码申诉功能，按页面要求填写信息后办理。'),
    JSON_OBJECT('question', '账号激活在哪里办理', 'answer', '首次登录时在数智安农登录页选择账号激活，输入工号/学号、证件号并绑定手机号。'),
    JSON_OBJECT('question', '密码申诉适用于哪些情况', 'answer', '适用于忘记密码、休学复学、延期毕业、校园邮箱等特殊情况的人工密码重置。')
  ),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/work/ahau_mmsssq/mmsssq/nmIndex.jsp',
  '2026-06-15 00:00:00.000'
),
(
  'bu-dao-le-pao',
  '步道乐跑',
  '体育服务',
  '用于本科生校园日常体育锻炼记录、线上免跑申请、体测成绩查询。研究生及教职工日常体育锻炼记录可下载“步道乐跑”App了解详情。',
  NULL,
  JSON_ARRAY('本科生'),
  'https://oa.ahau.edu.cn/info/inforead/view.shtml?e_infocolid=2&e_id=16685',
  '体育部',
  '卜老师 李老师',
  '18822136882 15932761798',
  '-',
  '-',
  JSON_ARRAY('步道乐跑 App', '本科生体育锻炼记录相关信息'),
  JSON_ARRAY('下载并使用“步道乐跑”App', '按体育部要求完成校园日常体育锻炼记录', '需要时可进行线上免跑申请或查询体测成绩'),
  '具体使用规则以体育部通知和“步道乐跑”App说明为准。',
  JSON_ARRAY('步道乐跑', '乐跑', '免跑申请', '体测成绩', '体育锻炼', '校园跑', '体育部'),
  JSON_ARRAY(
    JSON_OBJECT('question', '步道乐跑使用手册在哪里', 'answer', '可查看“步道乐跑”App使用手册 PDF：https://i.ahau.edu.cn/ywtbapi/rhmhUpload/serviceAttachments/545951d37ad0d99706fb196e239cbed6a2e2e46a9264f6c91eba7b6b64141f9b.pdf')
  ),
  'ENABLED',
  'https://oa.ahau.edu.cn/info/inforead/view.shtml?e_infocolid=2&e_id=16685',
  '2026-06-15 00:00:00.000'
),
(
  'retired-faculty-hospitalization-condolence-registration',
  '离退休教职工住院慰问线上登记',
  '离退休服务',
  '住院慰问登记分为线上和线下两种方式，任选一种方式，无需重复登记。离退休职工出院后，可在线填报相关慰问信息，上传出院小结并提交。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.ghhywwsb.ghhywwsb',
  '离退休工作处、离退休工作处党总支',
  '高老师',
  '0551-65786928',
  '发放完成为止',
  '-',
  JSON_ARRAY('出院小结', '住院慰问登记相关信息'),
  JSON_ARRAY('离退休职工出院后进入“数智安农—安心办—离退休工作处—离退休教职工住院慰问线上登记”', '填报相关慰问信息', '上传出院小结', '提交登记', '也可出院后携带出院小结复印件 2 份到离退休工作处一楼 103 办公室线下登记'),
  '同种疾病每年只慰问 1 次。住院慰问登记每月月底向校人事处报一次。线上和线下任选一种方式，无需重复登记。',
  JSON_ARRAY('离退休', '住院慰问', '慰问登记', '出院小结', '离退休工作处', '高老师'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.ghhywwsb.ghhywwsb',
  '2026-06-15 00:00:00.000'
),
(
  'information-system-filing',
  '信息系统备案',
  '信息化服务',
  '信息系统备案是等级保护工作的重要环节，是开展信息系统等级测评、建设整改、监督检查等工作的重要基础。信息系统建设单位需按信息系统重要程度和破坏后影响程度确定安全保护等级，并完成校内备案等相关工作。',
  158,
  JSON_ARRAY('教职工'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.hlwxxfwsq.hlwxxfwsq',
  '数据管理处（信息化办公室）',
  '杨春节',
  '0551-65786139',
  '工作日正常办公时间',
  '《安徽农业大学预算项目库管理暂行办法》；《关于印发<安徽农业大学信息化项目建设管理规定（试行）>的通知》',
  JSON_ARRAY('《信息系统安全等级保护备案表》电子版', '系统备案相关信息', '必要的扫描件材料'),
  JSON_ARRAY('申报单位信息系统管理人员线上提交信息系统备案相关信息', '部门领导、信息化办公室领导审核通过', '信息化办公室反馈安全评估、域名配置等信息，开通内网访问', '申请人员填写《信息系统安全等级保护备案表》，扫描件在智慧安农/信息系统备案中提交，纸质件由单位留存备用', '信息化办公室审核通过备案表，完成信息系统校内备案'),
  '此前该入口被标记为暂不可用，因此当前先入库但保持 DISABLED，不会被 AI 办事返回。待确认入口恢复后再改为 ENABLED。',
  JSON_ARRAY('信息系统备案', '系统备案', '等级保护', '等保备案', '安全等级保护', '信息系统安全', '备案表', '杨春节'),
  JSON_ARRAY(
    JSON_OBJECT('question', '信息系统备案表在哪里下载', 'answer', '空白表格：https://i.ahau.edu.cn/_upload/ueditor/file/20231106/1699255347285046581.doc；示例样表：https://i.ahau.edu.cn/_upload/ueditor/file/20231106/1699255357319099787.doc')
  ),
  'DISABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.hlwxxfwsq.hlwxxfwsq',
  '2026-06-15 00:00:00.000'
),
(
  'campus-card-balance-donation',
  '一卡通余额爱心捐赠',
  '财务服务',
  '为凝聚安农学子的赤子情怀，回馈母校培育之恩，学校启用校园卡余额爱心捐赠功能。广大师生可自愿将卡内余额捐赠母校，每一笔善意捐款都将用于助学帮扶、成长赋能、办学能力提升等事业。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://ykt.ahau.edu.cn/zsanapp/web/AlumniDonation.aspx#',
  '财务处',
  '陈老师',
  '0551-65786419',
  '任何时间',
  '-',
  JSON_ARRAY('校园卡账户', '一卡通余额'),
  JSON_ARRAY('进入一卡通余额爱心捐赠页面', '确认本人校园卡余额和捐赠信息', '按页面提示自愿完成捐赠'),
  '捐赠为自愿行为，请在确认余额和捐赠意愿后操作。',
  JSON_ARRAY('一卡通余额', '校园卡余额', '爱心捐赠', '余额捐赠', '财务处', '校园卡'),
  JSON_ARRAY(),
  'ENABLED',
  'https://ykt.ahau.edu.cn/zsanapp/web/AlumniDonation.aspx#',
  '2026-06-15 00:00:00.000'
),
(
  'electronic-seal-info-maintenance',
  '电子公章信息维护',
  '信息化服务',
  '本服务适用于各单位电子公章管理员或负责领导发生岗位调整后，对电子公章管理信息进行变更报备，并实现向校园密码服务平台自动同步电子公章管理数据。',
  3,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.dzgzxxwh.dzgzxxwh',
  '数据管理处（信息化办公室）',
  '刘老师',
  '0551-65786196',
  '任何时间',
  '关于印发《安徽农业大学电子印章管理办法（试行）》的通知（校办发[2025]4号）',
  JSON_ARRAY('电子公章管理信息', '变更后的管理员或负责领导信息'),
  JSON_ARRAY('申请人选择本单位已经启用服务的电子公章', '系统自动加载原管理信息', '选择变更管理员或负责领导后提交', '由该电子公章负责领导审核', '数据自动同步至校园密码服务平台电子公章管理数据'),
  '适用于电子公章管理员或负责领导岗位调整后的信息维护场景。',
  JSON_ARRAY('电子公章', '电子印章', '公章信息维护', '电子公章管理员', '校园密码服务平台', '刘老师'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.dzgzxxwh.dzgzxxwh',
  '2026-06-15 00:00:00.000'
),
(
  'genuine-antivirus-software',
  '正版杀毒软件',
  '信息化服务',
  '为提升学校网络安全整体防护水平，增强用户上网终端安全防护能力，学校部署天融信“终端威胁防御系统”软件，请各学院、各单位组织师生安装使用，确保覆盖所有接入校园网的笔记本、台式机、物理服务器及虚拟服务器等终端。',
  NULL,
  JSON_ARRAY('本科生', '研究生', '教职工'),
  'https://xxb.ahau.edu.cn/info/1171/4621.htm',
  '数据管理处（信息化办公室）',
  '康老师',
  '0551-65786196',
  '任何时间',
  '关于面向全校师生提供正版软件服务的通知：https://www.ahau.edu.cn/info/2351/127681.htm',
  JSON_ARRAY('需要安装防病毒软件的终端设备'),
  JSON_ARRAY('笔记本、台式机、物理服务器及虚拟服务器等终端必须安装防病毒软件', '用户可自行选择下载安装天融信威胁终端防御系统', '也可根据需要下载火绒安全软件：https://www.huorong.cn/person5.html'),
  '前期已安装的服务器无需再次安装。具体下载和安装要求以信息化办公室通知为准。',
  JSON_ARRAY('正版杀毒软件', '杀毒软件', '防病毒', '天融信', '终端威胁防御', '火绒', '网络安全'),
  JSON_ARRAY(),
  'ENABLED',
  'https://xxb.ahau.edu.cn/info/1171/4621.htm',
  '2026-06-15 00:00:00.000'
),
(
  'graduate-off-campus-residence-withdrawal',
  '研究生走读退宿办理',
  '研究生服务',
  '本服务适用于研究生因各种原因需要办理走读申请及各单位线上审核。当前研工部会统一导出名单提交给总务部、财务处，开展后续宿舍管理及退费工作。',
  NULL,
  JSON_ARRAY('研究生'),
  'https://yjsxt.ahau.edu.cn/',
  '党委研究生工作部、研究生院',
  '研究生院、各学院研究生导师',
  '研究生院、各学院研究生导师联系电话',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('走读申请信息', '必要证明材料'),
  JSON_ARRAY('研究生提交走读申请', '提交信息并上传必要材料', '导师审核', '学院审核', '研工部审核', '研工部统一导出名单提交给总务部、财务处', '总务部学生宿舍管理中心线上办理宿舍调整，财务处审核后线上办理退费（功能正在开发中）'),
  '宿舍调整和退费后续功能正在开发中，具体办理结果以研究生院和相关部门通知为准。',
  JSON_ARRAY('研究生走读', '退宿', '走读退宿', '研究生宿舍', '宿舍退费', '导师审核', '研工部'),
  JSON_ARRAY(),
  'ENABLED',
  'https://yjsxt.ahau.edu.cn/',
  '2026-06-15 00:00:00.000'
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `handler_count` = VALUES(`handler_count`),
  `target_roles` = VALUES(`target_roles`),
  `entry_url` = VALUES(`entry_url`),
  `department` = VALUES(`department`),
  `contact_person` = VALUES(`contact_person`),
  `contact_phone` = VALUES(`contact_phone`),
  `service_time` = VALUES(`service_time`),
  `basis` = VALUES(`basis`),
  `materials` = VALUES(`materials`),
  `process_steps` = VALUES(`process_steps`),
  `notice` = VALUES(`notice`),
  `keywords` = VALUES(`keywords`),
  `faq` = VALUES(`faq`),
  `status` = VALUES(`status`),
  `source_url` = VALUES(`source_url`),
  `last_verified_at` = VALUES(`last_verified_at`);

INSERT INTO `service_item_assets` (
  `id`,
  `service_item_id`,
  `asset_type`,
  `title`,
  `url`,
  `alt_text`,
  `sort_order`
) VALUES
(
  'fixed-ip-address-application-flow',
  'fixed-ip-address-application',
  'image',
  '固定IP地址申请流程',
  '/service-assets/fixed-ip-address-application-flow.png',
  '固定IP地址申请流程图',
  1
),
(
  'digital-agriculture-password-account-activation',
  'digital-agriculture-password-service',
  'image',
  '账号激活入口',
  '/service-assets/digital-agriculture-password-account-activation.png',
  '数智安农登录页账号激活入口截图',
  1
),
(
  'digital-agriculture-password-forgot',
  'digital-agriculture-password-service',
  'image',
  '忘记密码入口',
  '/service-assets/digital-agriculture-password-forgot.png',
  '数智安农登录页忘记密码入口截图',
  2
),
(
  'digital-agriculture-password-appeal-entry',
  'digital-agriculture-password-service',
  'image',
  '密码申诉入口',
  '/service-assets/digital-agriculture-password-appeal-entry.png',
  '数智安农登录页密码申诉入口截图',
  3
),
(
  'digital-agriculture-password-appeal-type',
  'digital-agriculture-password-service',
  'image',
  '密码申诉类型选择',
  '/service-assets/digital-agriculture-password-appeal-type.png',
  '密码申诉类型选择页面截图',
  4
),
(
  'information-system-filing-flow',
  'information-system-filing',
  'image',
  '信息系统备案流程',
  '/service-assets/information-system-filing-flow.png',
  '信息系统备案流程图',
  1
)
ON DUPLICATE KEY UPDATE
  `service_item_id` = VALUES(`service_item_id`),
  `asset_type` = VALUES(`asset_type`),
  `title` = VALUES(`title`),
  `url` = VALUES(`url`),
  `alt_text` = VALUES(`alt_text`),
  `sort_order` = VALUES(`sort_order`);
