USE `aibs`;

INSERT INTO `service_items` (
  `id`,
  `title`,
  `category`,
  `description`,
  `handler_count`,
  `target_roles`,
  `entry_url`,
  `department`,
  `contact_person`,
  `contact_phone`,
  `service_time`,
  `basis`,
  `materials`,
  `process_steps`,
  `notice`,
  `keywords`,
  `faq`,
  `status`,
  `source_url`,
  `last_verified_at`
) VALUES
(
  'fixed-vehicle-campus-entry-application',
  '固定车辆入校申请',
  '安保服务',
  '为教职工办理固定车辆入校申请，申请人按车辆类型准备对应材料后，到保卫处办事大厅办理。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://e.ahau.edu.cn/win/zhmz.htm',
  '保卫处',
  '保卫处办事大厅工作人员',
  '0551-65786766',
  '工作日正常办公时间',
  'https://bwc.ahau.edu.cn/info/1056/4038.htm',
  JSON_ARRAY('各类车辆出入校园申请表', '按申请表要求准备的车辆及人员材料'),
  JSON_ARRAY('访问保卫处官方网站下载中心', '下载各类车辆出入校园申请表', '选择对应申请表并填写表格', '准备相关材料', '携带材料到保卫处办事大厅办理', '应缴费车辆审核通过并缴费成功后办理，无需缴费车辆审核通过后直接办理'),
  '请按车辆类型选择对应申请表。应缴费车辆需完成缴费后办理。',
  JSON_ARRAY('固定车辆入校', '固定车辆申请', '车辆入校', '车辆进校', '出入校园申请表', '保卫处', '车辆门禁'),
  JSON_ARRAY(),
  'ENABLED',
  'https://e.ahau.edu.cn/win/zhmz.htm',
  '2026-06-15 00:00:00.000'
),
(
  'retired-newspaper-subscription-statistics-application',
  '离退休报刊定投统计申请',
  '离退休服务',
  '离退休人员报刊定投统计申请服务。单职工每人可以申请征订 1 份《老年报》，双职工可以申请征订 1 份《老年报》和 1 份《开心老年》杂志。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://wk.ahau.edu.cn/default/coreplus/ltxbkdgtjsq/form/indexPage.jsp',
  '离退休工作处、离退休工作处党总支',
  '高老师',
  '0551-65786928',
  '11月底',
  '-',
  JSON_ARRAY('报刊征订申请信息', '离退休人员相关信息'),
  JSON_ARRAY('离退休本人登录智慧安农“网上办事大厅”为本人申请征订', '或由本校在职人员登录智慧安农“网上办事大厅”为离退休人员代申请征订', '按页面要求填写并提交申请'),
  '单职工每人可申请征订 1 份《老年报》；双职工可申请征订 1 份《老年报》和 1 份《开心老年》杂志。',
  JSON_ARRAY('离退休报刊', '报刊定投', '老年报', '开心老年', '离退休工作处', '报刊征订'),
  JSON_ARRAY(),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/coreplus/ltxbkdgtjsq/form/indexPage.jsp',
  '2026-06-15 00:00:00.000'
),
(
  'official-vehicle-reservation',
  '公务车预约',
  '安保服务',
  '公务车辆来校访问预约入口。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://xssq.ahau.edu.cn/security/h5/#/pages/login/login1',
  '保卫处',
  '-',
  '-',
  '-',
  '-',
  JSON_ARRAY('公务车预约相关信息'),
  JSON_ARRAY('进入公务车预约入口', '按页面提示登录', '填写公务车预约信息并提交', '等待审核结果'),
  '具体预约字段、审核规则和通行规则以系统页面展示为准。',
  JSON_ARRAY('公务车预约', '公务车辆', '车辆预约', '来访车辆', '车辆进校', '保卫处'),
  JSON_ARRAY(),
  'ENABLED',
  'https://xssq.ahau.edu.cn/security/h5/#/pages/login/login1',
  '2026-06-15 00:00:00.000'
),
(
  'graduate-student-status-change',
  '研究生学籍异动',
  '研究生服务',
  '适用于研究生线上申请各类学籍异动业务，包括新生保留入学资格、恢复入学资格、放弃入学资格，以及退学、休学、保留学籍、复学、降层次、换导师、转专业、修改学籍信息等及相应审批流程。',
  NULL,
  JSON_ARRAY('研究生'),
  'https://yjsxt.ahau.edu.cn/dashboard/workplace?dm=xj_xjyd_ydsq&mode=2&role=1',
  '党委研究生工作部、研究生院',
  '李老师',
  '0551-65785007',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('按异动类型要求提交的申请信息和证明材料'),
  JSON_ARRAY('登录研究生系统', '进入学籍异动申请入口', '选择异动类型', '填写申请信息并上传所需材料', '提交后等待相应审批流程办理'),
  '不同学籍异动类型的材料要求和审批流程可能不同，请以研究生系统页面提示为准。',
  JSON_ARRAY('研究生学籍异动', '学籍异动', '研究生休学', '研究生复学', '退学', '保留学籍', '换导师', '研究生转专业', '修改学籍信息', '研究生院'),
  JSON_ARRAY(),
  'ENABLED',
  'https://yjsxt.ahau.edu.cn/dashboard/workplace?dm=xj_xjyd_ydsq&mode=2&role=1',
  '2026-06-15 00:00:00.000'
),
(
  'public-classroom-reservation-application',
  '公共教室预约申请',
  '教务管理',
  '本校教师补课或开展其他教学活动需要使用公共教室的，须提前预约申请。本科学生开展主题班会使用公共教室的，须由班主任办理；团委、学生处、院系等组织学生活动使用公共教室的，须由相关负责教师办理。',
  NULL,
  JSON_ARRAY('教职工'),
  'http://newjwxt.ahau.edu.cn/sso/Sudylogin',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '房老师 张老师',
  '0551-65786861',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('教室使用申请信息', '申请人电话', '借用原因', '已审批的场地预约申请单'),
  JSON_ARRAY('教师登录本人教务系统', '进入“我的应用-场地预约申请”页面', '根据教室使用需求选择学期、校区、楼号、场地类别、座位数、周次、星期、节次等条件并查询', '选择教室并填写申请人电话和借用原因后提交', '教务科在一天之内审批', '审批通过后打印场地预约申请单并按要求审核盖章和留存'),
  '公共教室使用须提前预约。教师或受委托学生需持已审批的场地预约申请单，按流程交教学楼物业楼管和教务科留存备案。',
  JSON_ARRAY('公共教室预约', '教室预约', '借教室', '场地预约', '教务系统', '补课教室', '主题班会教室', '教学活动'),
  JSON_ARRAY(),
  'ENABLED',
  'http://newjwxt.ahau.edu.cn/sso/Sudylogin',
  '2026-06-15 00:00:00.000'
),
(
  'informatization-project-pool-declaration',
  '信息化项目入库申报',
  '信息化服务',
  '信息化项目库是学校项目库建设的组成部分，是学校编制年度预算和三年滚动预算的重要依据，也是年内追加项目预算的依据。项目建设单位根据事业发展提出信息化项目立项依据、建设内容、实施方案、绩效目标、预算及依据，并对申请立项项目进行初步论证。',
  51,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xxhxmrksb.xxhxmrksb',
  '数据管理处（信息化办公室）',
  '杨春节',
  '0551-65786139',
  '工作日正常办公时间',
  '《安徽农业大学预算项目库管理暂行办法》',
  JSON_ARRAY('安徽农业大学信息化项目立项申请表'),
  JSON_ARRAY('申报单位阅读预算项目库管理办法及相关通知要求', '填写《安徽农业大学信息化项目立项申请表》', '申请建设单位意见、申请建设单位分管领导意见须填写', '扫描件在“智慧安农/信息化项目入库申报”中提交，纸质件由单位留存备用', '可行性、必要性论证通过后，经学校会议研究纳入学校预算项目库管理'),
  '学校编制预算时，根据财力优先选定入库项目。纸质件由单位留存备用。',
  JSON_ARRAY('信息化项目入库', '项目入库', '信息化项目', '项目库', '预算项目库', '立项申请表', '数据管理处', '信息化办公室'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xxhxmrksb.xxhxmrksb',
  '2026-06-15 00:00:00.000'
),
(
  'campus-course-opening-query',
  '全校开课查询',
  '教务管理',
  '师生可通过综合服务-全校开课查询进行课程信息筛选并查询。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://bkjw.ahau.edu.cn/home/#/home',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '李老师',
  '0551-65786169',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('新本科教务系统账号'),
  JSON_ARRAY('进入本科教务系统', '打开综合服务', '选择全校开课查询', '按课程信息筛选条件查询'),
  '课程数据以教务系统展示为准。',
  JSON_ARRAY('全校开课查询', '开课查询', '课程查询', '课程信息', '综合服务', '本科教务', '教务系统'),
  JSON_ARRAY(),
  'ENABLED',
  'https://bkjw.ahau.edu.cn/home/#/home',
  '2026-06-15 00:00:00.000'
),
(
  'campus-network-domain-port-service',
  '校园网域名端口服务',
  '信息化服务',
  '各单位根据工作需要申请、修改、注销域名和网络端口。面向互联网的访问端口严格控制，非必须不开通。',
  5,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xywymdkfw.ymdkfwsq',
  '数据管理处（信息化办公室）',
  '刘锴',
  '0551-65786196',
  '工作日正常办公时间',
  '《中华人民共和国网络安全法》；《网络安全等级保护2.0标准》；《互联网用户账号信息管理规定》',
  JSON_ARRAY('域名或端口服务申请信息', '服务器所在单位信息', '网络安全承诺相关信息'),
  JSON_ARRAY('申请人在“智慧安农/校园网域名、端口服务”填写申请信息', '服务器所在单位审批', '信息化办公室审批', '审批通过后信息化办公室开通服务并通知申请人'),
  '在虚拟服务器申请、服务器托管服务中已配置域名和端口的，不需要通过此流程再次申请；已申请域名和开放端口需要变更或者注销的，可通过此事项办理。申请单位须遵守网络安全法律法规和学校相关规定。',
  JSON_ARRAY('校园网域名端口服务', '域名申请', '端口申请', '端口开放', '域名修改', '端口注销', '网络端口', 'DNS', 'ahau.edu.cn', '数据管理处'),
  JSON_ARRAY('域名用于标识网络主机，学校提供 ahau.edu.cn 下的子域名解析服务。', '端口是主机使用 TCP/UDP 协议提供服务时监听的端口号，端口号介于 0-65535。'),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xywymdkfw.ymdkfwsq',
  '2026-06-15 00:00:00.000'
),
(
  'informatization-demand-feedback',
  '信息化建设需求意见反馈',
  '信息化服务',
  '为充分发挥各单位业务优势和师生集体智慧，共同推进智慧校园建设和“网上办事”服务模式逐步形成，高质量服务师生信息化需求，面向全校各单位、全体师生常态化开展信息化需求意见调研。',
  12,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xxhbgsxxhdy.xxhbgsxxhdy',
  '数据管理处（信息化办公室）',
  '杨老师',
  '0551-65786196',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('信息化建设需求、意见建议或网上办事需求说明'),
  JSON_ARRAY('使用“安心办-信息化建设需求意见反馈”提出意见建议、网上办事需求或信息系统建设需求', '数据管理处（信息化办公室）汇总、梳理相关需求', '向相关单位反馈，共同推动、落实师生建议事项'),
  '该事项用于收集信息化建设相关意见、建议和需求，后续落实情况以相关单位反馈为准。',
  JSON_ARRAY('信息化建设需求', '意见反馈', '信息化意见', '网上办事需求', '信息系统建设需求', '智慧校园建议', '数据管理处'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xxhbgsxxhdy.xxhbgsxxhdy',
  '2026-06-15 00:00:00.000'
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `handler_count` = VALUES(`handler_count`),
  `target_roles` = VALUES(`target_roles`),
  `entry_url` = VALUES(`entry_url`),
  `department` = VALUES(`department`),
  `contact_person` = VALUES(`contact_person`),
  `contact_phone` = VALUES(`contact_phone`),
  `service_time` = VALUES(`service_time`),
  `basis` = VALUES(`basis`),
  `materials` = VALUES(`materials`),
  `process_steps` = VALUES(`process_steps`),
  `notice` = VALUES(`notice`),
  `keywords` = VALUES(`keywords`),
  `faq` = VALUES(`faq`),
  `status` = VALUES(`status`),
  `source_url` = VALUES(`source_url`),
  `last_verified_at` = VALUES(`last_verified_at`);

INSERT INTO `service_item_assets` (
  `id`,
  `service_item_id`,
  `asset_type`,
  `title`,
  `url`,
  `alt_text`,
  `sort_order`
) VALUES
(
  'fixed-vehicle-campus-entry-application-form-page',
  'fixed-vehicle-campus-entry-application',
  'link',
  '各类车辆出入校园申请表下载页',
  'https://bwc.ahau.edu.cn/info/1067/2040.htm',
  '保卫处各类车辆出入校园申请表下载页',
  1
),
(
  'public-classroom-reservation-flow',
  'public-classroom-reservation-application',
  'image',
  '公共教室预约申请流程',
  '/service-assets/public-classroom-reservation-flow.png',
  '公共教室预约申请流程图',
  1
),
(
  'informatization-project-application-form',
  'informatization-project-pool-declaration',
  'link',
  '安徽农业大学信息化项目立项申请表',
  'https://i.ahau.edu.cn/sopplus/_upload/service/file/1779421766709020481.docx',
  '安徽农业大学信息化项目立项申请表 DOCX',
  1
),
(
  'informatization-project-pool-flow',
  'informatization-project-pool-declaration',
  'image',
  '信息化项目入库申报流程',
  '/service-assets/informatization-project-pool-flow.png',
  '信息化项目入库申报流程图',
  2
),
(
  'campus-network-domain-port-flow',
  'campus-network-domain-port-service',
  'image',
  '校园网域名端口服务流程',
  '/service-assets/campus-network-domain-port-flow.png',
  '校园网域名端口服务流程图',
  1
),
(
  'informatization-demand-feedback-flow',
  'informatization-demand-feedback',
  'image',
  '信息化建设需求意见反馈流程',
  '/service-assets/informatization-demand-feedback-flow.png',
  '信息化建设需求意见反馈流程图',
  1
)
ON DUPLICATE KEY UPDATE
  `service_item_id` = VALUES(`service_item_id`),
  `asset_type` = VALUES(`asset_type`),
  `title` = VALUES(`title`),
  `url` = VALUES(`url`),
  `alt_text` = VALUES(`alt_text`),
  `sort_order` = VALUES(`sort_order`);
