USE `aibs`;

INSERT INTO `service_items` (
  `id`,
  `title`,
  `category`,
  `description`,
  `handler_count`,
  `target_roles`,
  `entry_url`,
  `department`,
  `contact_person`,
  `contact_phone`,
  `service_time`,
  `basis`,
  `materials`,
  `process_steps`,
  `notice`,
  `keywords`,
  `faq`,
  `status`,
  `source_url`,
  `last_verified_at`
) VALUES
(
  'xinyuan-fourth-floor-auditorium-reservation',
  '欣苑四楼小礼堂使用预约',
  '场地预约',
  '为全校各单位使用安徽农业大学学生活动中心多功能厅提供预约服务，由申请使用单位的教职工发起预约申请，常用于会议、报告、文艺演出、招聘会等。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.tsgtdhds.tsgtdhds&type=2',
  '团委',
  '夏老师',
  '0551-65781884',
  '当日',
  '-',
  JSON_ARRAY('安徽农业大学学生活动中心多功能厅使用申请表'),
  JSON_ARRAY('填写使用申请表', '提交申请人基本信息、活动时间、活动类别、活动规模等信息', '举办活动单位负责人签字', '上传电子版材料，建议上传电子签章版 PDF', '提交预约申请并等待受理'),
  '活动需提前一周进行线上系统申请。使用期间由使用单位负责现场布置、现场秩序、会务和后勤等工作；活动内容须与申请表一致；遇学校重大活动需服从校团委协调。',
  JSON_ARRAY('欣苑四楼小礼堂', '小礼堂', '多功能厅', '学生活动中心', '场地预约', '会议预约', '文艺演出', '招聘会', '团委'),
  JSON_ARRAY('严禁携带动物、易燃易爆物、腐蚀性物品、管制刀具等危险品进入多功能厅。', '活动后使用单位需完成卫生清理并经工作人员检查达标后离开。', '活动文件原则上通过 QQ 向小礼堂官 Q 发送，不接受 U 盘传输。'),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.tsgtdhds.tsgtdhds&type=2',
  '2026-06-15 00:00:00.000'
),
(
  'website-construction-filing',
  '网站建设备案',
  '信息化服务',
  '各单位建设部门网站时须基于学校网站群管理系统建设。新建网站时需要先备案；学校定期的网站在用情况核查也将通过“网站建设备案”的方式实施，具体情况以学校通知为准。',
  91,
  JSON_ARRAY('教职工'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.wzjsbasq.wzjsbasq',
  '数据管理处（信息化办公室）',
  '刘世虎',
  '0551-65786139',
  '工作日正常办公时间',
  '关于印发《安徽农业大学网站建设与管理办法（暂行）》的通知',
  JSON_ARRAY('网站建设备案相关信息', '申请单位信息管理员提交的信息'),
  JSON_ARRAY('申请单位的信息管理员线上提交相关信息', '部门领导审核', '信息化办公室领导审核', '信息化办公室处理备案信息', '网站备案完成'),
  '备案完成后，申请单位将获得对应网站的管理权限。网站设计和维护应与学校门户网站总体风格保持一致；未备案或长期无更新不在用的网站，学校统计后可能统一关闭清理。',
  JSON_ARRAY('网站建设备案', '网站备案', '网站群', '部门网站', '网站建设', '网站核查', '数据管理处', '信息化办公室'),
  JSON_ARRAY('网站群学习网：http://www.vsbclub.com', '公开课：http://webber.ke.qq.com'),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.wzjsbasq.wzjsbasq',
  '2026-06-15 00:00:00.000'
),
(
  'undergraduate-student-card-reissue',
  '本科生补办学生证',
  '教务管理',
  '本科生学生证丢失可以通过“新本科教务”系统线上申请补办学生证。系统审核通过后，学生于每月 1-5 日（遇节假日顺延）携带一寸证件照至教务处学籍管理科（勤政楼 127 室）现场办领学生证。',
  NULL,
  JSON_ARRAY('本科生'),
  'https://bkjw.ahau.edu.cn/student/for-std/reissue-std-card-apply/index/43126',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '胡老师、赵老师',
  '0551-65786163',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('一寸证件照'),
  JSON_ARRAY('学生在新本科教务系统中提交补办申请', '辅导员审核', '教务处审核', '系统审核通过后，学生于每月 1-5 日携带一寸证件照至勤政楼 127 室现场办领学生证'),
  '每名学生只有一次线上申请机会。线下办理时间为每月 1-5 日，遇节假日顺延。',
  JSON_ARRAY('本科生补办学生证', '学生证补办', '补办学生证', '学生证丢失', '学生证', '新本科教务', '勤政楼127'),
  JSON_ARRAY(),
  'ENABLED',
  'https://bkjw.ahau.edu.cn/student/for-std/reissue-std-card-apply/index/43126',
  '2026-06-15 00:00:00.000'
),
(
  'lab-team-website',
  '实验室（团队）网站',
  '科研服务',
  '实验室（团队）网站为安徽农业大学国家级、省级、校级实验室及科研项目团队集中展示科研成果提供统一展示服务的平台。目前已经入驻 40 个不同级别、不同类型的实验室及科研项目团队。',
  NULL,
  JSON_ARRAY('访客', '教职工', '本科生', '研究生', '校友'),
  'https://lab.ahau.edu.cn/',
  '科技处',
  '侯老师',
  '0551-65786222',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY(),
  JSON_ARRAY('访问实验室（团队）网站', '浏览已入驻实验室及科研项目团队', '查看实验室负责人、团队人数、发布时间等展示信息'),
  '该事项主要用于展示查询，具体实验室团队信息以网站页面为准。',
  JSON_ARRAY('实验室网站', '团队网站', '科研平台', '实验室团队', '科技处', '实验室展示', '科研成果'),
  JSON_ARRAY('目前已入驻 40 个不同级别、不同类型的实验室及科研项目团队。'),
  'ENABLED',
  'https://lab.ahau.edu.cn/',
  '2026-06-15 00:00:00.000'
),
(
  'carsi-federated-authentication-resource-sharing',
  '教育网联邦认证与资源共享基础设施（CARSI）',
  '图书资源',
  '中国教育和科研计算机网联邦认证与资源共享基础设施（CARSI）为已建立校园网统一身份认证的高校和科研单位提供联邦认证和全球学术信息资源共享服务。无需 VPN，不受校园 IP 地址授权限制，可以在有互联网的任何地方使用校园网账号直接访问已授权资源。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://www.carsi.edu.cn/resourcenologin.html',
  '图书馆、档案馆',
  '龚老师',
  '0551-65786335',
  '任何时间',
  '-',
  JSON_ARRAY('校园统一身份认证账号'),
  JSON_ARRAY('访问 CARSI 门户 ds.carsi.edu.cn 或 CARSI 资源页面', '选择安徽农业大学或对应学校机构', '跳转到本校统一身份认证页面', '输入校园账号密码完成认证', '认证通过后访问所需数据库或资源'),
  'CARSI 可用于校外访问学校已授权的学术资源，不用 VPN、不用插件。可访问资源以学校实际购买授权和 CARSI 平台可用资源为准。',
  JSON_ARRAY('CARSI', '教育网联邦认证', '资源共享', '校外访问数据库', '不用VPN', '知网', '万方', 'Elsevier', 'ScienceDirect', '图书资源', '学术资源'),
  JSON_ARRAY('CARSI 可以解决校外访问图书电子资源的问题。', '可用资源包括知网、万方、维普、超星、Elsevier、Springer、IEEE、EBSCO、Emerald 等，具体以学校授权为准。'),
  'ENABLED',
  'https://www.carsi.edu.cn/resourcenologin.html',
  '2026-06-15 00:00:00.000'
),
(
  'unified-reservation-services',
  '统一预约一类事',
  '预约服务',
  '统一预约一类事为师生提供预约类服务入口。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://wk.ahau.edu.cn/default/coreplus/tsgtdhds/form/index.jsp',
  '-',
  '-',
  '-',
  '-',
  '-',
  JSON_ARRAY(),
  JSON_ARRAY('进入统一预约一类事入口', '按页面提示选择需要预约的事项', '填写预约信息并提交'),
  '具体可预约事项和办理要求以系统页面展示为准。',
  JSON_ARRAY('统一预约', '预约一类事', '预约服务', '场地预约', '统一预约一类事'),
  JSON_ARRAY(),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/coreplus/tsgtdhds/form/index.jsp',
  '2026-06-15 00:00:00.000'
),
(
  'liaison-information-filing-service',
  '联络员信息备案服务',
  '信息化服务',
  '面向教职工，提供各种联络员信息备案服务，为教职工增加联络员标签，更加精准地推送应用及办事服务。包括网站通讯员、实验室（团队）网站维护员、网络信息安全员、给据邮件单位管理员等。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.wlaqxxysq.wlaqxxysq',
  '数据管理处（信息化办公室）',
  '本单位领导、许陈',
  '各单位联系电话、0551-65786196',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('联络员备案相关信息'),
  JSON_ARRAY('教职工自行备案，或因岗位、工作职责变动为他人备案', '本单位领导审批', '数据自动推送给相应业务管理部门备案'),
  '不同联络员类型对应不同备案部门：网站通讯员向宣传部备案；实验室（团队）网站维护员、网络信息安全员向数据管理处备案；给据邮件单位管理员向总务部备案。',
  JSON_ARRAY('联络员信息备案', '联络员备案', '网站通讯员', '网站维护员', '网络信息安全员', '给据邮件单位管理员', '数据管理处'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.wlaqxxysq.wlaqxxysq',
  '2026-06-15 00:00:00.000'
),
(
  'library-reader-book-recommendation',
  '图书馆读者荐购图书申请',
  '图书馆服务',
  '为师生提供图书荐购入口，由图书馆相关工作人员具体受理、办理。',
  NULL,
  JSON_ARRAY('本科生', '研究生', '教职工'),
  'https://opac.ahau.edu.cn/asord/asord_redr.php',
  '图书馆、档案馆',
  '汪老师',
  '0551-65786351',
  '1-3个月',
  '-',
  JSON_ARRAY('题名', '责任者', 'ISBN', '推荐理由', '联系方式'),
  JSON_ARRAY('进入图书馆读者荐购入口', '荐购前先查重，确认图书馆未收藏该图书', '填写题名、责任者、出版社、出版年、语种、ISBN、推荐理由等信息', '提交荐购申请', '等待图书馆工作人员受理'),
  '荐购前请先查重，图书馆已有图书无需推荐；带 * 为必填项；请确保荐购信息准确。',
  JSON_ARRAY('图书荐购', '读者荐购', '荐购图书', '图书馆荐购', '推荐购买图书', '图书馆', 'OPAC'),
  JSON_ARRAY('荐购图书的内容需积极健康，符合国家法律法规、公共道德与公序良俗。', '图书馆已有馆藏复本、少儿读物、教辅资料、考试题库等出版物一般不予受理。'),
  'ENABLED',
  'https://opac.ahau.edu.cn/asord/asord_redr.php',
  '2026-06-15 00:00:00.000'
),
(
  'information-basic-resource-expansion-application',
  '信息基础资源扩容申请',
  '信息化服务',
  '信息基础资源（CPU/内存/存储）使用率长时间高位运行，导致系统运行响应速度变慢，影响业务系统正常运行时，可申请扩容。',
  11,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xxjczykrsq.xxjczykrlc',
  '数据管理处（信息化办公室）',
  '刘世虎',
  '0551-65786196',
  '工作日正常办公时间',
  '《安徽农业大学虚拟服务器管理办法（试行）》',
  JSON_ARRAY('CPU 扩容信息', '内存扩容信息', '存储扩容信息', '业务系统运行情况说明'),
  JSON_ARRAY('点击“信息基础资源扩容申请”并填写扩容信息', '数据管理处工作人员预审', '学院书记或部门领导审批同意', '数据管理处领导审批同意', '数据管理处工作人员受理并办理'),
  '请根据业务系统实际运行情况填写扩容需求，扩容内容包括 CPU、内存、存储等基础资源。',
  JSON_ARRAY('信息基础资源扩容', '资源扩容', 'CPU扩容', '内存扩容', '存储扩容', '虚拟服务器扩容', '数据管理处', '信息化办公室'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xxjczykrsq.xxjczykrlc',
  '2026-06-15 00:00:00.000'
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `handler_count` = VALUES(`handler_count`),
  `target_roles` = VALUES(`target_roles`),
  `entry_url` = VALUES(`entry_url`),
  `department` = VALUES(`department`),
  `contact_person` = VALUES(`contact_person`),
  `contact_phone` = VALUES(`contact_phone`),
  `service_time` = VALUES(`service_time`),
  `basis` = VALUES(`basis`),
  `materials` = VALUES(`materials`),
  `process_steps` = VALUES(`process_steps`),
  `notice` = VALUES(`notice`),
  `keywords` = VALUES(`keywords`),
  `faq` = VALUES(`faq`),
  `status` = VALUES(`status`),
  `source_url` = VALUES(`source_url`),
  `last_verified_at` = VALUES(`last_verified_at`);

INSERT INTO `service_item_assets` (
  `id`,
  `service_item_id`,
  `asset_type`,
  `title`,
  `url`,
  `alt_text`,
  `sort_order`
) VALUES
(
  'xinyuan-fourth-floor-auditorium-application-form',
  'xinyuan-fourth-floor-auditorium-reservation',
  'link',
  '安徽农业大学学生活动中心多功能厅使用申请表',
  'https://i.ahau.edu.cn/ywtbapi/rhmhUpload/serviceAttachments/533cf952e3a9ae940aa2c371bf774de7626240b414599276d6c207bffaa28435.docx',
  '安徽农业大学学生活动中心多功能厅使用申请表 DOCX',
  1
),
(
  'website-construction-filing-flow',
  'website-construction-filing',
  'image',
  '网站建设备案流程',
  '/service-assets/website-construction-filing-flow.png',
  '网站建设备案流程图',
  1
),
(
  'lab-team-website-example',
  'lab-team-website',
  'image',
  '实验室（团队）网站示例',
  '/service-assets/lab-team-website-example.png',
  '实验室团队网站展示示例',
  1
),
(
  'carsi-login-example',
  'carsi-federated-authentication-resource-sharing',
  'image',
  'CARSI 统一认证登录示例',
  '/service-assets/carsi-login-example.png',
  'CARSI 统一认证登录页面示例',
  1
),
(
  'carsi-resource-list-example',
  'carsi-federated-authentication-resource-sharing',
  'image',
  'CARSI 应用资源页面示例',
  '/service-assets/carsi-resource-list-example.png',
  'CARSI 应用资源列表页面示例',
  2
),
(
  'library-reader-book-recommendation-form',
  'library-reader-book-recommendation',
  'image',
  '图书馆读者荐购表单',
  '/service-assets/library-reader-book-recommendation-form.png',
  '图书馆读者荐购图书申请表单截图',
  1
),
(
  'information-basic-resource-expansion-flow',
  'information-basic-resource-expansion-application',
  'image',
  '信息基础资源扩容申请流程',
  '/service-assets/information-basic-resource-expansion-flow.png',
  '信息基础资源扩容申请流程图',
  1
)
ON DUPLICATE KEY UPDATE
  `service_item_id` = VALUES(`service_item_id`),
  `asset_type` = VALUES(`asset_type`),
  `title` = VALUES(`title`),
  `url` = VALUES(`url`),
  `alt_text` = VALUES(`alt_text`),
  `sort_order` = VALUES(`sort_order`);
