USE `aibs`;

INSERT INTO `service_items` (
  `id`,
  `title`,
  `category`,
  `description`,
  `handler_count`,
  `target_roles`,
  `target_grades`,
  `target_colleges`,
  `target_campuses`,
  `entry_url`,
  `department`,
  `contact_person`,
  `contact_phone`,
  `service_time`,
  `basis`,
  `materials`,
  `process_steps`,
  `notice`,
  `keywords`,
  `faq`,
  `status`,
  `source_url`,
  `last_verified_at`
) VALUES
(
  'leader-official-activity-application',
  '邀请校领导参加公务活动申请',
  '数据填报',
  '面向教职工提供邀请校领导参加公务活动的线上填报入口。申请人按页面要求填写公务活动信息并提交。',
  NULL,
  JSON_ARRAY('教职工'),
  NULL,
  NULL,
  NULL,
  'https://data1.ahau.edu.cn/TableX/menu_infoFill/infoFillList/infoFillFormPage?appId=1000205&appName=%E9%82%80%E8%AF%B7%E6%A0%A1%E9%A2%86%E5%AF%BC%E5%8F%82%E5%8A%A0%E5%85%AC%E5%8A%A1%E6%B4%BB%E5%8A%A8%E7%94%B3%E8%AF%B7&taskId=0c4bac03ef948bca5e73999492df4c5b&fillType=0&flag=1&currSelectApp=%5Bobject%20Object%5D&type=add',
  '-',
  '-',
  '-',
  '填报中',
  '-',
  JSON_ARRAY('公务活动相关信息'),
  JSON_ARRAY('进入一表通填报页面', '按页面要求填写邀请校领导参加公务活动申请信息', '核对信息无误后提交'),
  '该入口仅教职工可用，学生身份不返回该事项。',
  JSON_ARRAY('邀请校领导', '校领导公务活动', '公务活动申请', '邀请校领导参加公务活动申请', '一表通', '流程填报', '教职工'),
  JSON_ARRAY(),
  'ENABLED',
  'https://data1.ahau.edu.cn/TableX/menu_infoFill/infoFillList/infoFillFormPage?appId=1000205&appName=%E9%82%80%E8%AF%B7%E6%A0%A1%E9%A2%86%E5%AF%BC%E5%8F%82%E5%8A%A0%E5%85%AC%E5%8A%A1%E6%B4%BB%E5%8A%A8%E7%94%B3%E8%AF%B7&taskId=0c4bac03ef948bca5e73999492df4c5b&fillType=0&flag=1&currSelectApp=%5Bobject%20Object%5D&type=add',
  '2026-06-17 00:00:00.000'
),
(
  'tablex-source-form-collection',
  '一表通-源表收集',
  '数据填报',
  '面向教职工提供一表通源表收集填报入口，用于按要求提交源表相关信息。',
  NULL,
  JSON_ARRAY('教职工'),
  NULL,
  NULL,
  NULL,
  'https://data1.ahau.edu.cn/TableX/menu_infoFill/infoFillList/infoFillFormPage?appId=1000167&appName=%E4%B8%80%E8%A1%A8%E9%80%9A-%E6%BA%90%E8%A1%A8%E6%94%B6%E9%9B%86&taskId=026a03be659b8821e7661f36ce2a29cc&fillType=0&flag=1&currSelectApp=%5Bobject%20Object%5D&type=add',
  '-',
  '-',
  '-',
  '填报中',
  '-',
  JSON_ARRAY('源表相关信息'),
  JSON_ARRAY('进入一表通源表收集页面', '按页面要求填写源表收集信息', '核对信息无误后提交'),
  '该入口仅教职工可用，学生身份不返回该事项。',
  JSON_ARRAY('一表通', '源表收集', '一表通源表收集', '源表', '流程填报', '教职工'),
  JSON_ARRAY(),
  'ENABLED',
  'https://data1.ahau.edu.cn/TableX/menu_infoFill/infoFillList/infoFillFormPage?appId=1000167&appName=%E4%B8%80%E8%A1%A8%E9%80%9A-%E6%BA%90%E8%A1%A8%E6%94%B6%E9%9B%86&taskId=026a03be659b8821e7661f36ce2a29cc&fillType=0&flag=1&currSelectApp=%5Bobject%20Object%5D&type=add',
  '2026-06-17 00:00:00.000'
),
(
  'information-officer-registration',
  '信息员登记',
  '数据填报',
  '面向教职工提供信息员登记填报入口，用于按要求登记信息员相关信息。',
  NULL,
  JSON_ARRAY('教职工'),
  NULL,
  NULL,
  NULL,
  'https://data1.ahau.edu.cn/TableX/menu_infoFill/infoFillList/infoFillFormPage?appId=1000164&appName=%E4%BF%A1%E6%81%AF%E5%91%98%E7%99%BB%E8%AE%B0&taskId=cddc4bdd71ea05030a45001072bb2dd4&fillType=0&flag=1&currSelectApp=%5Bobject%20Object%5D&type=add',
  '-',
  '-',
  '-',
  '填报中',
  '-',
  JSON_ARRAY('信息员登记信息'),
  JSON_ARRAY('进入信息员登记页面', '按页面要求填写信息员登记信息', '核对信息无误后提交'),
  '该入口仅教职工可用，学生身份不返回该事项。',
  JSON_ARRAY('信息员', '信息员登记', '登记信息员', '流程填报', '一表通', '教职工'),
  JSON_ARRAY(),
  'ENABLED',
  'https://data1.ahau.edu.cn/TableX/menu_infoFill/infoFillList/infoFillFormPage?appId=1000164&appName=%E4%BF%A1%E6%81%AF%E5%91%98%E7%99%BB%E8%AE%B0&taskId=cddc4bdd71ea05030a45001072bb2dd4&fillType=0&flag=1&currSelectApp=%5Bobject%20Object%5D&type=add',
  '2026-06-17 00:00:00.000'
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `handler_count` = VALUES(`handler_count`),
  `target_roles` = VALUES(`target_roles`),
  `target_grades` = VALUES(`target_grades`),
  `target_colleges` = VALUES(`target_colleges`),
  `target_campuses` = VALUES(`target_campuses`),
  `entry_url` = VALUES(`entry_url`),
  `department` = VALUES(`department`),
  `contact_person` = VALUES(`contact_person`),
  `contact_phone` = VALUES(`contact_phone`),
  `service_time` = VALUES(`service_time`),
  `basis` = VALUES(`basis`),
  `materials` = VALUES(`materials`),
  `process_steps` = VALUES(`process_steps`),
  `notice` = VALUES(`notice`),
  `keywords` = VALUES(`keywords`),
  `faq` = VALUES(`faq`),
  `status` = VALUES(`status`),
  `source_url` = VALUES(`source_url`),
  `last_verified_at` = VALUES(`last_verified_at`),
  `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `service_item_assets` (
  `id`,
  `service_item_id`,
  `asset_type`,
  `title`,
  `url`,
  `alt_text`,
  `sort_order`
) VALUES
(
  'leader-official-activity-application-qrcode',
  'leader-official-activity-application',
  'image',
  '邀请校领导参加公务活动申请二维码',
  '/service-assets/leader-official-activity-application-qrcode.png',
  '邀请校领导参加公务活动申请扫码填报二维码',
  1
),
(
  'tablex-source-form-collection-qrcode',
  'tablex-source-form-collection',
  'image',
  '一表通-源表收集二维码',
  '/service-assets/tablex-source-form-collection-qrcode.png',
  '一表通-源表收集扫码填报二维码',
  1
),
(
  'information-officer-registration-qrcode',
  'information-officer-registration',
  'image',
  '信息员登记二维码',
  '/service-assets/information-officer-registration-qrcode.png',
  '信息员登记扫码填报二维码',
  1
)
ON DUPLICATE KEY UPDATE
  `service_item_id` = VALUES(`service_item_id`),
  `asset_type` = VALUES(`asset_type`),
  `title` = VALUES(`title`),
  `url` = VALUES(`url`),
  `alt_text` = VALUES(`alt_text`),
  `sort_order` = VALUES(`sort_order`);
