USE `aibs`;

INSERT INTO `service_items` (
  `id`,
  `title`,
  `category`,
  `description`,
  `handler_count`,
  `target_roles`,
  `entry_url`,
  `department`,
  `contact_person`,
  `contact_phone`,
  `service_time`,
  `basis`,
  `materials`,
  `process_steps`,
  `notice`,
  `keywords`,
  `faq`,
  `status`,
  `source_url`,
  `last_verified_at`
) VALUES
(
  'party-political-birthday-sms',
  '党员政治生日短信服务',
  '党建服务',
  '党委组织部面向全校师生党员提供政治生日短信提醒服务，在党员转正日期对应的重要日子向党员致以问候，提醒牢记党员身份，弘扬和践行“三牛”精神。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://my.ahau.edu.cn/default/work/process/processManager/managePageIndex.jsp?businessCode=t_ahau_dydxfwgl',
  '党委组织部、党校、机关党委',
  '马老师',
  '0551-65786112',
  '视具体情况而定',
  '-',
  JSON_ARRAY('无需党员个人办理'),
  JSON_ARRAY('党委组织部每学期更新两次新党员数据', '系统按照党员转正日期，每年自动发送一条政治生日短信'),
  '该服务无需党员个人办理，由党委组织部统一维护党员数据并发送短信。',
  JSON_ARRAY('党员政治生日', '政治生日', '短信服务', '党员短信', '党委组织部', '党员转正日期'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/work/process/processManager/managePageIndex.jsp?businessCode=t_ahau_dydxfwgl',
  '2026-06-14 00:00:00.000'
),
(
  'teacher-ethics-monthly-report',
  '师德师风月报提交',
  '人事服务',
  '师德师风月报提交服务。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.sdsfybtj.sdsfybtj',
  '党委教师工作部、人事处、人才办',
  '-',
  '-',
  '-',
  '-',
  JSON_ARRAY('按系统页面要求填写'),
  JSON_ARRAY('进入师德师风月报提交流程', '按页面要求填写并提交'),
  '具体填报要求以系统页面和相关部门通知为准。',
  JSON_ARRAY('师德师风', '月报', '师德师风月报', '月报提交', '人事处'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.sdsfybtj.sdsfybtj',
  '2026-06-14 00:00:00.000'
),
(
  'teacher-ethics-weekly-report',
  '师德师风周报提交',
  '人事服务',
  '师德师风周报提交服务。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.sdsfzbtj.sdsfzbtj',
  '党委教师工作部、人事处、人才办',
  '-',
  '-',
  '-',
  '-',
  JSON_ARRAY('按系统页面要求填写'),
  JSON_ARRAY('进入师德师风周报提交流程', '按页面要求填写并提交'),
  '具体填报要求以系统页面和相关部门通知为准。',
  JSON_ARRAY('师德师风', '周报', '师德师风周报', '周报提交', '人事处'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.sdsfzbtj.sdsfzbtj',
  '2026-06-14 00:00:00.000'
),
(
  'party-branch-outside-activity-application',
  '支部外出活动申请',
  '党建服务',
  '基层党组织开展“三会一课”、主题党日活动、党员和入党积极分子教育培训、学习调研等党建活动前，需要在系统内填报支部外出活动申请，报校党委组织部审核同意后方可外出。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.zzdywckzdjhdsq.zzdywckzdjhdsq',
  '党委组织部、党校、机关党委',
  '何老师',
  '0551-65780583',
  '工作日正常办公时间',
  '关于印发《安徽农业大学基层党组织党建活动经费管理使用暂行办法》的通知.pdf',
  JSON_ARRAY('按表单要求填写活动信息和相关材料'),
  JSON_ARRAY('申请人填报', '二级党组织书记审批', '党委组织部审批'),
  '外出活动应在开展前完成申请和审批。',
  JSON_ARRAY('支部外出', '党建活动', '主题党日', '三会一课', '党组织活动经费', '党委组织部'),
  JSON_ARRAY(
    '报账经费一般选择葛红（1992025）名下的“党组织活动专项经费”。',
    '报账材料包括外出活动申请审批页截图、汇总单、车票、用餐票据和其他发票等。',
    '审批页截图可在数智安农“我的已办”中打开申请条目后整页截图。'
  ),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.zzdywckzdjhdsq.zzdywckzdjhdsq',
  '2026-06-14 00:00:00.000'
),
(
  'graduate-thesis-submission',
  '研究生学位论文提交',
  '图书档案',
  '研究生和研究生校友通过论文提交系统办理学位论文提交。',
  NULL,
  JSON_ARRAY('研究生', '研究生校友'),
  'https://tsglw.ahau.edu.cn/home?name=',
  '图书馆、档案馆',
  '林老师',
  '0551-65786352',
  '-',
  '-',
  JSON_ARRAY('按论文提交系统要求填写并上传材料'),
  JSON_ARRAY('登录论文提交系统', '提交学位论文', '查看论文状态', '根据审核意见修改或系统打印回执单'),
  '具体流程以论文提交系统和图书馆、档案馆要求为准。',
  JSON_ARRAY('研究生论文', '学位论文', '论文提交', '毕业论文', '论文状态', '论文回执'),
  JSON_ARRAY(),
  'ENABLED',
  'https://tsglw.ahau.edu.cn/home?name=',
  '2026-06-14 00:00:00.000'
),
(
  'undergraduate-student-status-change',
  '本科学籍异动',
  '教务服务',
  '本科学籍异动是指本科生因休学、复学、保留学籍、退学等原因需要变更学籍状态时办理的过程。该事项通过教务系统完成申请、审核、结果反馈全流程。',
  NULL,
  JSON_ARRAY('本科生'),
  'https://bkjw.ahau.edu.cn/student/for-std/std-alteration-apply/apply/index/43126?index=0',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '赵老师',
  '0551-65786163',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('对应异动类型所需专项材料，如医院诊断证明、入伍通知书、创业证明材料等，以弹窗通知为准'),
  JSON_ARRAY(
    '学生登录数智安农，进入“新教务系统-学生全部服务-学籍-学籍异动申请”模块',
    '选择对应异动类型，填写申请信息并上传附件证明材料后提交',
    '辅导员、学院等按要求核对申请信息真实性并审核',
    '已提交的异动申请可在“学籍异动申请管理”查看并下载申请证明材料，教务系统同步更新学籍状态'
  ),
  '学生在下一级审核人审核前可撤回异动；如辅导员已审核完毕，则不可再撤回。',
  JSON_ARRAY('学籍异动', '休学', '复学', '保留学籍', '退学', '本科学籍', '教务系统'),
  JSON_ARRAY(),
  'ENABLED',
  'https://bkjw.ahau.edu.cn/student/for-std/std-alteration-apply/apply/index/43126?index=0',
  '2026-06-14 00:00:00.000'
),
(
  'questionnaire-voting',
  '问卷投票',
  '信息化服务',
  '为教职工免费提供设计、分发和分析问卷调查、投票、评比的工具，结合数智安农统一身份认证信息，可用于信息在线搜集登记、后台统计管理数据等。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://wenjuan.ahau.edu.cn/casLogin/0',
  '数据管理处（信息化办公室）',
  '章老师',
  '0551-65786196',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('无'),
  JSON_ARRAY('搜索“问卷投票”', '进行问卷或投票的新建、编辑、发布、分析等操作', '具体操作可参考安农大问卷调查用户手册'),
  '原始链接中的 ticket 为一次性登录票据，固定入口已去掉 ticket 参数。',
  JSON_ARRAY('问卷', '投票', '评比', '问卷调查', '调查表', '数据收集', '在线投票'),
  JSON_ARRAY(
    '问卷调查、投票及评比系统使用说明视频教程见附件链接。',
    '问卷投票评比工具使用说明图文教程见附件链接。',
    '安农大问卷调查用户手册 PDF 见附件链接。'
  ),
  'ENABLED',
  'https://wenjuan.ahau.edu.cn/casLogin/0',
  '2026-06-14 00:00:00.000'
),
(
  'non-motor-vehicle-plate-application',
  '非机动车车牌申请',
  '安保门禁',
  '面向师生开展校园非机动车车牌申请及补办服务。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://xssq.ahau.edu.cn/security/h5/#/pkgNoCar/noCarApply/noCarApply',
  '保卫处',
  '李老师',
  '0551-65786766',
  '工作日正常办公时间',
  '安徽农业大学电动自行车校园车牌办理工作实施方案',
  JSON_ARRAY('社会车牌等信息', '对应图片材料', '补办时按要求上传补办材料'),
  JSON_ARRAY(
    '用户可登录数智安农-智慧门禁系统-通用，或安农卫士微信公众号底部网上办事-业务办理，或安心办搜索非机动车车牌申请',
    '选择非机动车牌申请，根据人员类别选择对应申请项，填写社会车牌等信息并上传材料',
    '提交后等待管理员审核',
    '审核通过后等待下发，收到下发通知短信后去北二门安装非机动车牌',
    '补办可在智慧门禁系统或安农卫士微信公众号的我的非机动车申请中点击补办并提交材料'
  ),
  '学生特殊情况申办或遗失损坏补办需按对应表单材料要求办理。',
  JSON_ARRAY('非机动车', '车牌', '电动车车牌', '校园车牌', '车牌补办', '安农卫士', '智慧门禁'),
  JSON_ARRAY(),
  'ENABLED',
  'https://xssq.ahau.edu.cn/security/h5/#/pkgNoCar/noCarApply/noCarApply',
  '2026-06-14 00:00:00.000'
),
(
  'fixed-pedestrian-access-application',
  '固定人行门禁申请',
  '安保门禁',
  '在校家属、产权户、外服单位等人员需长期进校访问时，可通过该流程发起固定人行门禁申请，经审核通过后可拥有长期进校权限，通行时限以填写时长为准。',
  NULL,
  JSON_ARRAY('教职工', '访客(社会人员)'),
  'https://e.ahau.edu.cn/win/zhmz.htm',
  '保卫处',
  '各单位审核负责人',
  '0551-65786766',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('通行人信息', '按系统要求填写的申请材料'),
  JSON_ARRAY(
    '智慧安农中搜索智慧门禁系统，教职工选择教职工，其他人员选择通用',
    '点击人行门禁管理，申请办卡，选择对应申请项并填写通行人等信息',
    '提交后在人行门禁管理-申请记录中查看审核信息',
    '审核通过后收到短信通知，12小时后可刷身份证通行',
    '也可关注安农卫士微信公众号，通过办事大厅-各类车辆门禁进入固定人行门禁申请'
  ),
  '具体通行权限和有效时长以审核结果和系统记录为准。',
  JSON_ARRAY('固定人行门禁', '人行门禁', '长期进校', '家属进校', '外服单位', '智慧门禁', '安农卫士'),
  JSON_ARRAY(),
  'ENABLED',
  'https://e.ahau.edu.cn/win/zhmz.htm',
  '2026-06-14 00:00:00.000'
),
(
  'visitor-vehicle-reservation',
  '访客预约（仅车辆）',
  '安保门禁',
  '校外车辆因公或因私到校访问时，可进行车辆预约进校；被访单位或被访人可线上审核车辆预约申请，审核通过后车辆可在访问时间内进校。',
  NULL,
  JSON_ARRAY('访客(社会人员)'),
  'https://e.ahau.edu.cn/win/zhmz.htm',
  '保卫处',
  '各单位管理员或教职工',
  '0551-65786766',
  '随时',
  '-',
  JSON_ARRAY('手机号验证码注册登录', '被访单位或被访人信息', '访问事由', '访问时间', '车牌号'),
  JSON_ARRAY(
    '访客关注安农卫士微信公众号',
    '点击底部菜单-办事大厅-各类车辆门禁',
    '如未登录，需通过手机号验证码注册登录',
    '因公车辆选择公务车预约，填写被访单位、访问事由、访问时间、车牌号等信息并提交，等待被访单位管理员审批',
    '因私车辆选择临时车预约，填写被访人、访问事由、访问时间、车牌号等信息并提交，等待被访人审批',
    '审批通过后，相关车辆可在预约时段内进出校园'
  ),
  '公务车审批通过后在预约时段内进出校园，离校不收取停车费；因私车辆离校根据停留时长收取停车费。',
  JSON_ARRAY('访客预约', '车辆预约', '公务车预约', '临时车预约', '校外车辆', '车辆进校', '安农卫士'),
  JSON_ARRAY(),
  'ENABLED',
  'https://e.ahau.edu.cn/win/zhmz.htm',
  '2026-06-14 00:00:00.000'
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `handler_count` = VALUES(`handler_count`),
  `target_roles` = VALUES(`target_roles`),
  `entry_url` = VALUES(`entry_url`),
  `department` = VALUES(`department`),
  `contact_person` = VALUES(`contact_person`),
  `contact_phone` = VALUES(`contact_phone`),
  `service_time` = VALUES(`service_time`),
  `basis` = VALUES(`basis`),
  `materials` = VALUES(`materials`),
  `process_steps` = VALUES(`process_steps`),
  `notice` = VALUES(`notice`),
  `keywords` = VALUES(`keywords`),
  `faq` = VALUES(`faq`),
  `status` = VALUES(`status`),
  `source_url` = VALUES(`source_url`),
  `last_verified_at` = VALUES(`last_verified_at`);

INSERT INTO `service_item_assets` (
  `id`,
  `service_item_id`,
  `asset_type`,
  `title`,
  `url`,
  `alt_text`,
  `sort_order`
) VALUES
(
  'graduate-thesis-submission-flow',
  'graduate-thesis-submission',
  'image',
  '研究生学位论文提交办理流程',
  '/service-assets/graduate-thesis-submission-flow.png',
  '研究生学位论文提交办理流程图',
  1
),
(
  'questionnaire-video-guide',
  'questionnaire-voting',
  'link',
  '问卷调查、投票及评比系统使用说明视频教程',
  'https://xxb.ahau.edu.cn/info/1161/5501.htm',
  '问卷调查、投票及评比系统使用说明视频教程',
  1
),
(
  'questionnaire-text-guide',
  'questionnaire-voting',
  'link',
  '问卷投票评比工具使用说明图文教程',
  'https://xxb.ahau.edu.cn/info/1181/7481.htm',
  '问卷投票评比工具使用说明图文教程',
  2
),
(
  'questionnaire-manual-pdf',
  'questionnaire-voting',
  'link',
  '安农大问卷调查用户手册 PDF',
  'http://i.ahau.edu.cn/_upload/ueditor/file/20231106/1699232430264043051.pdf',
  '安农大问卷调查用户手册 PDF',
  3
),
(
  'non-motor-vehicle-policy-doc',
  'non-motor-vehicle-plate-application',
  'link',
  '安徽农业大学电动自行车校园车牌办理工作实施方案',
  'https://i.ahau.edu.cn/_upload/ueditor/file/20250305/1741159390519065599.doc',
  '安徽农业大学电动自行车校园车牌办理工作实施方案',
  1
),
(
  'non-motor-vehicle-reissue-form',
  'non-motor-vehicle-plate-application',
  'link',
  '电动自行车校园车牌遗失损坏补办申请表',
  'https://i.ahau.edu.cn/_upload/ueditor/file/20250305/1741159231593083666.doc',
  '安徽农业大学电动自行车校园车牌遗失损坏补办申请表',
  2
),
(
  'non-motor-vehicle-student-special-form',
  'non-motor-vehicle-plate-application',
  'link',
  '在校学生特殊情况申办校园车牌审批表',
  'https://i.ahau.edu.cn/_upload/ueditor/file/20250305/1741159255004083047.doc',
  '在校学生因特殊情况申办电动自行车校园车牌审批表',
  3
),
(
  'visitor-official-vehicle-flow',
  'visitor-vehicle-reservation',
  'image',
  '因公车辆预约流程图',
  '/service-assets/visitor-official-vehicle-flow.png',
  '因公车辆预约流程图',
  1
),
(
  'visitor-private-vehicle-flow',
  'visitor-vehicle-reservation',
  'image',
  '因私车辆预约流程图',
  '/service-assets/visitor-private-vehicle-flow.png',
  '因私车辆预约流程图',
  2
)
ON DUPLICATE KEY UPDATE
  `service_item_id` = VALUES(`service_item_id`),
  `asset_type` = VALUES(`asset_type`),
  `title` = VALUES(`title`),
  `url` = VALUES(`url`),
  `alt_text` = VALUES(`alt_text`),
  `sort_order` = VALUES(`sort_order`);
