USE `aibs`;

INSERT INTO `service_items` (
  `id`,
  `title`,
  `category`,
  `description`,
  `handler_count`,
  `target_roles`,
  `entry_url`,
  `department`,
  `contact_person`,
  `contact_phone`,
  `service_time`,
  `basis`,
  `materials`,
  `process_steps`,
  `notice`,
  `keywords`,
  `faq`,
  `status`,
  `source_url`,
  `last_verified_at`
) VALUES
(
  'faculty-leave-travel-one-form',
  '教职工请假（报备、出差）一张表',
  '人事服务',
  '适用于全体在职在岗教职工，可用于发起公务出差申请、个人假期轮休离肥报备、因私请假等事项。公务出差包括因公务工作参加培训、会议、学习、调研等；离肥报备仅限个人于假期轮休离肥，按学校要求向单位报备；因私请假包括事假、病假、产假、婚假、探亲假、工伤假、丧假。',
  5000,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.gwcc.gwcc',
  '党委教师工作部、人事处、人才办',
  '各单位有审批权限的领导',
  '各单位',
  '任何时间',
  '-',
  JSON_ARRAY('出差、离肥报备或因私请假所需信息', '同行人信息，如有同行教职工或学生'),
  JSON_ARRAY(
    '按照因公出差、离肥报备、因私请假实际需要选择类型',
    '按要求填写表单信息',
    '如有同行人（教职工或学生），添加同行人信息',
    '提交后表单自动推送至具有审批权限的领导',
    '领导完成审批后流程结束',
    '如需打印因公出差审批单，可在审批完成后进入“我的已办”查看相应办事记录，点击“打印”按钮直接打印，并支持导出 PDF'
  ),
  '在校学生不得单独发起出差申请，可作为教职工同行人员参与相关审批流程。所有公务出差必须在出发前完成审批手续，严禁事后补报。经审批签批的出差申请表单作为财务报销的必要凭证；公务出差事项必须通过专门出差审批流程（线上或线下）办理，不得以请假审批流程代替。',
  JSON_ARRAY('教职工请假', '请假', '报备', '出差', '公务出差', '离肥报备', '因私请假', '病假', '事假', '产假', '打印出差审批单'),
  JSON_ARRAY(
    JSON_OBJECT('question', '学生可以单独发起出差申请吗？', 'answer', '不可以。在校学生不得单独发起出差申请，可作为教职工同行人员参与相关审批流程。'),
    JSON_OBJECT('question', '出差审批单如何打印？', 'answer', '审批完成后进入“我的已办”查看相应办事记录，点击下方“打印”按钮即可直接打印，并支持导出为 PDF。')
  ),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.gwcc.gwcc',
  '2026-06-14 00:00:00.000'
),
(
  'lab-team-platform-admin',
  '实验室（团队）平台管理后台',
  '科研服务',
  '作为学校实验室（团队）平台网站的管理后台，可对有需要展示的实验室团队及科研平台网站内容进行维护。实验室团队及科研平台网站指定专人维护，由数据管理处授权访问管理后台。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://labmanage.ahau.edu.cn/anutalabwebapp/platform/login.html',
  '科技处',
  '侯老师',
  '0551-65786222',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('经授权的实验室团队或科研平台网站维护账号'),
  JSON_ARRAY('由实验室团队或科研平台指定专人维护', '经数据管理处授权后访问管理后台', '登录后台维护实验室团队及科研平台网站内容'),
  '实验室（团队）平台网站地址为 https://lab.ahau.edu.cn，管理后台访问权限以数据管理处授权为准。',
  JSON_ARRAY('实验室平台', '团队平台', '科研平台', '平台管理后台', '实验室团队', '科技处', 'lab', 'labmanage'),
  JSON_ARRAY(),
  'ENABLED',
  'https://labmanage.ahau.edu.cn/anutalabwebapp/platform/login.html',
  '2026-06-14 00:00:00.000'
),
(
  'research-invoice-online-application',
  '科研发票线上申请',
  '财务服务',
  '主要面向申请科研经费的教职工提供科研发票线上申请服务。经费已入账时需上传入账通知单；经费未到账时需填写扣税财务经费代码并上传相关承诺书和合同页面。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.kyfpzxsq.kyfpzxsq',
  '财务处',
  '王老师，程老师',
  '0551-65786669',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY(
    '经费已入账：入账通知单（在财务系统来款认领中打印）',
    '经费未到账：扣税财务经费代码',
    '经费未到账：附件2 预借发票承诺书',
    '经费未到账：附件3 合同首页及有付款金额和双方单位盖章的页面',
    '科研系统项目编号，纵向为校内流水号、横向为合同编号'
  ),
  JSON_ARRAY('进入科研发票线上申请流程', '根据经费是否到账填写对应信息', '上传所需附件材料', '提交后等待财务处处理'),
  '普通发票和专用发票税率都是 3%，需和对方单位确认开票种类。特殊情况或免税发票的开具仍走线下流程，现场办理。',
  JSON_ARRAY('科研发票', '发票申请', '科研经费', '财务处', '入账通知单', '预借发票', '横向课题', '纵向项目', '合同编号'),
  JSON_ARRAY(
    JSON_OBJECT('question', '普通发票和专用发票税率是多少？', 'answer', '普通和专用发票税率都是 3%，需和对方单位确认开票种类。'),
    JSON_OBJECT('question', '免税发票能线上办吗？', 'answer', '特殊情况或免税发票的开具仍走线下流程，现场办理。')
  ),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.kyfpzxsq.kyfpzxsq',
  '2026-06-14 00:00:00.000'
),
(
  'new-faculty-onboarding-one-stop',
  '新教师入职一件事',
  '人事服务',
  '为新进教职工整合入职后需办理的相关事务服务提示和快捷入口，包括党团组织关系转接、人才公寓申请、门禁系统开通、公务卡办理、安家费申领、科研启动经费申请、加入校工会、填写干部履历表、校园一卡通办理、启薪手续等。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/coreplus/xjsrzbdyjsxsfw/form/xjsrzbdyjsxsfw.jsp',
  '党委教师工作部、人事处、人才办',
  '李老师',
  '0551-65786168',
  '工作日',
  '-',
  JSON_ARRAY('新进教职工在线提交的入职相关材料'),
  JSON_ARRAY('新进教职工在线提交材料', '相关流程自动流转至党委组织部、人事处、财务处、保卫处等对应部门办理', '进入“新教师入职报到管理”查看办理情况'),
  '具体入职事项和材料要求以系统页面及相关部门通知为准。',
  JSON_ARRAY('新教师', '新进教职工', '入职', '入职一件事', '人才公寓', '公务卡', '安家费', '科研启动经费', '校园一卡通', '启薪'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/coreplus/xjsrzbdyjsxsfw/form/xjsrzbdyjsxsfw.jsp',
  '2026-06-14 00:00:00.000'
),
(
  'zhxy-meeting-room-reservation',
  '资环学院会议室在线预约',
  '学院服务',
  '为加强和规范资源与环境学院会议室使用和管理，更好地服务师生，资源与环境学院启用线上会议室申请流程，电脑端和手机端均可申请。',
  NULL,
  JSON_ARRAY('资环学院教职工'),
  'https://my.ahau.edu.cn/default/work/ahau/zhxy_hyszxyy/index.jsp',
  '资源与环境学院',
  '陈老师',
  '0551-65786595',
  '即时办理',
  '-',
  JSON_ARRAY('数智安农账号', '会议室预约使用信息'),
  JSON_ARRAY('进入数智安农-安心办-部门服务', '搜索“资环学院会议室在线预约”', '进入在线办理流程', '选择会议室并填写预约信息', '提交申请'),
  '会议室服务范围包括中西部综合楼南楼510会议室、中西部综合楼南楼506会议室、研究生综合楼B楼2010党建室、久易学术报告厅、中西部综合楼南楼107智慧教室、中西部综合楼南楼105多功能教室。',
  JSON_ARRAY('资环学院', '资源与环境学院', '会议室', '会议室预约', '学院会议室', '部门服务', '久易学术报告厅', '智慧教室'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/work/ahau/zhxy_hyszxyy/index.jsp',
  '2026-06-14 00:00:00.000'
),
(
  'electronic-signature-seal-service',
  '电子签章服务',
  '信息化服务',
  '面向校务服务流转使用的电子文档，提供在线签名和电子公章服务。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xsyydjfw.xsyydjfw',
  '数据管理处（信息化办公室）',
  '教职工（签名人）、业务部门（盖章部门）',
  '-',
  '工作日正常办公时间',
  '关于印发《安徽农业大学电子印章管理办法（试行）》的通知',
  JSON_ARRAY('需要申请签章的电子文档，支持 WORD、PDF、JPG 上传'),
  JSON_ARRAY(
    '只选择“签名”：申请-签名受理人-结束',
    '本科生只选择“盖章”：申请-辅导员预审-所在单位领导审核-二级单位审核-二级单位领导审核-经办人盖章-结束',
    '研究生只选择“盖章”：申请-导师预审-所在单位领导审核-二级单位审核-二级单位领导审核-经办人盖章-结束',
    '教职工只选择“盖章”：申请-所在单位领导审核-二级单位审核-二级单位领导审核-经办人盖章-结束',
    '签字+盖章流程（含校领导签字）：按照当前纸质文件二级部门签字盖章完成后，由校领导签字的流程建立相应电子签章流程'
  ),
  '电子签章服务试运行范围以系统内提示和业务部门要求为准。',
  JSON_ARRAY('电子签章', '电子签名', '电子公章', '盖章', '签名', '用印', '签字盖章', 'WORD', 'PDF', 'JPG'),
  JSON_ARRAY(
    JSON_OBJECT('question', '可以上传哪些格式？', 'answer', '支持 WORD、PDF、JPG 上传。'),
    JSON_OBJECT('question', '本科生盖章需要经过哪些审核？', 'answer', '申请后需经辅导员预审、所在单位领导审核、二级单位审核、二级单位领导审核，再由经办人盖章。')
  ),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xsyydjfw.xsyydjfw',
  '2026-06-14 00:00:00.000'
),
(
  'library-auditorium-reservation',
  '图书馆报告厅申请预约',
  '图书馆服务',
  '为提高图书馆报告厅使用效率、充分发挥功能，学校依托数智安农“安心办”平台提供图书馆报告厅使用申请服务。图书馆学术报告厅是学校承担重要会议、学术报告等活动的场所。',
  1200,
  JSON_ARRAY('教职工'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.ahau.tsgbgtyysq.tsgbgtyysq',
  '图书馆、档案馆',
  '顾老师',
  '0551-65786386，65786334',
  '周一至周五 上午：08:00-11:30 下午：14:00-17:30',
  '报告厅使用费内部转账流程说明',
  JSON_ARRAY('报告厅预约使用信息', '申请部门信息', '如需内转，按要求提交缴费单或内转缴费凭证'),
  JSON_ARRAY(
    '登录智慧安农网上办事大厅，进入图书馆报告厅使用预约系统按需提交申请',
    '申请人部门领导审批',
    '党政办公室审核',
    '图书馆综合服务部审核',
    '会议结束后申请人提交内转缴费凭证',
    '图书馆综合服务部审核',
    '流程结束'
  ),
  '各部门须提前根据需求提出申请，并按程序线上申请。如预约撤销或时间变更，预约部门应提前办理撤销或变更手续。若预约部门存在3次没有办结的流程，将无法继续申请。使用方须在报告厅管理人员指导和监督下使用设备设施，会议结束后清扫报告厅并检查门窗、电源。',
  JSON_ARRAY('图书馆报告厅', '报告厅预约', '学术报告厅', '会议场地', '图书馆', '座位表', '内转', '缴费单', '报告厅申请'),
  JSON_ARRAY(
    JSON_OBJECT('question', '如果部门有未办结流程还能继续申请吗？', 'answer', '如果部门存在3次没有办结的流程，将无法继续申请。'),
    JSON_OBJECT('question', '座位表在哪里查看？', 'answer', '可在附件/相关链接中查看第一报告厅、第二报告厅、第三第四报告厅座位表 PDF。')
  ),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.ahau.tsgbgtyysq.tsgbgtyysq',
  '2026-06-14 00:00:00.000'
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `handler_count` = VALUES(`handler_count`),
  `target_roles` = VALUES(`target_roles`),
  `entry_url` = VALUES(`entry_url`),
  `department` = VALUES(`department`),
  `contact_person` = VALUES(`contact_person`),
  `contact_phone` = VALUES(`contact_phone`),
  `service_time` = VALUES(`service_time`),
  `basis` = VALUES(`basis`),
  `materials` = VALUES(`materials`),
  `process_steps` = VALUES(`process_steps`),
  `notice` = VALUES(`notice`),
  `keywords` = VALUES(`keywords`),
  `faq` = VALUES(`faq`),
  `status` = VALUES(`status`),
  `source_url` = VALUES(`source_url`),
  `last_verified_at` = VALUES(`last_verified_at`);

INSERT INTO `service_item_assets` (
  `id`,
  `service_item_id`,
  `asset_type`,
  `title`,
  `url`,
  `alt_text`,
  `sort_order`
) VALUES
(
  'faculty-leave-print-pdf-guide',
  'faculty-leave-travel-one-form',
  'image',
  '出差审批单导出 PDF 示例',
  '/service-assets/faculty-leave-print-pdf-guide.png',
  '打印页面中选择另存为 PDF 的示例截图',
  1
),
(
  'library-auditorium-approval-flow',
  'library-auditorium-reservation',
  'image',
  '图书馆报告厅审批说明',
  '/service-assets/library-auditorium-approval-flow.png',
  '图书馆报告厅申请审批流程示意图',
  1
),
(
  'library-auditorium-process-flow',
  'library-auditorium-reservation',
  'image',
  '图书馆报告厅办理流程',
  '/service-assets/library-auditorium-process-flow.png',
  '图书馆报告厅办理流程图',
  2
),
(
  'library-auditorium-seat-first',
  'library-auditorium-reservation',
  'link',
  '第一报告厅座位表 PDF',
  'http://lib.ahau.edu.cn/__local/4/FD/19/6E1F6BA94085145239BE6D7F8CA_56B0921D_1B096.pdf?e=.pdf',
  '第一报告厅座位表 PDF',
  3
),
(
  'library-auditorium-seat-second',
  'library-auditorium-reservation',
  'link',
  '第二报告厅座位表 PDF',
  'http://lib.ahau.edu.cn/__local/E/53/08/2990D03AEAE8E4E5A251A41A19D_72EFD3A0_12DBC.pdf?e=.pdf',
  '第二报告厅座位表 PDF',
  4
),
(
  'library-auditorium-seat-third-fourth',
  'library-auditorium-reservation',
  'link',
  '第三第四报告厅座位表 PDF',
  'http://lib.ahau.edu.cn/__local/9/02/CB/74D0E0374478406F58D22D3C6D6_E1852EA0_12A1C.pdf?e=.pdf',
  '第三第四报告厅座位表 PDF',
  5
)
ON DUPLICATE KEY UPDATE
  `service_item_id` = VALUES(`service_item_id`),
  `asset_type` = VALUES(`asset_type`),
  `title` = VALUES(`title`),
  `url` = VALUES(`url`),
  `alt_text` = VALUES(`alt_text`),
  `sort_order` = VALUES(`sort_order`);
