USE `aibs`;

INSERT INTO `service_items` (
  `id`,
  `title`,
  `category`,
  `description`,
  `handler_count`,
  `target_roles`,
  `entry_url`,
  `department`,
  `contact_person`,
  `contact_phone`,
  `service_time`,
  `basis`,
  `materials`,
  `process_steps`,
  `notice`,
  `keywords`,
  `faq`,
  `status`,
  `source_url`,
  `last_verified_at`
) VALUES
(
  'team-activity-room-application',
  '团队活动室申请',
  '场地预约',
  '团队活动室免费向在校大学生预约开放，但不得以各种名义开展营利性活动或其它禁止的活动。服务范围包括图书馆团队活动室、本科生院“一站式”活动场地、团委欣苑四楼小礼堂等。',
  2891,
  JSON_ARRAY('教职工'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.tsgtdhds.tsgtdhds',
  '图书馆、档案馆',
  '图书馆：顾老师；一站式社区：周老师；团委：夏老师',
  '图书馆顾老师：0551-65786386；本科生院周老师：0551-65780064；团委夏老师：0551-65781884',
  '周一至周五 上午：08:00-11:30 下午：14:00-17:30',
  '-',
  JSON_ARRAY('活动场地预约信息', '活动时间、人数、用途等信息'),
  JSON_ARRAY(
    '进入团队活动室申请流程',
    '根据实际需要选择图书馆团队活动室、“一站式”活动场地或欣苑四楼小礼堂',
    '按页面要求填写活动信息并提交',
    '等待对应管理部门受理或审核'
  ),
  '图书馆申请区域包括801、808、810、811、812、814；“一站式”活动场地使用时间段为8:00-21:00，活动需提前一周预约；欣苑四楼小礼堂可使用时段为8:00-22:00，活动需提前一周预约。线上预约开放时间一般为周一上午8:00至周五下午17:30。',
  JSON_ARRAY('团队活动室', '活动室申请', '图书馆团队活动室', '一站式活动场地', '欣苑四楼小礼堂', '场地预约', '小礼堂', '团委'),
  JSON_ARRAY(
    JSON_OBJECT('question', '图书馆团队活动室有哪些区域？', 'answer', '申请区域包括图书馆801、808、810、811、812、814。'),
    JSON_OBJECT('question', '一站式活动场地需要提前多久预约？', 'answer', '活动需提前一周进行场地预约。'),
    JSON_OBJECT('question', '小礼堂预约有什么限制？', 'answer', '彩排和初赛活动原则上不接受预约，同一场活动预约时长不得超过8小时；每周三12:00-22:00校团委活动使用，原则上不外借。')
  ),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.tsgtdhds.tsgtdhds',
  '2026-06-14 00:00:00.000'
),
(
  'bocai-ebook-resources',
  '博采图书电子资源',
  '图书馆服务',
  '学校图书馆建设的博采电子资源导航，可为在校师生提供图书电子资源服务，校内、校外均可使用。',
  NULL,
  JSON_ARRAY('本科生', '研究生', '教职工'),
  'https://ahau.metaersp.com/personalIndex',
  '图书馆、档案馆',
  '龚老师',
  '0551-65786335',
  '任何时间',
  '-',
  JSON_ARRAY('校园统一身份认证账号'),
  JSON_ARRAY('打开博采图书电子资源入口', '按页面提示登录或访问资源', '根据需要检索和使用图书电子资源'),
  '校内、校外均可使用，具体访问方式以页面提示为准。',
  JSON_ARRAY('博采图书', '电子资源', '图书电子资源', '数据库', '图书馆资源', '校外访问', 'metaersp'),
  JSON_ARRAY(),
  'ENABLED',
  'https://ahau.metaersp.com/personalIndex',
  '2026-06-14 00:00:00.000'
),
(
  'vacant-classroom-query-borrow',
  '空闲教室查询及借用',
  '教务服务',
  '教职工可通过本科教务系统进行空闲教室查询，并通过“借教室-新建申请”进行空闲教室查询和借用。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://bkjw.ahau.edu.cn/home/#/home',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '李老师',
  '0551-65786169',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('本科教务系统账号', '借用教室用途、时间等信息'),
  JSON_ARRAY('进入本科教务系统', '选择“借教室”', '点击“新建申请”', '查询空闲教室并填写借用信息', '提交申请'),
  '教室可借用情况以本科教务系统实时查询结果为准。',
  JSON_ARRAY('空闲教室', '教室查询', '借教室', '教室借用', '本科教务系统', '教务处'),
  JSON_ARRAY(),
  'ENABLED',
  'https://bkjw.ahau.edu.cn/home/#/home',
  '2026-06-14 00:00:00.000'
),
(
  'student-leaving-campus-one-stop',
  '学生离校一件事',
  '毕业离校',
  '面向本科生和研究生，学生离校一件事服务集中整合毕业离校可能需要办理的事项提醒，包括组织关系转接、图书归还、水电网费退费、学费欠费清缴、一卡通余额、车牌和户口迁移、毕业生快递、档案状态、退宿、研究生毕业论文提交等。',
  NULL,
  JSON_ARRAY('本科生', '研究生'),
  'http://my.ahau.edu.cn/default/work/ahau/xslxxsfw/xslxxsfwLogin.jsp',
  '党委学生工作部、党委武装部、学生处（学生资管中心、大学生就业指导中心）',
  '本科生院、研究生院、各学院相关老师',
  '各单位部门电话',
  '即时办理',
  '-',
  JSON_ARRAY('校园统一身份认证账号', '毕业离校相关个人信息'),
  JSON_ARRAY(
    '进入学生离校一件事服务',
    '查看党/团组织关系转接提醒',
    '查看图书借阅实时数据并按需归还图书',
    '查看水电网费统一或零星退费方法',
    '查看学费欠费清缴提醒',
    '查看一卡通余额及状态，并可使用一卡通余额捐赠到学校教育基金会功能',
    '查看电动自行车校园车牌、户口迁移、毕业生快递、档案状态及转寄情况',
    '研究生可通过快捷入口提交毕业论文相关材料'
  ),
  '离校事项涉及多个部门，具体状态和办理要求以系统实时展示及各单位通知为准。',
  JSON_ARRAY('离校', '毕业离校', '离校一件事', '毕业生', '档案转寄', '图书归还', '一卡通余额', '退宿', '论文提交', '组织关系转接'),
  JSON_ARRAY(),
  'ENABLED',
  'http://my.ahau.edu.cn/default/work/ahau/xslxxsfw/xslxxsfwLogin.jsp',
  '2026-06-14 00:00:00.000'
),
(
  'forum-lecture-conference-approval',
  '论坛、讲坛、讲座、年会、报告会、研讨会审批申请',
  '宣传审批',
  '为进一步改进工作作风，提高办事效率，优化各单位举办论坛、讲坛、讲座、年会、报告会、研讨会的审批流程，学校利用“智慧校园”平台搭建相关审批申请系统。',
  1493,
  JSON_ARRAY('教职工'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.hysq.hysq',
  '党委宣传部（新闻中心）、党委统战部',
  '胡老师',
  '13855119207',
  '周一至周五 上午：08:00-11:30 下午：14:00-17:30',
  '-',
  JSON_ARRAY('论坛、讲坛、讲座、年会、报告会、研讨会等活动申请信息', '涉及报告人时按要求提交相关审批材料'),
  JSON_ARRAY(
    '申请人提交申请',
    '主办单位负责人审核',
    '涉及外籍人士或国际交流合作事项时，提交国际交流合作处审核',
    '人文社科类提交社会科学处审核，自然科学类提交科技处审核',
    '党委宣传部审核',
    '重大、重要活动提交分管校领导审核',
    '流程结束'
  ),
  '举办论坛、讲坛、讲座、年会、报告会、研讨会等活动，必须坚持正确政治方向，遵守党的纪律和国家法律法规。按照谁主管谁负责、谁主办谁负责原则，各级党委对本单位主管、主办活动负主体责任。举办相关活动应按规定提前一周提出申请。',
  JSON_ARRAY('论坛审批', '讲坛审批', '讲座审批', '年会审批', '报告会审批', '研讨会审批', '宣传部', '统战部', '国际交流合作处'),
  JSON_ARRAY(
    JSON_OBJECT('question', '活动需要提前多久申请？', 'answer', '举办论坛、讲坛、讲座、年会、报告会、研讨会等活动，应按规定提前一周提出申请。'),
    JSON_OBJECT('question', '邀请校外报告人需要注意什么？', 'answer', '邀请高校、党校、社会科学院专家学者和党政机关、人民团体、社会组织、企事业单位工作人员担任报告人时，需提交报告人所在党组织书面审批表。')
  ),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.hysq.hysq',
  '2026-06-14 00:00:00.000'
),
(
  'computing-power-application',
  '算力申请',
  '信息化服务',
  '算力申请（扩容）面向教师开放。算力资源分配使用原则为“先申请先审批，按序使用”，用户获得超算平台账号后，可以通过“数智安农/算力申请”进行申请，经审核后，超算平台调配算力资源。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.cskrsq.cskrsq',
  '数据管理处（信息化办公室）',
  '杨老师',
  '0551-65786139',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('超算平台账号', '算力资源申请信息'),
  JSON_ARRAY('获得超算平台账号', '进入数智安农/算力申请', '按需填写算力资源申请', '提交后等待审核', '审核后由超算平台调配算力资源'),
  '调试资源申请原则上 CPU≤12 核、内存≤64GB。正式运行作业所需算力资源请仔细评估后申请，避免浪费。',
  JSON_ARRAY('算力申请', '超算', '超算平台', 'CPU', '内存', '算力扩容', '数据管理处', '信息化办公室'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.cskrsq.cskrsq',
  '2026-06-14 00:00:00.000'
),
(
  'student-email-service',
  '学生邮箱服务',
  '信息化服务',
  '为学生及校友提供 @stu.ahau.edu.cn 邮箱服务，每名在校学生仅限申请 1 个邮箱账号；校友在毕业后仍可使用原先申请的学生邮箱。',
  NULL,
  JSON_ARRAY('研究生校友', '本科生校友', '教职工校友', '本科生', '研究生'),
  'https://xxb.ahau.edu.cn/info/1181/4781.htm',
  '数据管理处（信息化办公室）',
  '康老师',
  '0551-65786196',
  '任何时间',
  '-',
  JSON_ARRAY('校园统一身份认证账号', '学生或校友身份信息'),
  JSON_ARRAY('在校学生进入数智安农', '在“我的邮件”栏目下方点击“申请邮箱”入口', '按页面提示自助申请邮箱'),
  '每名在校学生仅限申请 1 个邮箱账号。校友毕业后仍可使用原先申请的学生邮箱。',
  JSON_ARRAY('学生邮箱', '校园邮箱', 'stu.ahau.edu.cn', '邮箱申请', '邮箱注册', '校友邮箱', '二次验证', 'Foxmail', '网易邮箱'),
  JSON_ARRAY(
    JSON_OBJECT('question', '在哪里申请学生邮箱？', 'answer', '在校学生可通过数智安农-我的邮件栏目下方的“申请邮箱”入口自助申请。'),
    JSON_OBJECT('question', '毕业后还能使用学生邮箱吗？', 'answer', '校友在毕业后仍可使用原先申请的学生邮箱。')
  ),
  'ENABLED',
  'https://xxb.ahau.edu.cn/info/1181/4781.htm',
  '2026-06-14 00:00:00.000'
),
(
  'institution-legal-person-certificate-use',
  '《事业单位法人证书》使用申请',
  '档案服务',
  '服务各部门及教职工，满足工作场景中申请使用学校《事业单位法人证书》的需要。适用场景包括课题申报及结题、软件著作权申请、专利申请、公派出国（境）签证、校外社会科技服务项目投标或转让、平台开户年审注销、后勤工作、资产招租报废、购买进口产品或危险品、开立银行账户、减税免税退税等。',
  131,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.sydwfrzssysq.sydwfrzssysq',
  '图书馆、档案馆',
  '邱老师',
  '0551-65786318',
  '工作日办公时间',
  '安徽农业大学《事业单位法人证书》使用管理办法（试行）',
  JSON_ARRAY('根据表单中申请项目表单要求提交材料'),
  JSON_ARRAY('申请人根据需要提交信息', '经审核同意后，申请人下载打印件', '到材料与化学学院楼（档案馆303室）线下办理', '按需使用《事业单位法人证书》副本复印件、扫描件或原件'),
  '线下办理地点为材料与化学学院楼（档案馆303室）。具体使用方式和材料要求以表单要求及档案馆审核为准。',
  JSON_ARRAY('事业单位法人证书', '法人证书', '档案馆', '课题申报', '软件著作权', '专利申请', '签证', '投标', '银行账户', '免税'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.sydwfrzssysq.sydwfrzssysq',
  '2026-06-14 00:00:00.000'
),
(
  'union-member-condolence-application',
  '工会会员慰问申报',
  '工会服务',
  '工会为在职工会会员提供生病住院、女职工生育、结婚、首次重大疾病四项慰问服务线上申报。',
  140,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.ghhywwsb.ghhywwsb',
  '工会',
  '钱老师',
  '0551-65786448',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('在职工会会员身份信息', '慰问事项相关证明材料，按表单要求提交'),
  JSON_ARRAY('在职工会会员线上申报', '工会相关人员受理审批', '审批结束后流程办结', '慰问金一般于办结次月上旬通过转账进入申报人工资卡'),
  '慰问项目包括生病住院（1000元）、女职工生育（1000元）、结婚（1000元）、首次重大疾病（2000元）。',
  JSON_ARRAY('工会', '工会会员', '慰问申报', '生病住院', '女职工生育', '结婚', '重大疾病', '慰问金'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.ghhywwsb.ghhywwsb',
  '2026-06-14 00:00:00.000'
),
(
  'mental-health-counseling-reservation',
  '心理咨询预约',
  '学生服务',
  '为在校学生提供心理咨询预约服务。',
  NULL,
  JSON_ARRAY('本科生', '研究生', '数据管理处-数据中心'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xlzxyy.xlzxyy',
  '党委学生工作部、党委武装部、学生处（学生资管中心、大学生就业指导中心）',
  '柯老师',
  '0551-65786445',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('无'),
  JSON_ARRAY('搜索“心理咨询预约”', '进行信息填写', '提交预约申请', '等待专人受理'),
  '如遇特殊情况，可拨打电话 0551-65786445。',
  JSON_ARRAY('心理咨询', '心理咨询预约', '心理健康', '学生处', '预约咨询', '柯老师'),
  JSON_ARRAY(
    JSON_OBJECT('question', '申请材料是什么？', 'answer', '无。'),
    JSON_OBJECT('question', '特殊情况联系谁？', 'answer', '可拨打电话 0551-65786445。')
  ),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xlzxyy.xlzxyy',
  '2026-06-14 00:00:00.000'
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `handler_count` = VALUES(`handler_count`),
  `target_roles` = VALUES(`target_roles`),
  `entry_url` = VALUES(`entry_url`),
  `department` = VALUES(`department`),
  `contact_person` = VALUES(`contact_person`),
  `contact_phone` = VALUES(`contact_phone`),
  `service_time` = VALUES(`service_time`),
  `basis` = VALUES(`basis`),
  `materials` = VALUES(`materials`),
  `process_steps` = VALUES(`process_steps`),
  `notice` = VALUES(`notice`),
  `keywords` = VALUES(`keywords`),
  `faq` = VALUES(`faq`),
  `status` = VALUES(`status`),
  `source_url` = VALUES(`source_url`),
  `last_verified_at` = VALUES(`last_verified_at`);

INSERT INTO `service_item_assets` (
  `id`,
  `service_item_id`,
  `asset_type`,
  `title`,
  `url`,
  `alt_text`,
  `sort_order`
) VALUES
(
  'forum-approval-flow-wide',
  'forum-lecture-conference-approval',
  'image',
  '论坛讲坛讲座等审批流程总览',
  '/service-assets/forum-approval-flow-wide.png',
  '论坛、讲坛、讲座、年会、报告会、研讨会审批流程总览图',
  1
),
(
  'forum-approval-flow-detail',
  'forum-lecture-conference-approval',
  'image',
  '论坛讲坛讲座等审批申请流程',
  '/service-assets/forum-approval-flow-detail.png',
  '论坛、讲坛、讲座、年会、报告会、研讨会审批申请流程图',
  2
),
(
  'computing-power-resource-image',
  'computing-power-application',
  'image',
  '超算一期算力资源',
  'https://i.ahau.edu.cn/ywtbapi/rhmhUpload/serviceAttachments/41536dbce5ea5951f7cb803a7b228f38f25d036299375829b39b0e74a98b8a50.png',
  '超算一期算力资源图片',
  1
),
(
  'student-email-video-guide',
  'student-email-service',
  'link',
  '邮箱注册使用视频教程',
  'https://xxb.ahau.edu.cn/info/1161/5031.htm',
  '邮箱注册使用视频教程',
  1
),
(
  'student-email-web-guide',
  'student-email-service',
  'link',
  '学生申请使用校园邮箱',
  'https://xxb.ahau.edu.cn/info/1181/4781.htm',
  '学生申请使用校园邮箱教程',
  2
),
(
  'student-email-2fa-guide',
  'student-email-service',
  'link',
  '邮箱启用登录二次验证的使用提示',
  'https://xxb.ahau.edu.cn/info/1181/4711.htm',
  '邮箱启用登录二次验证的使用提示',
  3
)
ON DUPLICATE KEY UPDATE
  `service_item_id` = VALUES(`service_item_id`),
  `asset_type` = VALUES(`asset_type`),
  `title` = VALUES(`title`),
  `url` = VALUES(`url`),
  `alt_text` = VALUES(`alt_text`),
  `sort_order` = VALUES(`sort_order`);
