USE `aibs`;

INSERT INTO `service_items` (
  `id`,
  `title`,
  `category`,
  `description`,
  `handler_count`,
  `target_roles`,
  `entry_url`,
  `department`,
  `contact_person`,
  `contact_phone`,
  `service_time`,
  `basis`,
  `materials`,
  `process_steps`,
  `notice`,
  `keywords`,
  `faq`,
  `status`,
  `source_url`,
  `last_verified_at`
) VALUES
(
  'freshman-major-transfer',
  '新生转专业',
  '教务服务',
  '根据《安徽农业大学本科学生转专业办法》（校教发〔2024〕23号）和2025-2026学年本科生转专业工作安排，符合条件的新生可线上提交转专业申请，转出、转入学院审核并录入结果。',
  2657,
  JSON_ARRAY('本科生'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xszzysq.xszzysqlc',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '胡老师、赵老师',
  '0551-65786163',
  '以2025年转专业通知时间为准',
  '《关于印发<安徽农业大学本科学生转专业办法>的通知》校教发〔2024〕23号',
  JSON_ARRAY('身份证正反面电子件', '转专业申请表电子件或纸质签字盖章后照片'),
  JSON_ARRAY(
    '大一新生线上提交转专业申请，并按要求填写信息',
    '提交后打印信息表，本人签字、学院盖章，然后拍照上传附件',
    '辅导员初审；在申请提交截止时间前，如初审不通过，允许学生再次提交',
    '所在学院工作人员进行转出审核，学生收到短信通知',
    '第一志愿线下录取结束后，转入学院线上录入录取结果',
    '第一志愿未录取的学生信息自动传递给第二志愿',
    '第二志愿线下录取结束后，转入学院线上录入录取结果',
    '系统自动汇总录取结果，流程结束'
  ),
  '线下录取环节以转入学院通知和学院招录细则为准，可能包含面试、考核、考试等方式。',
  JSON_ARRAY('转专业', '新生转专业', '本科生转专业', '大一转专业', '专业调整', '教务处', '申请表'),
  JSON_ARRAY(
    JSON_OBJECT('question', '申请表在哪里获取？', 'answer', '学生提交申请后可在系统中打印申请表。'),
    JSON_OBJECT('question', '录取环节在线上完成吗？', 'answer', '申请和结果录入在线上完成，录取考核一般按照转入学院通知线下进行。')
  ),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xszzysq.xszzysqlc',
  '2026-06-14 00:00:00.000'
),
(
  'library-seat-reservation',
  '图书馆座位预约',
  '图书馆服务',
  '提供图书馆座位在线预约服务。',
  NULL,
  JSON_ARRAY('本科生', '研究生', '教职工'),
  'https://libres.ahau.edu.cn/home/web/seat/area/1',
  '图书馆、档案馆',
  '秦老师',
  '0551-65786335',
  '任何时间',
  '-',
  JSON_ARRAY('校园统一身份认证账号'),
  JSON_ARRAY('进入图书馆座位预约系统', '选择馆区、区域和座位', '选择可预约时间段', '提交预约并按预约规则使用座位'),
  '座位开放范围、预约规则和签到要求以图书馆座位预约系统显示为准。',
  JSON_ARRAY('图书馆', '座位预约', '图书馆座位', '自习座位', '座位', '预约座位'),
  JSON_ARRAY(),
  'ENABLED',
  'https://libres.ahau.edu.cn/home/web/seat/area/1',
  '2026-06-14 00:00:00.000'
),
(
  'campus-face-access-collection',
  '门禁人脸采集',
  '校园安全',
  '面向全校师生提供校园门禁人脸信息采集服务，重新采集完成后，人脸数据自动同步至数据中心，用于进出校园大门和宿舍楼门禁等场景。',
  NULL,
  JSON_ARRAY('本科生', '研究生', '教职工'),
  'https://xssq.ahau.edu.cn/face/#/',
  '保卫处',
  '石老师',
  '0551-65786766',
  '任何时间',
  '关于印发《安徽农业大学人员和非机动车智能门禁系统使用管理规定（试行）》的通知（校办字[2022]16号）',
  JSON_ARRAY('校园统一身份认证账号', '本人清晰人脸照片或现场采集信息'),
  JSON_ARRAY('根据身份选择人脸采集入口', '查看并确认个人信息', '点击重新采集并按页面提示完成人脸采集', '等待约1至2分钟后生效'),
  '每个自然年只允许重新采集一次，请确认照片清晰、本人操作后再提交。',
  JSON_ARRAY('门禁', '人脸采集', '人脸识别', '宿舍门禁', '校园大门', '保卫处', '重新采集'),
  JSON_ARRAY(
    JSON_OBJECT('question', '重新采集多久生效？', 'answer', '一般约1至2分钟生效。'),
    JSON_OBJECT('question', '一年可以重新采集几次？', 'answer', '每个自然年只允许重新采集一次。')
  ),
  'ENABLED',
  'https://xssq.ahau.edu.cn/face/#/',
  '2026-06-14 00:00:00.000'
),
(
  'online-interview-booth-reservation',
  '线上面试亭预约',
  '就业服务',
  '学校面向毕业生提供勤学楼、博学楼、图书馆、大学生公寓一站式服务中心北区、欣苑食堂三楼一站式南区等线上面试亭，缓解毕业生求职线上面试需求。',
  1146,
  JSON_ARRAY('面试亭管理部门', '本科生', '研究生'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.mstyysq.mstyysqlc',
  '党委学生工作部、党委武装部、学生处（学生资管中心、大学生就业指导中心）',
  '史老师',
  '0551-65786432',
  '1天',
  '-',
  JSON_ARRAY('线上面试证明，如短信、邮件或面试通知截图'),
  JSON_ARRAY(
    '勤学楼、博学楼、图书馆、一站式服务中心北区四个面试亭通过微信扫码进入小程序预约',
    '在预约首页点击“面试亭预约”，选择需要使用的面试亭',
    '点击“立即预约”，选择使用时间段，单次使用不超过1小时',
    '提交预约；预约成功后可在小程序面试亭记录中查看或取消',
    '预约成功后会收到含电子锁密码的短信，密码仅限预约时间使用',
    '到场后长按门锁面板，输入电子锁密码并点击“#”号键开锁进入',
    '欣苑食堂三楼一站式南区面试亭通过“数智安农-安心办-线上面试亭预约”申请',
    '欣苑食堂三楼一站式南区预约经老师审核通过后，学生在面试前2小时收到电子锁密码短信',
    '使用完毕后清理桌面、关闭灯光空调等电源、带走个人物品并关好门'
  ),
  '勤学楼、博学楼、图书馆、一站式服务中心北区四处需通过微信二维码小程序预约；当前数据库先记录文字说明，二维码图片待上传为静态资源后可补充到附件表或详情页。',
  JSON_ARRAY('面试亭', '线上面试', '面试亭预约', '就业', '毕业生', '电子锁密码', '欣苑食堂', '勤学楼', '博学楼', '图书馆'),
  JSON_ARRAY(
    JSON_OBJECT('question', '每次可以使用多久？', 'answer', '每人每天单次使用不超过1小时。'),
    JSON_OBJECT('question', '需要提前多久预约？', 'answer', '学生申请时需提前一天预约，目前每天可申请使用2次，每时段仅限1人使用。'),
    JSON_OBJECT('question', '预约后不使用怎么办？', 'answer', '如面试计划有变，需至少提前半小时在“数智安农/面试亭预约学生管理”页面取消申请。'),
    JSON_OBJECT('question', '什么时候收到电子锁密码？', 'answer', '学校审批通过后，会在面试前2小时收到包含面试亭电子锁密码的短信。'),
    JSON_OBJECT('question', '使用中遇到问题找谁？', 'answer', '可向欣苑四楼408室值班人员求助，或致电校学生就业指导中心：0551-65786432。')
  ),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.mstyysq.mstyysqlc',
  '2026-06-14 00:00:00.000'
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `handler_count` = VALUES(`handler_count`),
  `target_roles` = VALUES(`target_roles`),
  `entry_url` = VALUES(`entry_url`),
  `department` = VALUES(`department`),
  `contact_person` = VALUES(`contact_person`),
  `contact_phone` = VALUES(`contact_phone`),
  `service_time` = VALUES(`service_time`),
  `basis` = VALUES(`basis`),
  `materials` = VALUES(`materials`),
  `process_steps` = VALUES(`process_steps`),
  `notice` = VALUES(`notice`),
  `keywords` = VALUES(`keywords`),
  `faq` = VALUES(`faq`),
  `status` = VALUES(`status`),
  `source_url` = VALUES(`source_url`),
  `last_verified_at` = VALUES(`last_verified_at`);
