USE `aibs`;

INSERT INTO `service_items` (
  `id`,
  `title`,
  `category`,
  `description`,
  `handler_count`,
  `target_roles`,
  `entry_url`,
  `department`,
  `contact_person`,
  `contact_phone`,
  `service_time`,
  `basis`,
  `materials`,
  `process_steps`,
  `notice`,
  `keywords`,
  `faq`,
  `status`,
  `source_url`,
  `last_verified_at`
) VALUES
(
  'online-service-process-development-application',
  '网上办事流程开发申请',
  '信息化服务',
  '各单位根据工作需要提出线下事务线上化改造需求，信息化办公室协同各单位开发网上办事流程。',
  26,
  JSON_ARRAY('教职工'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.bszntbsq.bszntbsqlc',
  '数据管理处（信息化办公室）',
  '杨春节',
  '0551-65786139',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('《办事指南详情》电子版'),
  JSON_ARRAY('登录“网上办事大厅-网上办事流程开发申请”平台，填写网上办事项目信息', '上传《办事指南详情》电子版', '部门领导审核后，信息化办公室组织详细需求调研和开发，或视情况提出具体建议'),
  '《办事指南详情》空表和样例见附件链接。',
  JSON_ARRAY('网上办事流程', '流程开发', '办事流程开发', '线上化改造', '办事指南', '信息化办公室', '网上办事大厅'),
  JSON_ARRAY(),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.bszntbsq.bszntbsqlc',
  '2026-06-14 00:00:00.000'
),
(
  'faculty-email-service',
  '教工邮箱服务',
  '信息化服务',
  '为教职工提供 @ahau.edu.cn 邮箱服务，原则上每个教职工仅限申请 1 个邮箱账号。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://xxb.ahau.edu.cn/info/1181/4741.htm',
  '数据管理处（信息化办公室）',
  '康老师',
  '0551-65786196',
  '任何时间',
  '-',
  JSON_ARRAY('数智安农账号', '邮箱申请信息'),
  JSON_ARRAY('教职工进入数智安农', '在“我的邮件”栏目下方点击“申请邮箱”入口', '按页面要求自助申请邮箱'),
  '学校已开启邮箱二次验证功能；使用第三方邮箱客户端时，请先阅读二次验证相关帮助文档。',
  JSON_ARRAY('教工邮箱', '教师邮箱', 'ahau.edu.cn邮箱', '申请邮箱', '邮箱二次验证', '第三方邮箱客户端'),
  JSON_ARRAY(
    '教职工 @ahau.edu.cn 域名邮箱申请注册使用说明见附件链接。',
    '邮箱注册使用视频教程见附件链接。',
    '使用第三方邮箱客户端前，请阅读邮箱启用登录二次验证的使用提示。'
  ),
  'ENABLED',
  'https://xxb.ahau.edu.cn/info/1181/4741.htm',
  '2026-06-14 00:00:00.000'
),
(
  'faculty-resignation-online-application',
  '教职工离职线上申请',
  '人事服务',
  '为办理离职的教职工提供离职申请线上办理、各业务部门审批。',
  6,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.jzglzxssq.jzglzxssq',
  '党委教师工作部、人事处、人才办',
  '人事处沈老师、各业务部门经办老师',
  '0551-65786168、各业务部门经办人电话',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('按系统页面要求提交离职申请信息'),
  JSON_ARRAY('教职工按照要求提交信息', '各部门线上受理'),
  '各业务部门审批要求以系统流程和部门通知为准。',
  JSON_ARRAY('教职工离职', '离职申请', '离职线上申请', '人事处', '业务部门审批'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.jzglzxssq.jzglzxssq',
  '2026-06-14 00:00:00.000'
),
(
  'agricultural-innovation-base-bus-meal-reservation',
  '农业创新实践基地（原农业园）乘车就餐预约',
  '教务服务',
  '为前往大杨农业创新实践基地的师生提供乘车和就餐的预约服务，以便大杨农业创新实践基地提前做好准备。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://wk.ahau.edu.cn/default/coreplus/gwccjcyyxt/form/indexPage.jsp',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '方老师',
  '13075531489',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('预约乘车和就餐相关信息'),
  JSON_ARRAY('进入农业创新实践基地乘车就餐预约入口', '按页面要求选择乘车和就餐信息', '提交预约'),
  '预约截止时间为前一天晚 18:30 前，不接受提前 2 天以上的预约；节假日不预约，寒暑假及清明、五一、国庆、中秋、春节等按学校惯例停止班车和就餐。',
  JSON_ARRAY('农业创新实践基地', '农业园', '大杨基地', '乘车预约', '就餐预约', '班车预约', '教务处'),
  JSON_ARRAY(
    '平时工作周周六可以预约，需周五晚 19:00 之前预约。',
    '住宿学生可和食堂协商解决就餐。'
  ),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/coreplus/gwccjcyyxt/form/indexPage.jsp',
  '2026-06-14 00:00:00.000'
),
(
  'department-operation-account-application',
  '部门运维账号申请',
  '信息化服务',
  '申请单位部门运维账号及访问权限，包含 VPN、堡垒机、数据库运维系统、管理员账号统一门户、网站群系统、短信平台、申请单位公用邮箱等，适用本事项。',
  4,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.bmywzhsq.bmywzhlc',
  '数据管理处（信息化办公室）',
  '许陈',
  '0551-65786196',
  '工作日正常办公时间',
  '关于印发《安徽农业大学运维账号管理规定（试行）》的通知',
  JSON_ARRAY('申请单位信息', '需要申请的权限', '按系统要求提交的附件材料'),
  JSON_ARRAY('用户点击“申请单位运维账号”', '勾选需要申请的权限', '学院书记或部门领导审批同意', '数据管理处工作人员受理并办理'),
  '请按实际工作需要勾选权限，审批通过后由数据管理处工作人员受理办理。',
  JSON_ARRAY('部门运维账号', '运维账号', 'VPN', '堡垒机', '数据库运维系统', '管理员账号统一门户', '网站群系统', '短信平台', '公用邮箱'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.bmywzhsq.bmywzhlc',
  '2026-06-14 00:00:00.000'
),
(
  'smart-ahau-app-service',
  '数智安农APP服务',
  '信息化服务',
  '数智安农门户移动端 APP 与电脑版、微信版、企业微信版实现信息“多端一源”，适用于安卓、iOS 系统，原生鸿蒙系统需要依托第三方软件安装。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://my.ahau.edu.cn/sopplus/_upload/tpl/00/02/2/template2/main.htm',
  '数据管理处（信息化办公室）',
  '刘老师',
  '0551-65786196',
  '任何时间',
  '-',
  JSON_ARRAY('移动端设备', '数智安农账号'),
  JSON_ARRAY('进入 APP 安装使用说明页面', '按设备系统选择对应安装方式', '安装后使用数智安农账号登录'),
  '原生鸿蒙系统需要依托第三方软件安装。',
  JSON_ARRAY('数智安农APP', '智慧安农', '移动端', '安卓', 'iOS', '鸿蒙', 'APP安装'),
  JSON_ARRAY('APP 安装使用说明见入口链接。'),
  'ENABLED',
  'https://my.ahau.edu.cn/sopplus/_upload/tpl/00/02/2/template2/main.htm',
  '2026-06-14 00:00:00.000'
),
(
  'student-orientation-one-thing',
  '学生迎新一件事',
  '迎新服务',
  '面向本科生、研究生提供学生迎新一件事服务。',
  NULL,
  JSON_ARRAY('本科生', '研究生'),
  'https://my.ahau.edu.cn/default/work/ahau/xsyxyjs/xsyxyjs.jsp',
  '数据管理处（信息化办公室）',
  '-',
  '-',
  '-',
  '-',
  JSON_ARRAY('按系统页面要求办理迎新相关事项'),
  JSON_ARRAY('进入学生迎新一件事入口', '按页面提示办理迎新相关事项'),
  '具体办理内容以迎新系统页面为准。',
  JSON_ARRAY('学生迎新', '迎新一件事', '新生', '本科新生', '研究生新生', '报到'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/work/ahau/xsyxyjs/xsyxyjs.jsp',
  '2026-06-14 00:00:00.000'
),
(
  'union-member-join-application',
  '工会会员加入申请',
  '工会服务',
  '作为新教师入职一件事的组成事项，数据中心每日同步人事系统中具备工会会员资格的教职工信息数据推送到工会系统；具备会员资格的教职工在工会系统会员档案、会员登记栏目填写相关信息，提交工会会员登记，由工会相关老师审批受理。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://ghbg.ahau.edu.cn/union/sso',
  '工会',
  '薛老师',
  '0551-65786083',
  '工作日正常办公时间',
  '《中华总工会章程》',
  JSON_ARRAY('工会会员登记信息'),
  JSON_ARRAY('教职工自愿申请，通过工会系统线上申请', '分工会主席审批', '校工会分管会员管理人员审核', '符合入会条件且个人信息准确后入会'),
  '具备会员资格的教职工可在工会系统“会员档案-会员登记”栏目提交工会会员登记。',
  JSON_ARRAY('工会会员', '加入工会', '入会申请', '会员登记', '新教师入职', '工会系统'),
  JSON_ARRAY(),
  'ENABLED',
  'https://ghbg.ahau.edu.cn/union/sso',
  '2026-06-14 00:00:00.000'
),
(
  'young-teacher-mentor-system',
  '青年教师导师制',
  '人事服务',
  '青年教师导师制主要针对 35 周岁以下、首次从事高校教学工作且新入职的青年教师，由导师进行“一对一”指导和培养，学院负责导师制遴选工作，通过线上备案后实施具体培养工作。',
  88,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.qnjsdsz.qnjsdsz',
  '党委教师工作部、人事处、人才办',
  '王老师',
  '0551-65786553',
  '周一至周五 上午：08：00-11：30 下午：14：00-17：30（冬季） 下午：14：30-18：00（夏季）',
  '-',
  JSON_ARRAY('青年教师导师制备案相关信息'),
  JSON_ARRAY('学院遴选导师', '线上提交导师制备案信息', '实施具体培养工作'),
  '适用于 35 周岁以下、首次从事高校教学工作且新入职的青年教师。',
  JSON_ARRAY('青年教师导师制', '青年教师', '导师制', '新入职教师', '一对一指导', '人事处'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.qnjsdsz.qnjsdsz',
  '2026-06-14 00:00:00.000'
),
(
  'alumni-card',
  '校友卡',
  '校友服务',
  '面向在校学生和已经毕业或离校的师生校友，提供安徽农业大学校友卡微信小程序服务，也可以直接使用微信搜索“安徽农业大学校友卡”小程序，按照提示注册。',
  NULL,
  JSON_ARRAY('全部人员'),
  'https://andxyk.ahau.edu.cn/home/WeChathome.html',
  '校友会、教育基金会',
  '高老师、张老师',
  '0551-65786855',
  '任何时间',
  '-',
  JSON_ARRAY('按校友卡小程序要求填写注册信息'),
  JSON_ARRAY('进入校友卡入口或微信搜索“安徽农业大学校友卡”小程序', '按照提示注册', '注册后使用校友卡相关功能'),
  '校友卡包含校友返校二维码、校友爱心捐赠等功能。',
  JSON_ARRAY('校友卡', '安徽农业大学校友卡', '校友返校', '返校二维码', '校友捐赠', '教育基金会', '微信小程序'),
  JSON_ARRAY('校友返校二维码可用于刷码入校；校友爱心捐赠将用于助学帮扶、成长赋能、办学能力提升等教育事业。'),
  'ENABLED',
  'https://andxyk.ahau.edu.cn/home/WeChathome.html',
  '2026-06-14 00:00:00.000'
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `handler_count` = VALUES(`handler_count`),
  `target_roles` = VALUES(`target_roles`),
  `entry_url` = VALUES(`entry_url`),
  `department` = VALUES(`department`),
  `contact_person` = VALUES(`contact_person`),
  `contact_phone` = VALUES(`contact_phone`),
  `service_time` = VALUES(`service_time`),
  `basis` = VALUES(`basis`),
  `materials` = VALUES(`materials`),
  `process_steps` = VALUES(`process_steps`),
  `notice` = VALUES(`notice`),
  `keywords` = VALUES(`keywords`),
  `faq` = VALUES(`faq`),
  `status` = VALUES(`status`),
  `source_url` = VALUES(`source_url`),
  `last_verified_at` = VALUES(`last_verified_at`);

INSERT INTO `service_item_assets` (
  `id`,
  `service_item_id`,
  `asset_type`,
  `title`,
  `url`,
  `alt_text`,
  `sort_order`
) VALUES
(
  'online-service-process-development-flow',
  'online-service-process-development-application',
  'image',
  '网上办事流程开发申请流程',
  '/service-assets/online-service-process-development-flow.png',
  '网上办事流程开发申请流程图',
  1
),
(
  'online-service-process-development-empty-template',
  'online-service-process-development-application',
  'link',
  '《办事指南详情》空表',
  'https://i.ahau.edu.cn/_upload/ueditor/file/20231106/1699258769256047796.docx',
  '《办事指南详情》空表',
  2
),
(
  'online-service-process-development-sample',
  'online-service-process-development-application',
  'link',
  '《办事指南详情》样例',
  'https://i.ahau.edu.cn/_upload/ueditor/file/20231106/1699258804172031448.docx',
  '《办事指南详情》样例',
  3
),
(
  'faculty-email-registration-guide',
  'faculty-email-service',
  'link',
  '教职工邮箱申请注册使用说明',
  'https://xxb.ahau.edu.cn/info/1181/4741.htm',
  '教职工 @ahau.edu.cn 域名邮箱申请注册使用说明',
  1
),
(
  'faculty-email-video-guide',
  'faculty-email-service',
  'link',
  '邮箱注册使用视频教程',
  'https://xxb.ahau.edu.cn/info/1161/5031.htm',
  '邮箱注册使用视频教程',
  2
),
(
  'faculty-email-two-factor-guide',
  'faculty-email-service',
  'link',
  '邮箱启用登录二次验证的使用提示',
  'https://xxb.ahau.edu.cn/info/1181/4711.htm',
  '邮箱启用登录二次验证的使用提示',
  3
),
(
  'department-operation-account-flow',
  'department-operation-account-application',
  'image',
  '部门运维账号申请流程',
  '/service-assets/department-operation-account-flow.png',
  '部门运维账号申请流程图',
  1
),
(
  'union-member-join-flow',
  'union-member-join-application',
  'image',
  '工会会员入会流程',
  '/service-assets/union-member-join-flow.png',
  '安徽农业大学工会会员入会流程图',
  1
)
ON DUPLICATE KEY UPDATE
  `service_item_id` = VALUES(`service_item_id`),
  `asset_type` = VALUES(`asset_type`),
  `title` = VALUES(`title`),
  `url` = VALUES(`url`),
  `alt_text` = VALUES(`alt_text`),
  `sort_order` = VALUES(`sort_order`);
