USE `aibs`;

INSERT INTO `service_items` (
  `id`,
  `title`,
  `category`,
  `description`,
  `handler_count`,
  `target_roles`,
  `entry_url`,
  `department`,
  `contact_person`,
  `contact_phone`,
  `service_time`,
  `basis`,
  `materials`,
  `process_steps`,
  `notice`,
  `keywords`,
  `faq`,
  `status`,
  `source_url`,
  `last_verified_at`
) VALUES
(
  'digital-agriculture-password-appeal',
  '数智安农密码申诉',
  '信息化服务',
  '若用户通过忘记密码功能操作时，发现数智安农系统中个人手机号不存在或信息有误，导致无法自助修改密码，可通过密码申诉渠道办理。申诉类型包括“忘记密码、复学、延期毕业、邮箱密码”四种，需按对应类型提交相关信息。工作人员受理申诉并完成密码重置后，会向用户提交登记的手机号发送密码重置反馈短信予以告知。',
  NULL,
  JSON_ARRAY('全部人员'),
  'https://wk.ahau.edu.cn/default/work/ahau_mmsssq/mmsssq/nmIndex.jsp',
  '数据管理处（信息化办公室）',
  '康老师、王老师、许老师、陈老师',
  '0551-65786196',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('申诉类型对应信息', '可接收反馈短信的手机号'),
  JSON_ARRAY('进入数智安农密码申诉页面', '选择申诉类型：忘记密码、复学、延期毕业或邮箱密码', '按对应类型提交相关信息', '工作人员受理申诉并完成密码重置', '系统向用户登记手机号发送密码重置反馈短信'),
  '适用于个人手机号不存在或信息有误，导致无法通过忘记密码功能自助修改密码的情况。',
  JSON_ARRAY('数智安农密码申诉', '密码申诉', '忘记密码', '复学密码', '延期毕业密码', '邮箱密码', '手机号有误', '密码重置', '统一身份认证'),
  JSON_ARRAY(
    JSON_OBJECT('question', '什么情况需要密码申诉', 'answer', '通过忘记密码功能操作时，如果系统中个人手机号不存在或信息有误，导致无法自助修改密码，可以走密码申诉。'),
    JSON_OBJECT('question', '密码申诉有哪些类型', 'answer', '包括忘记密码、复学、延期毕业、邮箱密码四种类型。')
  ),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/work/ahau_mmsssq/mmsssq/nmIndex.jsp',
  '2026-06-15 00:00:00.000'
),
(
  'undergraduate-course-exempt-listen-application',
  '本科生课程免听申请',
  '教务服务',
  '学生在修读课程时，存在因重修、补修课程造成本人课程表冲突无法正常上课、退役返校学生免修剩余学年的全部体育课、军事技能和军事理论等课程、外国留学生按相关规定免修部分公共必修课程等情形的，可以申请课程免听（或自修）、免修。',
  NULL,
  JSON_ARRAY('本科生'),
  'https://bkjw.ahau.edu.cn/student/for-std/exempt-listen-apply',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '张老师',
  '0551-65786861',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('课程免听或免修申请相关材料'),
  JSON_ARRAY('本科生进入课程免听申请页面', '根据课程冲突、重修补修、退役返校或留学生免修等实际情况选择申请类型', '按系统要求填写申请信息并提交', '等待相关部门审核', '按审核结果执行课程学习、考试或免修安排'),
  '完全线上教学课程不予办理免听（或自修）。除学校规定情形外，其他课程均不予办理免听（或自修）、免修。',
  JSON_ARRAY('课程免听', '免听申请', '免修', '自修', '重修课程冲突', '补修课程冲突', '退役返校', '体育课免修', '军事理论免修', '张老师'),
  JSON_ARRAY(
    JSON_OBJECT('question', '重修补修课程冲突怎么办', 'answer', '学生因重修、补修课程造成本人课程表冲突无法正常上课的，应申请重修课程或补修课程的免听（或自修）。'),
    JSON_OBJECT('question', '退役返校学生哪些课程可以免修', 'answer', '可按相关政策免修剩余学年的全部体育课、军事技能和军事理论等课程并直接获得学分，免修军事理论与军事训练到武装部登记，免修体育课到体育部登记。'),
    JSON_OBJECT('question', '免修课程还要考试吗', 'answer', '免修课程无须参加考试。')
  ),
  'ENABLED',
  'https://bkjw.ahau.edu.cn/student/for-std/exempt-listen-apply',
  '2026-06-15 00:00:00.000'
),
(
  'server-hosting-service',
  '服务器托管服务',
  '信息化服务',
  '为教师提供服务器托管服务。未按照《关于印发〈安徽农业大学信息化项目建设管理规定（试行）〉的通知》自行建设的项目，学校不提供各类网络资源。',
  43,
  JSON_ARRAY('教职工'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.fwqtgsq.fwqtgsq',
  '数据管理处（信息化办公室）',
  '康琳琳',
  '0551-65786196',
  '正常办公时间',
  '《安徽农业大学校园网服务器（主机/硬件）托管协议》',
  JSON_ARRAY('服务器托管申请信息', '待托管设备', '安全扫描相关要求'),
  JSON_ARRAY('在“网上办事大厅/服务器托管申请”提交线上使用申请', '申请办理并完成审批', '审批结束后将所要托管的设备带至数据中心机房', '由信息化办公室专人配合将服务器上架', '通过服务器安全扫描后完成开通服务'),
  '该事项此前被标记为当前不可用，先入库保留资料，暂不向用户推荐或返回。',
  JSON_ARRAY('服务器托管', '主机托管', '硬件托管', '数据中心机房', '服务器上架', '安全扫描', '康琳琳'),
  JSON_ARRAY(),
  'DISABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.fwqtgsq.fwqtgsq',
  '2026-06-15 00:00:00.000'
),
(
  'school-classroom-schedule-query',
  '全校教室课表查询',
  '教务服务',
  '教职工可通过综合服务-全校教室课表查询，根据所选教室进行课程查询。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://bkjw.ahau.edu.cn/home/#/home',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '李老师',
  '0551-65786169',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('教务系统账号', '需要查询的教室信息'),
  JSON_ARRAY('进入本科教务系统', '选择综合服务', '进入全校教室课表查询', '根据所选教室筛选并查询课程安排'),
  '课程数据以本科教务系统显示为准。',
  JSON_ARRAY('全校教室课表查询', '教室课表', '课表查询', '教室课程', '本科教务系统', '综合服务', '李老师'),
  JSON_ARRAY(),
  'ENABLED',
  'https://bkjw.ahau.edu.cn/home/#/home',
  '2026-06-15 00:00:00.000'
),
(
  'public-mailbox-service',
  '公共邮箱服务（申请、变更、注销）',
  '信息化服务',
  '为教职工提供公共邮箱申请、变更、注销服务。',
  1,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.ggyxsq.ggyxsq',
  '数据管理处（信息化办公室）',
  '-',
  '-',
  '-',
  '-',
  JSON_ARRAY('公共邮箱申请、变更或注销相关信息'),
  JSON_ARRAY('进入公共邮箱服务申请页面', '按申请、变更或注销类型填写信息', '提交后等待相关人员受理'),
  '具体办理材料和审核要求以系统页面显示为准。',
  JSON_ARRAY('公共邮箱', '公共邮箱服务', '邮箱申请', '邮箱变更', '邮箱注销', '单位邮箱', '公用邮箱'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.ggyxsq.ggyxsq',
  '2026-06-15 00:00:00.000'
),
(
  'visitor-person-appointment',
  '访客预约（仅人员）',
  '保卫服务',
  '访客预约服务用于校外人员因公或因私到校访问，被访单位（人）可线上审核预约申请，审核通过后可在访问时间内进校。',
  NULL,
  JSON_ARRAY('访客(社会人员)'),
  'https://e.ahau.edu.cn/win/zhmz.htm',
  '保卫处',
  '各单位管理员或教职工',
  '0551-65786766',
  '随时',
  '-',
  JSON_ARRAY('访客身份信息', '被访单位或被访人信息', '访问事由和访问时间'),
  JSON_ARRAY('访客进入预约页面', '按页面要求填写访客、被访单位或被访人、访问事由、访问时间等信息', '提交预约申请', '等待被访单位或被访人审核', '审核通过后在预约时间内入校'),
  '具体通行方式和审核要求以保卫处系统显示为准。',
  JSON_ARRAY('访客预约', '人员预约', '访客入校', '社会人员', '保卫处', '被访人', '校外人员进校'),
  JSON_ARRAY(),
  'ENABLED',
  'https://e.ahau.edu.cn/win/zhmz.htm',
  '2026-06-15 00:00:00.000'
),
(
  'official-document-drafting',
  '安徽农业大学公文起草',
  '校务服务',
  '校级或二级单位部门起草正式公文，必须经过电子政务 OA 系统-公文处理-起草公文相应线上流程办理，经主办部门及协办部门负责人线上流转审阅后，由党政办统一发布电子政务-学校文件栏目。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://oa.ahau.edu.cn/ssologin',
  '党政办公室',
  '郑老师',
  '0551-65786010',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('相应公文电子档材料'),
  JSON_ARRAY('进入电子政务 OA 系统', '进入公文处理', '选择起草公文相应线上流程', '提交正式公文电子档材料', '经主办部门及协办部门负责人线上流转审阅', '由党政办统一发布至电子政务-学校文件栏目'),
  '校级或二级单位部门起草正式公文必须通过电子政务 OA 系统办理。',
  JSON_ARRAY('公文起草', '安徽农业大学公文起草', '电子政务', 'OA', '起草公文', '学校文件', '党政办公室', '郑老师'),
  JSON_ARRAY(),
  'ENABLED',
  'https://oa.ahau.edu.cn/ssologin',
  '2026-06-15 00:00:00.000'
),
(
  'school-class-schedule-query',
  '全校班级课表查询',
  '教务服务',
  '教职工可通过综合服务-全校班级课表查询进行筛选，对所需班级课表进行查询。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://bkjw.ahau.edu.cn/home/#/home',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '李老师',
  '0551-65786169',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('教务系统账号', '需要查询的班级信息'),
  JSON_ARRAY('进入本科教务系统', '选择综合服务', '进入全校班级课表查询', '筛选所需班级并查询课表'),
  '班级课表数据以本科教务系统显示为准。',
  JSON_ARRAY('全校班级课表查询', '班级课表', '课表查询', '班级课程', '本科教务系统', '综合服务', '李老师'),
  JSON_ARRAY(),
  'ENABLED',
  'https://bkjw.ahau.edu.cn/home/#/home',
  '2026-06-15 00:00:00.000'
),
(
  'undergraduate-library-orientation',
  '本科新生入馆教育',
  '图书馆服务',
  '作为本科生迎新一件事的组成事项，开学季任何时间，即将入学的新生可以通过本科新生入馆教育熟悉图书馆规章制度和借阅规定，考试完成后自动开通图书馆借阅权限。',
  NULL,
  JSON_ARRAY('本科生'),
  'https://ahnydxrgjy6.zxhnzq.com/',
  '图书馆、档案馆',
  '吴老师',
  '0551-65786335',
  '开学季正常办公时间',
  '-',
  JSON_ARRAY('新生身份信息'),
  JSON_ARRAY('进入本科新生入馆教育页面', '学习图书馆规章制度和借阅规定', '完成入馆教育考试', '考试完成后自动开通图书馆借阅权限'),
  '如有任何问题，请咨询图书馆 0551-65786335。',
  JSON_ARRAY('本科新生入馆教育', '入馆教育', '新生入馆', '图书馆借阅权限', '迎新一件事', '吴老师', '图书馆'),
  JSON_ARRAY(
    JSON_OBJECT('question', '入馆教育完成后有什么作用', 'answer', '考试完成后会自动开通图书馆借阅权限。')
  ),
  'ENABLED',
  'https://ahnydxrgjy6.zxhnzq.com/',
  '2026-06-15 00:00:00.000'
),
(
  'campus-card-transaction-detail',
  '一卡通交易明细',
  '财务服务',
  '为师生提供一卡通交易明细查询服务。',
  NULL,
  JSON_ARRAY('研究生', '教职工', '本科生'),
  'https://ykt.ahau.edu.cn/zsanapp/web/TransactionQry.aspx#',
  '财务处',
  '陈老师',
  '0551-65786419',
  '任何时间',
  '-',
  JSON_ARRAY('一卡通账户信息'),
  JSON_ARRAY('进入一卡通交易明细页面', '按页面提示登录或确认身份', '查询一卡通交易明细'),
  '交易明细以一卡通系统显示为准。',
  JSON_ARRAY('一卡通交易明细', '一卡通明细', '交易明细', '消费明细', '校园卡明细', '财务处', '陈老师'),
  JSON_ARRAY(),
  'ENABLED',
  'https://ykt.ahau.edu.cn/zsanapp/web/TransactionQry.aspx#',
  '2026-06-15 00:00:00.000'
),
(
  'security-incident-report',
  '治安事件提报',
  '保卫服务',
  '面向本科生、研究生、教职工提供治安事件提报服务。',
  NULL,
  JSON_ARRAY('本科生', '研究生', '教职工'),
  'https://xssq.ahau.edu.cn/security/h5/#/pkgSecurityincidents/event/event',
  '保卫处',
  '保卫处治安科',
  '0551-65786766',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('治安事件相关图片', '必要事件信息'),
  JSON_ARRAY('进入治安事件提报页面', '上传治安事件相关图片', '填写必要信息', '提交后等待保卫处处理'),
  '请如实填写治安事件信息；紧急情况应优先联系保卫处或报警。',
  JSON_ARRAY('治安事件提报', '治安事件', '事件提报', '安全事件', '保卫处', '治安科', '上传图片'),
  JSON_ARRAY(),
  'ENABLED',
  'https://xssq.ahau.edu.cn/security/h5/#/pkgSecurityincidents/event/event',
  '2026-06-15 00:00:00.000'
),
(
  'personalized-course-selection-application',
  '个性化选课申请',
  '教务服务',
  '面向本科生提供个性化选课服务，主要服务时间在每个学期的第 X 周至第 X 周。',
  NULL,
  JSON_ARRAY('数据管理处测试'),
  'https://bkjw.ahau.edu.cn/student/for-std/course-select-apply',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '张老师',
  '0551-65786861',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('个性化选课申请信息'),
  JSON_ARRAY('进入个性化选课申请页面', '按系统要求填写申请信息', '提交后等待审核'),
  '该事项当前面向对象标注为数据管理处测试，先入库但保持 DISABLED，暂不向普通用户推荐或返回。',
  JSON_ARRAY('个性化选课', '选课申请', '本科生选课', '课程选择', '教务系统', '张老师'),
  JSON_ARRAY(),
  'DISABLED',
  'https://bkjw.ahau.edu.cn/student/for-std/course-select-apply',
  '2026-06-15 00:00:00.000'
),
(
  'final-exam-delay-application',
  '期末考试缓考申请',
  '教务服务',
  '期末考试缓考申请入口。',
  NULL,
  JSON_ARRAY('数据管理处测试'),
  'https://bkjw.ahau.edu.cn/student/for-std/exam-delay-apply',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '张老师',
  '0551-65786861',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('缓考申请相关材料'),
  JSON_ARRAY('进入期末考试缓考申请页面', '按系统要求填写申请信息并上传材料', '提交后等待审核'),
  '该事项当前面向对象标注为数据管理处测试，先入库但保持 DISABLED，暂不向普通用户推荐或返回。',
  JSON_ARRAY('期末考试缓考', '缓考申请', '考试缓考', '期末缓考', '教务系统', '张老师'),
  JSON_ARRAY(),
  'DISABLED',
  'https://bkjw.ahau.edu.cn/student/for-std/exam-delay-apply',
  '2026-06-15 00:00:00.000'
),
(
  'undergraduate-leave-request',
  '本科生请销假',
  '学生服务',
  '为本科生提供线上请销假申请及审批服务。',
  NULL,
  JSON_ARRAY('本科生'),
  'https://zhxg.ahau.edu.cn/xglckz/#/login',
  '党委学生工作部、党委武装部、学生处（学生资管中心、大学生就业指导中心）',
  '阿孜老师',
  '0551-65780064',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('请假或销假相关信息'),
  JSON_ARRAY('进入本科生请销假系统', '填写请假或销假申请信息', '提交后等待审批', '按审批结果执行请销假安排'),
  '具体审批流程和材料要求以系统页面显示为准。',
  JSON_ARRAY('本科生请销假', '请假', '销假', '学生请假', '本科生请假', '学工系统', '阿孜老师'),
  JSON_ARRAY(),
  'ENABLED',
  'https://zhxg.ahau.edu.cn/xglckz/#/login',
  '2026-06-15 00:00:00.000'
),
(
  'undergraduate-off-campus-residence-withdrawal',
  '学生走读退宿退费办理',
  '学生服务',
  '本事项适用于本科学生因各种原因需要办理走读申请及各单位线上审核。',
  NULL,
  JSON_ARRAY('本科生'),
  'https://zhxg.ahau.edu.cn/xglckz/#/login',
  '党委学生工作部、党委武装部、学生处（学生资管中心、大学生就业指导中心）',
  '学生辅导员、各学院、学工部、总务部、财务处',
  '学生辅导员、各学院、学工部、总务部、财务处联系电话',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('走读申请表', '走读协议', '有效材料'),
  JSON_ARRAY('学生提交走读申请表和走读协议等有效材料，需有关人员签字', '辅导员审核', '学院审核', '学工部审核', '总务部审核，办理走读办理完成学生宿舍退宿工作', '财务处审核，办理退费工作'),
  '具体审核要求和办理进度以学工系统及相关部门通知为准。',
  JSON_ARRAY('走读退宿退费', '学生走读', '本科生走读', '退宿', '退费', '宿舍退费', '辅导员审核', '学工部'),
  JSON_ARRAY(),
  'ENABLED',
  'https://zhxg.ahau.edu.cn/xglckz/#/login',
  '2026-06-15 00:00:00.000'
),
(
  'graduation-student-reexam-application',
  '结业学生返校考试申请',
  '教务服务',
  '主要面向结业学生提供返校考试申请服务。',
  NULL,
  JSON_ARRAY('本科生(结业)-树唯教务系统'),
  'https://bkjw.ahau.edu.cn/student/for-std/re-examination-apply',
  '教务处（招生办）、教学督导室、教师教学发展中心、创新创业学院',
  '洪老师',
  '0551-65786189',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('结业学生返校考试申请相关材料'),
  JSON_ARRAY('进入结业学生返校考试申请页面', '按系统要求填写返校考试申请信息', '提交后等待审核'),
  '适用于结业学生返校考试申请，具体要求以本科教务系统显示为准。',
  JSON_ARRAY('结业学生返校考试', '返校考试申请', '结业考试', '本科生结业', '树唯教务系统', '洪老师'),
  JSON_ARRAY(),
  'ENABLED',
  'https://bkjw.ahau.edu.cn/student/for-std/re-examination-apply',
  '2026-06-15 00:00:00.000'
),
(
  'campus-card-bank-transfer-recharge',
  '一卡通充值银校圈存',
  '财务服务',
  '为在校师生提供线上银校圈存服务。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://ykt.ahau.edu.cn/zsanapp/web/BankPay.aspx#',
  '财务处',
  '陈老师',
  '0551-65786419',
  '任何时间',
  '-',
  JSON_ARRAY('一卡通账户信息', '银行卡或圈存相关信息'),
  JSON_ARRAY('进入一卡通充值银校圈存页面', '按页面提示登录或确认身份', '选择充值或圈存方式', '完成线上银校圈存操作'),
  '充值和圈存结果以一卡通系统显示为准。',
  JSON_ARRAY('一卡通充值', '银校圈存', '一卡通圈存', '校园卡充值', '校园卡圈存', '财务处', '陈老师'),
  JSON_ARRAY(),
  'ENABLED',
  'https://ykt.ahau.edu.cn/zsanapp/web/BankPay.aspx#',
  '2026-06-15 00:00:00.000'
),
(
  'fire-hazard-report',
  '消防隐患提报',
  '保卫服务',
  '面向全校师生，一旦发现学校存在消防隐患风险，可以在线提报。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://xssq.ahau.edu.cn/security/h5/#/pkgSecurityincidents/hiddenDanger/hiddenDanger',
  '保卫处',
  '保卫处消防科',
  '0551-65786766',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('消防隐患图片', '必要隐患信息'),
  JSON_ARRAY('进入消防隐患提报页面', '上传隐患图片', '填写必要信息', '提交后等待保卫处处理'),
  '请如实填写消防隐患信息；紧急火情应优先拨打火警电话或联系保卫处。',
  JSON_ARRAY('消防隐患提报', '消防隐患', '隐患提报', '消防安全', '保卫处', '消防科', '上传隐患图片'),
  JSON_ARRAY(),
  'ENABLED',
  'https://xssq.ahau.edu.cn/security/h5/#/pkgSecurityincidents/hiddenDanger/hiddenDanger',
  '2026-06-15 00:00:00.000'
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `handler_count` = VALUES(`handler_count`),
  `target_roles` = VALUES(`target_roles`),
  `entry_url` = VALUES(`entry_url`),
  `department` = VALUES(`department`),
  `contact_person` = VALUES(`contact_person`),
  `contact_phone` = VALUES(`contact_phone`),
  `service_time` = VALUES(`service_time`),
  `basis` = VALUES(`basis`),
  `materials` = VALUES(`materials`),
  `process_steps` = VALUES(`process_steps`),
  `notice` = VALUES(`notice`),
  `keywords` = VALUES(`keywords`),
  `faq` = VALUES(`faq`),
  `status` = VALUES(`status`),
  `source_url` = VALUES(`source_url`),
  `last_verified_at` = VALUES(`last_verified_at`);
