USE `aibs`;

INSERT INTO `service_items` (
  `id`,
  `title`,
  `category`,
  `description`,
  `handler_count`,
  `target_roles`,
  `entry_url`,
  `department`,
  `contact_person`,
  `contact_phone`,
  `service_time`,
  `basis`,
  `materials`,
  `process_steps`,
  `notice`,
  `keywords`,
  `faq`,
  `status`,
  `source_url`,
  `last_verified_at`
) VALUES
(
  'union-member-transfer-application',
  '工会会员调转申请',
  '工会服务',
  '作为教职工离职一件事的组成事项。教职工办理离职事项流程中，由工会相关老师审批受理离职（自动退出安徽农业大学工会）后，在工会系统-会员档案-会员登记表中调整。',
  NULL,
  JSON_ARRAY('教职工'),
  'http://ghbg.ahau.edu.cn/union/sso',
  '工会',
  '薛老师',
  '0551-65786083',
  '工作日正常办公时间',
  '《中华总工会章程》',
  JSON_ARRAY('教职工离职相关申请信息'),
  JSON_ARRAY('教职工自愿申请离职，并通过工会系统线上申请', '分工会主席审批', '校工会分管会员管理人员审核', '办理退会或会员关系调整'),
  '该事项通常作为教职工离职一件事的组成事项，由工会相关老师审批受理。',
  JSON_ARRAY('工会会员调转', '工会调转', '工会会员', '退会', '教职工离职', '会员档案', '会员登记表'),
  JSON_ARRAY(),
  'ENABLED',
  'http://ghbg.ahau.edu.cn/union/sso',
  '2026-06-15 00:00:00.000'
),
(
  'faculty-private-leave-early-return-application',
  '教职工因私请假提前返回申请',
  '人事服务',
  '结合教职工请假（报备、出差）一张表中的因私请假数据，提供提前返回销假申请。例如教职工因私请假 7 天，实际使用假期 4 天，第 5 天起返岗工作时，适用于本事项。',
  0,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.jzgysqjtqfhsq.jzgysqjtqfhsq',
  '党委教师工作部、人事处、人才办',
  '沈老师',
  '0551-65786168',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('因私请假记录', '提前返岗相关说明'),
  JSON_ARRAY('进入教职工因私请假提前返回申请入口', '选择或关联原因私请假数据', '填写提前返回销假信息', '提交后等待审批'),
  '因私请假数据已与人事系统考勤数据同步共享，用于计算工资及绩效等，请按实际返岗情况填写。',
  JSON_ARRAY('因私请假提前返回', '提前返回申请', '销假', '教职工请假', '因私请假', '提前返岗', '人事处'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.jzgysqjtqfhsq.jzgysqjtqfhsq',
  '2026-06-15 00:00:00.000'
),
(
  'major-event-network-support-service',
  '重大活动网络保障服务',
  '信息化服务',
  '重大活动网络保障服务是指校级大型直播、远程学术交流、线上答辩等特殊活动需要确保网络接入链路可靠性和稳定的服务。',
  0,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.zdhdwlbzfw.zdhdwlbzfw',
  '数据管理处（信息化办公室）',
  '张武',
  '0551-65786196',
  '工作日正常办公时间',
  '《中华人民共和国网络安全法》；《网络安全等级保护2.0标准》；《互联网用户账号信息管理规定》',
  JSON_ARRAY('活动信息', '活动场地', '接入需求', '用网规模', '测试安排'),
  JSON_ARRAY('申请人在“智慧安农-大型活动网络保障服务”填写申请信息', '工作人员现场查勘', '预约线下测试', '活动时间监测', '流程结束'),
  '需提前一周与信息化办公室联系确认活动场地，并明确有线、无线、带宽大小、运营商出口等接入需求及用网规模。网络保障只能保障我校至运营商接入链路及相应带宽，不能保障对端及相关应用。',
  JSON_ARRAY('重大活动网络保障', '大型活动网络保障', '网络保障', '直播网络', '线上答辩', '远程学术交流', '活动网络', '信息化办公室'),
  JSON_ARRAY('重大活动建议提前模拟场景测试。', '网络保障范围不包含对端平台和第三方应用稳定性。'),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.zdhdwlbzfw.zdhdwlbzfw',
  '2026-06-15 00:00:00.000'
),
(
  'student-apartment-dormitory-application',
  '学生公寓宿舍申请',
  '学生公寓服务',
  '学生公寓宿舍申请入口。',
  2,
  JSON_ARRAY('本科生', '研究生'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xsssgl.xsrzsqlc',
  '-',
  '李老师',
  '-',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('按系统页面要求提交的住宿申请信息'),
  JSON_ARRAY('进入学生公寓宿舍申请入口', '按页面提示填写住宿申请信息', '提交后等待受理'),
  '原始面向对象为“数据管理处-数据中心”，但事项名称为学生公寓宿舍申请，当前按学生相关服务收录；后续以学校正式权限配置为准。',
  JSON_ARRAY('学生公寓宿舍申请', '宿舍申请', '学生公寓', '入住申请', '住宿申请'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xsssgl.xsrzsqlc',
  '2026-06-15 00:00:00.000'
),
(
  'administrator-account-portal',
  '管理员账号门户',
  '信息化服务',
  '授权用户点击“在线办理”登录管理员账号门户，使用授权的运维管理工具，对被允许授权访问的服务器或算力资源开展运维管理工作。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://pamweb.ahau.edu.cn/',
  '数据管理处（信息化办公室）',
  '许老师',
  '0551-65786196',
  '即时办理',
  '-',
  JSON_ARRAY('授权账号', '数智安农账号密码', '短信验证码'),
  JSON_ARRAY('打开管理员账号门户', '在输入框中输入“web”后点击登录', '服务器地址默认为 pam.ahau.edu.cn', '输入数智安农账号密码', '输入短信验证码后登录使用'),
  '仅授权用户可使用管理员账号门户。请按授权范围使用运维管理工具。',
  JSON_ARRAY('管理员账号门户', '管理员账号', '统一门户', 'PAM', '运维管理工具', 'pamweb', '服务器运维', '算力资源运维'),
  JSON_ARRAY(),
  'ENABLED',
  'https://pamweb.ahau.edu.cn/',
  '2026-06-15 00:00:00.000'
),
(
  'data-integration-application',
  '数据对接申请',
  '数据服务',
  '全域数据中心提供系统数据接入和数据申请使用服务。校内各单位可按数据资源管理要求，将本部门维护管理的数据对接至全域数据中心，也可在遵循数据安全的前提下申请使用已有业务系统数据。',
  0,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.sjdjzbsq.sjdjzbsq',
  '数据管理处（信息化办公室）',
  '-',
  '-',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('数据库基本信息', '线下数据文件', '业务数据信息表', '接口对接标准文档相关信息'),
  JSON_ARRAY('在网上办事大厅搜索“数据对接申请”流程并发起申请', '如需数据接入，对接内容选择“数据接入”', '根据类型选择数据库接入或线下数据接入（excel）并填写信息', '如需数据使用，对接内容选择“数据使用”', '选择库表对接或接口对接并上传需要申请的业务数据信息表', '提交申请并等待数据管理处安排专人负责对接'),
  '数据接入前，各部门需确保本部门业务系统数据质量。点击申请时需进行相关弹窗信息确认。',
  JSON_ARRAY('数据对接申请', '数据接入', '数据使用', '全域数据中心', '数据库接入', '线下数据接入', '库表对接', '接口对接', '业务数据信息表'),
  JSON_ARRAY('数据库接入需填报数据库类型、数据库名、端口号、服务器 IP 等信息。', '线下数据接入适用于 excel、word 等线下积累数据线上化。', '接口对接可先下载接口对接标准文档，自行判断接口复杂度。'),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.sjdjzbsq.sjdjzbsq',
  '2026-06-15 00:00:00.000'
),
(
  'network-information-point-addition-application',
  '信息点补增申请',
  '信息化服务',
  '网络信息点服务是指原场所确无信息点且具备补增条件的情况下开展的信息点补增服务。',
  17,
  JSON_ARRAY('教职工'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xxdbz.xxdbz',
  '数据管理处（信息化办公室）',
  '张武',
  '0551-65786196',
  '工作日正常办公时间',
  '《中华人民共和国网络安全法》；《网络安全等级保护2.0标准》；《互联网用户账号信息管理规定》',
  JSON_ARRAY('信息点补增申请信息', '场所信息', '用网需求说明'),
  JSON_ARRAY('申请人在“智慧安农-信息点补增申请”填写申请信息', '工作人员现场查勘', '预约线下施工', '流程结束'),
  '原场所已有信息点、室外环境场所不具备施工条件、商业盈利场所等情况不予增补。申请单位须遵守网络安全法律法规和学校相关规定。',
  JSON_ARRAY('信息点补增', '网络信息点', '信息点申请', '新增网口', '网络端口', '线下施工', '信息化办公室'),
  JSON_ARRAY(),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xxdbz.xxdbz',
  '2026-06-15 00:00:00.000'
),
(
  'sms-sending-application',
  '短信发送申请',
  '信息化服务',
  '安徽农业大学短信平台是校园网与手机无线连接的信息通道，是“智慧安农”中的应用信息系统，可实现与学生或老师指定号码进行短信批量发送和自定义发送。',
  31,
  JSON_ARRAY('教职工'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.dxfssqlc.dxfssqlc',
  '数据管理处（信息化办公室）',
  '康琳琳',
  '0551-65786196',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('短信发送内容', '发送对象或号码信息', '按系统要求提交的审批材料'),
  JSON_ARRAY('申请人提交短信发送申请', '单位领导审核或单位分管短信平台领导审核', '书记审批意见', '分管校领导审核', '信息办公室办理', '流程结束'),
  '各单位信息员是短信内容校对负责人，负责敏感词语查验；各单位分管领导为短信内容审批责任人，负责政治把关。通过学校短信平台发送短信须严格落实校对和审核制度。',
  JSON_ARRAY('短信发送申请', '短信平台', '批量短信', '自定义短信', '短信审批', '智慧安农短信', '数据管理处'),
  JSON_ARRAY(),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.dxfssqlc.dxfssqlc',
  '2026-06-15 00:00:00.000'
),
(
  'graduate-destination-leave-management',
  '研究生去向管理（请假）',
  '研究生服务',
  '面向全校在读研究生，提供因私请假线上申请、审批功能，研究生院掌握总体情况。研究生如需参加公务出差，可由带队负责老师在教职工请假（报备、出差）一张表中添加为同行人。',
  NULL,
  JSON_ARRAY('研究生'),
  'https://yjsxt.ahau.edu.cn/',
  '党委研究生工作部、研究生院',
  '朱老师',
  '0551-65786365',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('研究生请假申请信息', '请假事由及时间'),
  JSON_ARRAY('登录研究生系统', '进入研究生去向管理或请假相关入口', '填写因私请假信息', '提交后等待审批'),
  '研究生公务出差不由本人单独发起，可由带队负责老师在教职工请假（报备、出差）一张表中添加为同行人。',
  JSON_ARRAY('研究生请假', '研究生去向管理', '研究生因私请假', '研究生院', '请假审批', '研究生系统'),
  JSON_ARRAY(),
  'ENABLED',
  'https://yjsxt.ahau.edu.cn/',
  '2026-06-15 00:00:00.000'
),
(
  'faculty-off-campus-part-time-innovation-entrepreneurship-application',
  '教职工校外兼职创新创业申请',
  '人事服务',
  '适用于在职教学科研人员。专业技术辅助人员确因专业建设等需要从事公益性兼职的，按照从严控制原则，允许适度兼职，适用于本事项。',
  NULL,
  JSON_ARRAY('教职工'),
  'https://hr.ahau.edu.cn/templates/attestation/sso/ssologon.jsp?tabid=2',
  '党委教师工作部、人事处、人才办',
  '沈老师',
  '0551-65786168',
  '-',
  '安徽农业大学兼职创新创业管理办法.pdf',
  JSON_ARRAY('校外兼职创新创业申请相关材料'),
  JSON_ARRAY('进入人事相关系统入口', '按页面要求填写校外兼职创新创业申请信息', '上传或提交相关材料', '提交后等待审批'),
  '适用对象和审批要求以《安徽农业大学兼职创新创业管理办法》及系统页面提示为准。',
  JSON_ARRAY('校外兼职', '兼职创新创业', '教职工兼职', '创新创业申请', '人事处', '在职教学科研人员'),
  JSON_ARRAY(),
  'ENABLED',
  'https://hr.ahau.edu.cn/templates/attestation/sso/ssologon.jsp?tabid=2',
  '2026-06-15 00:00:00.000'
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `handler_count` = VALUES(`handler_count`),
  `target_roles` = VALUES(`target_roles`),
  `entry_url` = VALUES(`entry_url`),
  `department` = VALUES(`department`),
  `contact_person` = VALUES(`contact_person`),
  `contact_phone` = VALUES(`contact_phone`),
  `service_time` = VALUES(`service_time`),
  `basis` = VALUES(`basis`),
  `materials` = VALUES(`materials`),
  `process_steps` = VALUES(`process_steps`),
  `notice` = VALUES(`notice`),
  `keywords` = VALUES(`keywords`),
  `faq` = VALUES(`faq`),
  `status` = VALUES(`status`),
  `source_url` = VALUES(`source_url`),
  `last_verified_at` = VALUES(`last_verified_at`);

INSERT INTO `service_item_assets` (
  `id`,
  `service_item_id`,
  `asset_type`,
  `title`,
  `url`,
  `alt_text`,
  `sort_order`
) VALUES
(
  'union-member-transfer-flow',
  'union-member-transfer-application',
  'image',
  '工会会员调转申请流程',
  '/service-assets/union-member-transfer-flow.png',
  '安徽农业大学工会会员退会流程图',
  1
),
(
  'major-event-network-support-flow',
  'major-event-network-support-service',
  'image',
  '重大活动网络保障服务流程',
  '/service-assets/major-event-network-support-flow.png',
  '重大活动网络保障服务流程图',
  1
),
(
  'administrator-account-portal-login',
  'administrator-account-portal',
  'image',
  '管理员账号门户登录页面',
  '/service-assets/administrator-account-portal-login.png',
  '管理员账号统一门户登录页面截图',
  1
),
(
  'administrator-account-portal-sms-code',
  'administrator-account-portal',
  'image',
  '管理员账号门户短信验证码页面',
  '/service-assets/administrator-account-portal-sms-code.png',
  '管理员账号统一门户短信验证码页面截图',
  2
),
(
  'network-information-point-addition-flow',
  'network-information-point-addition-application',
  'image',
  '信息点补增申请流程',
  '/service-assets/network-information-point-addition-flow.png',
  '信息点补增申请流程图',
  1
),
(
  'sms-sending-application-flow',
  'sms-sending-application',
  'image',
  '短信发送申请审批流程',
  '/service-assets/sms-sending-application-flow.png',
  '短信发送申请审批流程图',
  1
)
ON DUPLICATE KEY UPDATE
  `service_item_id` = VALUES(`service_item_id`),
  `asset_type` = VALUES(`asset_type`),
  `title` = VALUES(`title`),
  `url` = VALUES(`url`),
  `alt_text` = VALUES(`alt_text`),
  `sort_order` = VALUES(`sort_order`);
