USE `aibs`;

INSERT INTO `service_items` (
  `id`,
  `title`,
  `category`,
  `description`,
  `handler_count`,
  `target_roles`,
  `entry_url`,
  `department`,
  `contact_person`,
  `contact_phone`,
  `service_time`,
  `basis`,
  `materials`,
  `process_steps`,
  `notice`,
  `keywords`,
  `faq`,
  `status`,
  `source_url`,
  `last_verified_at`
) VALUES
(
  'teacher-ethics-personal-report',
  '师德师风个人举报',
  '监督举报',
  '师德师风个人举报服务。',
  NULL,
  JSON_ARRAY('教职工', '本科生', '研究生'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.sdsfgrtj.sdsfgrtj',
  '党委教师工作部、人事处、人才办',
  '-',
  '-',
  '-',
  '-',
  JSON_ARRAY('按系统页面要求填写'),
  JSON_ARRAY('进入师德师风个人举报流程', '按页面要求填写并提交'),
  '具体受理范围和填报要求以系统页面及相关部门要求为准。',
  JSON_ARRAY('师德师风', '个人举报', '举报', '教师举报', '师德举报', '人事处'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.sdsfgrtj.sdsfgrtj',
  '2026-06-14 00:00:00.000'
),
(
  'network-account-recharge',
  '网络账号充值',
  '信息化服务',
  '校园网账号线上充值可通过多媒体机自助充值、智慧安农 APP 充值或内部转账充值办理。普通用户可选择自助充值或 APP 充值；需要通过内部转账报销网络费的用户，可在此入口办理。',
  28,
  JSON_ARRAY('研究生', '教职工', '本科生'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.wlzhcz.wlzhcz',
  '数据管理处（信息化办公室）',
  '康琳琳',
  '0551-65786196',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('网络报销信息单', '充值表格模版 EXCEL', '人员金额信息明细', '回执单或清晰截图'),
  JSON_ARRAY('进入“我要申请”', '登记上传相关充值信息', '信息化办公室办事人员办理网络费充值', '通过“我的申请”查看流程节点办理进度'),
  '回执单为财务处网络报销系统中带二维码的网络报销信息单文件，照片或截图需字迹清晰可见，否则可能退回。',
  JSON_ARRAY('网络账号充值', '校园网充值', '网费充值', '内部转账', '网络报销', '校园网账号', '信息化办公室'),
  JSON_ARRAY(
    '教职工已经在财务网络报销系统办理内转，并走完所有流程，生成网络报销信息单。',
    '下载充值表格模版 EXCEL，填写人员金额信息明细并上传。',
    '普通用户可通过多媒体机或智慧安农 APP 自助充值。'
  ),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.wlzhcz.wlzhcz',
  '2026-06-14 00:00:00.000'
),
(
  'virtual-server-service',
  '虚拟服务器服务',
  '信息化服务',
  '各单位根据部门业务信息化建设项目实际需要，提交信息化项目前期相关材料，可申请虚拟服务器。数据管理处受理后，提供虚拟服务器所需的 CPU、内存、存储等虚拟硬件、服务器操作系统和基础应用软件。',
  137,
  JSON_ARRAY('教职工'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xnfwqsq.xnfwqsq',
  '数据管理处（信息化办公室）',
  '许陈',
  '0551-65786196',
  '工作日正常办公时间',
  '安徽农业大学信息化建设管理办法',
  JSON_ARRAY('信息化项目前期相关材料', '虚拟服务器申请信息', '附件材料'),
  JSON_ARRAY('用户提出申请', '信息化办公室工作人员预审', '所属单位领导审批同意', '信息化办公室领导审批同意', '信息化办公室工作人员开通虚拟服务器并配置，反馈 IP 地址、VPN、堡垒机或特权管理账号密码、登录方式等使用信息'),
  '各单位申请虚拟服务器的人员需对服务器有基本管理能力，或委托业务系统工程师进行管理。教职工申请高性能计算请搜索“超算平台业务”。',
  JSON_ARRAY('虚拟服务器', '服务器申请', '云主机', '虚拟机', '信息化项目', 'VPN', '堡垒机', '超算平台'),
  JSON_ARRAY(),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xnfwqsq.xnfwqsq',
  '2026-06-14 00:00:00.000'
),
(
  'teacher-outside-lecture',
  '教职工外出讲学',
  '宣传统战',
  '为进一步改进工作作风、提高办事效率、优化教职工外出讲学审批流程，学校搭建了教职工外出讲学审批申请系统。',
  758,
  JSON_ARRAY('教职工'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.jzgwcjxsq.jzgwcjxsq',
  '党委宣传部（新闻中心）、党委统战部',
  '胡老师',
  '13855119207',
  '周一至周五 上午：08：00-11：30 下午：14：00-17：30',
  '-',
  JSON_ARRAY('按系统表单要求填写外出讲学申请材料'),
  JSON_ARRAY('申请人提交申请', '主办单位负责人审核', '国际交流合作处审核（涉外时）', '党委宣传部审核', '分管校领导审核', '流程结束'),
  '教职工外出讲学应提前一周提出申请。未经审批，不得擅自外出讲学。',
  JSON_ARRAY('教职工外出讲学', '外出讲学', '讲学审批', '论坛讲座', '党委宣传部', '统战部', '审批申请'),
  JSON_ARRAY(
    '教职工外出讲学必须坚持正确政治方向，遵守党的纪律和国家法律法规，践行社会主义核心价值观。',
    '外出讲学应按规定提前一周提出申请。'
  ),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.jzgwcjxsq.jzgwcjxsq',
  '2026-06-14 00:00:00.000'
),
(
  'student-accommodation-refund-payment',
  '学生零星退宿退费和入住缴费申请',
  '财务服务',
  '学生按宿管科流程线下办理完退宿或入住申请相关手续后，可在智慧安农系统中上传经宿管科签字盖章的退宿或入住申请表照片，财务处每日下载相关图片，及时办理入住缴费设置，并汇总集中办理退宿退费。',
  45,
  JSON_ARRAY('研究生', '本科生'),
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xstsrzjfsq.tstfrzjfsqlc',
  '财务处',
  '陈老师',
  '0551-65786419',
  '当日',
  '-',
  JSON_ARRAY('经宿管科签字盖章的退宿或入住申请表照片', '照片需清晰反映退宿时间或入住日期和住宿收费标准'),
  JSON_ARRAY('学生线下完成退宿或入住相关手续', '在智慧安农系统上传经宿管科签字盖章的退宿或入住申请表照片', '财务处审核', '财务处办理入住缴费设置或汇总办理退宿退费'),
  '上传照片需清晰反映退宿时间或入住日期和住宿收费标准。',
  JSON_ARRAY('退宿退费', '入住缴费', '住宿费', '零星退宿', '学生退费', '财务处', '宿管科'),
  JSON_ARRAY(),
  'ENABLED',
  'https://wk.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.xstsrzjfsq.tstfrzjfsqlc',
  '2026-06-14 00:00:00.000'
),
(
  'talent-recruitment',
  '人才招聘',
  '人事服务',
  '根据学校、各学院实际情况，提供高层次人才引进、全职博士后、专职辅导员和管理岗位招聘信息。应聘者可进入招聘网站了解具体岗位信息并投递。',
  NULL,
  JSON_ARRAY('本科生', '研究生', '教职工', '全部人员'),
  'https://zp.ahau.edu.cn/zp.html#/',
  '党委教师工作部、人事处、人才办',
  '牛老师、吕老师',
  '0551-65786065、0551-65780917',
  '工作日正常办公时间',
  '-',
  JSON_ARRAY('注册邮箱', '真实姓名', '身份证号', '个人简历信息', '岗位要求材料'),
  JSON_ARRAY('进入招聘官网', '注册账号或登录', '填写个人简历', '查看岗位并投递', '在个人中心查看或撤销已投递职位'),
  '人事处网站招聘信息栏目：https://rsc.ahau.edu.cn/index/zpxx.htm。咨询时间：上午 9:00-11:30，下午 14:00-17:00。',
  JSON_ARRAY('人才招聘', '招聘', '高层次人才', '博士后', '辅导员招聘', '管理岗位', '人事处', '应聘'),
  JSON_ARRAY(
    '应聘者注册账号时应使用有效电子邮箱、真实姓名和身份证号。',
    '忘记密码可在招聘官网登录页点击找回密码，按注册邮箱验证身份后设置新密码。',
    '首次注册成功后会自动切换至简历填写页面，基础信息中带星号项为必填。',
    '简历填写过程中长时间无操作，系统会自动退出，建议选择网络环境好的电脑填写简历和投递职位。',
    '职位投递成功后可在个人中心“我应聘的职位”中撤销；若系统提示职位申请正在处理中，则暂不可取消。'
  ),
  'ENABLED',
  'https://zp.ahau.edu.cn/zp.html#/',
  '2026-06-14 00:00:00.000'
),
(
  'medical-mutual-aid-subsidy',
  '医疗互助补助申请',
  '工会服务',
  '医疗互助补助申请。',
  7,
  JSON_ARRAY('教职工'),
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.ylhzbzsq.ylhzbzsqlc',
  '工会',
  '李老师',
  '0551-65786448',
  '现场即时办结',
  '-',
  JSON_ARRAY('补助申请表', '本人银行卡复印件', '职工医保住院结算单复印件及电子扫描件'),
  JSON_ARRAY('职工本人向所在单位工会提出申请并提供申请材料', '单位工会对职工提交的申请材料进行初审', '单位工会初审通过后汇总、签字盖章并线上申报', '省总工会职工服务中心复审单位工会提交的申请材料', '复审通过后补助金批汇总转账至职工所在单位工会账户', '所在单位工会根据补助金额明细及时将补助金银行转账至职工个人账户'),
  '材料缺少或未按要求提供时，由职工本人及所在单位工会补充完善后重新提交申请。',
  JSON_ARRAY('医疗互助', '医疗补助', '工会补助', '住院补助', '职工医保', '医疗互助补助'),
  JSON_ARRAY(),
  'ENABLED',
  'https://my.ahau.edu.cn/default/base/workflow/start.jsp?process=com.sudytech.work.ylhzbzsq.ylhzbzsqlc',
  '2026-06-14 00:00:00.000'
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `handler_count` = VALUES(`handler_count`),
  `target_roles` = VALUES(`target_roles`),
  `entry_url` = VALUES(`entry_url`),
  `department` = VALUES(`department`),
  `contact_person` = VALUES(`contact_person`),
  `contact_phone` = VALUES(`contact_phone`),
  `service_time` = VALUES(`service_time`),
  `basis` = VALUES(`basis`),
  `materials` = VALUES(`materials`),
  `process_steps` = VALUES(`process_steps`),
  `notice` = VALUES(`notice`),
  `keywords` = VALUES(`keywords`),
  `faq` = VALUES(`faq`),
  `status` = VALUES(`status`),
  `source_url` = VALUES(`source_url`),
  `last_verified_at` = VALUES(`last_verified_at`);

INSERT INTO `service_item_assets` (
  `id`,
  `service_item_id`,
  `asset_type`,
  `title`,
  `url`,
  `alt_text`,
  `sort_order`
) VALUES
(
  'network-account-recharge-flow',
  'network-account-recharge',
  'image',
  '网络账号充值办理流程',
  '/service-assets/network-account-recharge-flow.png',
  '网络账号充值办理流程图',
  1
),
(
  'network-account-recharge-media-guide',
  'network-account-recharge',
  'link',
  '多媒体机和智慧安农 APP 自助充值说明',
  'http://xxb.ahau.edu.cn/info/1120/1143.htm',
  '多媒体机和智慧安农 APP 自助充值说明',
  2
),
(
  'virtual-server-service-flow',
  'virtual-server-service',
  'image',
  '虚拟服务器服务办理流程',
  '/service-assets/virtual-server-service-flow.png',
  '虚拟服务器服务办理流程图',
  1
),
(
  'teacher-outside-lecture-approval-flow',
  'teacher-outside-lecture',
  'image',
  '教职工外出讲学审批流程',
  '/service-assets/teacher-outside-lecture-approval-flow.png',
  '教职工外出讲学审批流程图',
  1
),
(
  'teacher-outside-lecture-application-flow',
  'teacher-outside-lecture',
  'image',
  '教职工外出讲学申请流程',
  '/service-assets/teacher-outside-lecture-application-flow.png',
  '教职工外出讲学申请流程图',
  2
),
(
  'student-accommodation-refund-payment-flow',
  'student-accommodation-refund-payment',
  'image',
  '学生零星退宿退费和入住缴费审批流程',
  '/service-assets/student-accommodation-refund-payment-flow.png',
  '学生零星退宿退费和入住缴费审批流程图',
  1
),
(
  'talent-recruitment-info-page',
  'talent-recruitment',
  'link',
  '人事处网站招聘信息栏目',
  'https://rsc.ahau.edu.cn/index/zpxx.htm',
  '人事处网站招聘信息栏目',
  1
),
(
  'medical-mutual-aid-subsidy-flow',
  'medical-mutual-aid-subsidy',
  'image',
  '医疗互助补助申请流程',
  '/service-assets/medical-mutual-aid-subsidy-flow.png',
  '安徽省教科文卫体系统在职职工医疗互助补助申请流程图',
  1
)
ON DUPLICATE KEY UPDATE
  `service_item_id` = VALUES(`service_item_id`),
  `asset_type` = VALUES(`asset_type`),
  `title` = VALUES(`title`),
  `url` = VALUES(`url`),
  `alt_text` = VALUES(`alt_text`),
  `sort_order` = VALUES(`sort_order`);
